### ISSUE TITLE
'test_second_level': expected item missing in set

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2275] opened 2016-09-08 19:33 UTC
From: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158529136#L1386-L1393

```python
======================================================================
FAIL: test_second_level (storage.TestStoragePseudoHierarchy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/storage.py", line 329, in test_second_level
    set(['parent/child/grand/', 'parent/child/other/']))
AssertionError: Items in the second set but not the first:
'parent/child/other/'
```

**Comment by dhermes** [comment] 2016-09-08 19:46
Indeed. I've been tracking this on the last 5 or so builds. `storage` seems to be under duress (or just has different performance characteristics than before)

**Comment by dhermes** [comment] 2016-09-09 19:18
I went at this in #2252, maybe the issue is with how the `Iterator` stores prefixes?

**Comment by dhermes** [comment] 2016-09-09 23:13
I'm going to close this. I'm fairly certain that it was caused by #2289. We can re-open if we see the issue come back.

**Closed by dhermes** 2016-09-09 23:13 UTC
Labels: flaky, storage
