### ISSUE TITLE
storage access not working from within docker - from google.cloud import storage - ImportError: No module named 'google'

### ISSUE THREAD

**Issue by zinyosrim** [GoogleCloudPlatform/google-cloud-python#4683] opened 2018-01-03 12:44 UTC
I'm trying to access to access a bucket from within a docker image. I already searched the issues and stackoverflow and could not find any solution.

My dockerfile contains the line `RUN pip install --upgrade google-cloud-storage`
I'm executing following script within docker  
```
#!/bin/sh
export GOOGLE_APPLICATION_CREDENTIALS=google-api-keys.json
scrapy crawl phillips -o phillips.json > scrapy_log.txt   #my app producing the files to be uploaded
python gcpupload.py
```
The gcpupload does a file upload to the bucket:
```
from google.cloud import storage

def main():
	client = storage.Client()
	print('*****client initialized')
	bucket = client.get_bucket('artcollect')
	print('*****bucket set to artcollect')
	blob1 = bucket.blob('phillips.json')
	print('*****blob set to phillips.json')
	blob1.upload_from_filename(filename='phillips.json')
	print('*****upload phillips.json')
	blob2 = bucket.blob('scrapy_output.txt')
	blob2.upload_from_filename(filename='scrapy_output.txt')
	print('*****upload scrapy_output.txt')

if __name__ == "__main__":
	main()
```
Everything works ok so far in my local environment without docker and the files are uploaded as expected. But when running it from within docker I get the error message in the subject.

Can you please help me solving this issue.
Thanks
Zin

**Comment by jonparrott** [comment] 2018-01-03 17:13
@zinyosrim can you share the complete contents of the dockerfile with us?

**Comment by zinyosrim** [comment] 2018-01-03 17:15
@jonparrott here you go:

```
FROM ubuntu:16.04
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# update pip
RUN apt-get update
RUN apt-get install -y software-properties-common vim
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

# python, git
RUN apt-get install -y build-essential python python-dev python3.6 python3.6-dev python3-pip python3.6-venv
RUN apt-get install -y git
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

# python libs
RUN pip install requests
RUN pip install Pillow
RUN pip install botocore
RUN pip install rdflib
RUN pip install dateparser
RUN pip install sparqlwrapper
RUN pip install selenium
RUN pip install nltk --upgrade
RUN pip install scrapy
RUN pip install scrapy-splash
RUN pip install --upgrade google-cloud-storage

RUN git clone https://7cb3701d4605ff5898a12fe5653f2d0bca12e175:x-oauth-basic@github.com/zinyosrim/artcollect.git
RUN mkdir /temp
RUN cd /artcollect
RUN chmod 777 /artcollect/run_phillips.sh
CMD ["/artcollect/run_phillips.sh"]
```

**Comment by jonparrott** [comment] 2018-01-03 17:27
If you use a virtualenv (see below) does this error still occur?

Add this before your `python libs` section

```
RUN python -m virtualenv -p python3 /env
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH
```

(change python3 to python2 if necessary)

**Comment by dhermes** [comment] 2018-01-03 17:47
The issue is likely that `python3-pip` is not the "right" `pip` for the `python3.6` that comes with `ppa:jonathonf/python-3.6`.

I **strongly** recommend **always** using `${PYTHON} -m pip` rather than `pip`. (Here your `${PYTHON}` is likely `python3.6` but a bare `python` may be fine as well.)

**Comment by zinyosrim** [comment] 2018-01-03 18:22
@jonparrott @dhermes  I added:
```
RUN pip install virtualenv
RUN python -m virtualenv -p python3 /env
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH
```
and got the error message `/usr/bin/python: No module named virtualenv` during `docker-compose build --no-cache`

I changed the dockerfile to:
```
FROM ubuntu:16.04
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# update
RUN apt-get update
RUN apt-get install -y software-properties-common vim

# python
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get install -y build-essential python python-dev python3.6 python3.6-dev python3-pip python3.6-venv
RUN apt-get install -y git
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

RUN python3.6 -m pip install virtualenv
RUN python3.6 -m virtualenv -p python3 /env
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH

# python libs
RUN python3.6 -m pip install requests
RUN python3.6 -m pip install Pillow
RUN python3.6 -m pip install botocore
RUN python3.6 -m pip install rdflib
RUN python3.6 -m pip install dateparser
RUN python3.6 -m pip install sparqlwrapper
RUN python3.6 -m pip install selenium
RUN python3.6 -m pip install nltk --upgrade
RUN python3.6 -m pip install scrapy
RUN python3.6 -m pip install scrapy-splash
RUN python3.6 -m pip install --upgrade google-cloud-storage

RUN git clone https://7cb3701d4605ff5898a12fe5653f2d0bca12e175:x-oauth-basic@github.com/zinyosrim/artcollect.git
RUN mkdir /temp
RUN cd /artcollect
RUN chmod 777 /artcollect/run_phillips.sh
CMD ["/artcollect/run_phillips.sh"]
```
I created a fresh GCE VM, tried again - the problem remains.

**Comment by dhermes** [comment] 2018-01-03 18:28
After you've created `/env`, it won't be activated unless you `source /env/bin/activate`. Rather than doing that I would recommend just using `/env/bin/python3.6` rather than `python3.6`.

As for `/artcollect/run_phillips.sh`, you can / should modify it to use the correct Python binary (i.e. `/env/bin/python3.6`).

I am going to close this issue since there is no problem with our packaging (at least none that I can detect). The issue you are having is not one to be brushed off -- namespace packages and "wrong" `pip` is a problem for Python packaging -- it just isn't an issue with our library.

Even though I'm closing, I'm happy to continue helping you wade through this thorny issue.

The most relevant piece of advice is to make sure you are using the "same Python" everywhere (as I suggested above, just use `/env/bin/python3.6` and `/env/bin/python3.6 -m pip`.

**Closed by dhermes** 2018-01-03 18:28 UTC
Labels: api: storage, packaging, status: investigating, type: question

**Comment by zinyosrim** [comment] 2018-01-03 20:43
Finally got it working - Thank you very much for your help and instructions @dhermes @jonparrott

**Comment by exjohn** [comment] 2018-05-04 11:47
I have a very similar problem that hasn't been fixed with the above measures. The one difference is that I'm having the docker be built by gitlab CI.

This is my dockerfile:
```
FROM python:3.5.4

WORKDIR /PoC
ADD requirements.txt /PoC/
ADD *.py /PoC/
ADD *.json /PoC/

RUN python3 -m pip install --trusted-host pypi.python.org -r /PoC/requirements.txt

RUN apt-get update && apt-get install -y sudo vim
RUN sudo echo deb http://ftp.uk.debian.org/debian jessie-backports main >>/etc/apt/sources.list
RUN apt-get update && apt-get install -y ffmpeg
RUN mkdir /PoC/resources

CMD python3 server.py --port 4000

ENV GOOGLE_APPLICATION_CREDENTIALS /PoC/api-key.json
ENV PYCURL_SSL_LIBRARY=openssl
```

And this is my .gitlab-ci.yml:
```
stages:
  - build-docker
  - test-docker

build:
  stage: build-docker
  image: docker:latest
  tags:
    - docker
  script:
    - echo "Build base image"
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p $CI_JOB_TOKEN
    - docker build -t ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME} .
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
    # - docker run --rm -i ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME} python3 test_analyze_sb.py
    - docker rmi ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
  except:
    - tags

test:
  stage: test-docker
  image: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
  script:
    - python3 test_analyze_sb.py
```

See the commented line in the 'build' job? If I run that line, the job passes. The 'test' job, however, doesn't and fails with:
```
[...]/combined_into_gl_kws.py", line 12, in <module>
    from google.cloud import storage
ImportError: No module named 'google'
```

Any help is very much appreciated!!!
