### ISSUE TITLE
Storage: fetch specific object version

### ISSUE THREAD

**Issue by thakursc1** [GoogleCloudPlatform/google-cloud-python#5546] opened 2018-06-27 21:59 UTC
Is there a way to query a specific version of an object from cloud storage? 

```
def get_file_from_bucket(kind, id, ver:str)->dict:
    bucket = "bucket123"
    blob_path = "records" + "/" + kind + "/" + id+"#"+ver
    print("{}".format(blob_path))
    cred_file = Path(os.path.dirname((os.path.dirname(os.path.abspath(__file__)))),"service_file")
    storage_client = storage.Client.from_service_account_json(cred_file)
    bucket = storage_client.get_bucket(bucket)
    b = bucket.get_blob(blob_path)
    return b
```

`>> None `

The above function returns None, but when I remove the version I get the respective object. Is there a way to retrieve an object with specified version?

**Comment by tseaver** [comment] 2018-06-27 22:10
This is basically a duplicate of #4490.  We do not have support for fetching specific generations / metagenerations of blobs / objects, but have future plans to add that support.

/cc @frankyn

**Closed by tseaver** 2018-06-27 22:10 UTC
Labels: api: storage, type: feature request
