### ISSUE TITLE
support versioning options when fetching cloud storage buckets and objects

### ISSUE THREAD

**Issue by jcjones1515** [GoogleCloudPlatform/google-cloud-python#2538] opened 2016-10-12 20:44 UTC
The [bucket](https://cloud.google.com/storage/docs/json_api/v1/buckets/get) and [object](https://cloud.google.com/storage/docs/json_api/v1/objects/get) REST APIs allow for fetching or at least checking for specific generations/metagenerations of buckets and objects, but these are not supported by the python client.

**Comment by pdknsk** [comment] 2016-10-26 07:00
This is basically a more generic duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2463.

**Comment by tseaver** [comment] 2017-06-05 20:25
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2463#issuecomment-250479449 notes that the `generation` option should be used for the whole range of Object APIs which support it.  I have updated the title to indicate its broader scope.

**Closed by tseaver** 2017-06-05 20:25 UTC
Labels: api: storage, priority: p2+, type: enhancement
