### ISSUE TITLE
Fail `table.insert_data`

### ISSUE THREAD

**Issue by TechBK** [GoogleCloudPlatform/google-cloud-python#3695] opened 2017-07-28 09:19 UTC
1. OS version: ubuntu 17.04
2. Python version: Python 3.6.1
3. Lib version:

```
google-auth (1.0.1)
google-auth-httplib2 (0.0.2)
google-cloud-bigquery (0.25.0)
google-cloud-core (0.25.0)
googleapis-common-protos (1.5.2)
```

4. After i call `table.insert_data`, `result` object is : 
```
[{'index': 0, 'errors': [{'reason': 'invalid', 'location': '', 'debugInfo': 'generic::failed_precondition: Record leaf types are not supported.optional .Msg_0_CLOUD_QUERY_TABLE.Msg_1_CLOUD_QUERY_TABLE_user user = 2;\n', 'message': 'Record leaf types are not supported.optional .Msg_0_CLOUD_QUERY_TABLE.Msg_1_CLOUD_QUERY_TABLE_user user = 2;\n'}]}]
```

5. Code example:

* table's schema:

```python
schema = [bigquery.SchemaField('timestamp', 'TIMESTAMP', mode='REQUIRED'),
              bigquery.SchemaField('user', 'RECORD', fields=[
                  bigquery.SchemaField('id', 'INTEGER'),
                  bigquery.SchemaField('name', 'STRING'),
                  bigquery.SchemaField('mail', 'STRING'),
                  bigquery.SchemaField('phone', 'STRING'),
              ]),
              bigquery.SchemaField('action', 'STRING', mode='REQUIRED'),
              bigquery.SchemaField('project', 'STRING', mode='REQUIRED')]
```

* data test:

```python
data = (
            time.time(),
            12345,
            "user name",
            "mail",
            "phone",
            "action",
            "project"

        )

r = table.insert_data([tuple(data)])
```

**Comment by dhermes** [comment] 2017-07-28 16:19
@TechBK The issue is that "Record leaf types are not supported." (see the error message.)

@tswast I am not quite sure what that means?

**Comment by tswast** [comment] 2017-07-28 16:39
I think this is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2951.

I think we need some examples of inserting nested records in the docs, but for now you can look at the system test that was added for how to do it. https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3171/files

**Closed by tswast** 2017-07-28 16:39 UTC

**Comment by dhermes** [comment] 2017-07-28 17:00
Thanks a lot Tim!

**Comment by TechBK** [comment] 2017-07-29 06:02
But, i see document of `insert_data` function at [#L750](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/table.py#L750):
```
:param rows: Row data to be inserted. Each tuple should contain data
                     for each schema field on the current table and in the
                     same order as the schema fields.
```
I think this document is not clear
