### ISSUE TITLE
BigQuery: Failed to Parse JSON: Closing quote expected in string (non-ASCII characters)

### ISSUE THREAD

**Issue by WillFuks** [GoogleCloudPlatform/google-cloud-python#4753] opened 2018-01-14 10:23 UTC
Hello, 

I'd like to ask for some help on an issue I'm having.

Here's a sample code I created just to illustrate the problem:

```
import google.cloud.bigquery as bq
from google.cloud.bigquery import LoadJobConfig

con = bq.Client.from_service_account_json('/key.json')

from io import StringIO
data = "{'field1': '3 meses'}\n"
table = con.dataset('dataset_name').table('table_name')

conf = LoadJobConfig()
conf.write_disposition = 'WRITE_TRUNCATE'
conf.autodetect = True
conf.source_format = 'NEWLINE_DELIMITED_JSON'

r = con.load_table_from_file(StringIO(data), table, job_config=conf).result()
print(r.done())
print(r.errors)
```

If I run this code it works normally. But when a non-ASCII character is present in the string, such as:

    data = "{'field1': '3 mêses'}\n"

Then I get the error:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    r = con.load_table_from_file(StringIO(data), table, job_config=conf).result()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/job.py", line 528, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 111, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Failed to parse JSON: Closing quote expected in string; Could not parse value

```

I confirmed that `bq load` command works normally, it's just the Google Cloud API that I got this error. Am I missing something?

The only difference I could see from `bq load` command to the API is the mimetype is `application/octet-stream` in bq and `application/json` in API (I don't even know if this makes any difference, it's just the only difference I could find so far).

I'm using Python3.6 running from the latest public docker image with no virtualenvs. If you need anything else please let me know,

Thanks,

**Comment by chemelnucfin** [comment] 2018-01-15 01:57
@tseaver @tswast 
  I was not able to reproduce the behavior.  Any insights on if it's a docker related issue?
```
        from google.cloud.bigquery import LoadJobConfig

        dataset_id = _make_dataset_id('dataset_name')
        table = 'table_name'        
        con = Config.CLIENT
        dataset = self.temp_dataset(dataset_id)        
        table_arg = Table(dataset.table(table), schema=SCHEMA)
        table = retry_403(Config.CLIENT.create_table)(table_arg)
        self.to_delete.insert(0, table)
        
        from io import StringIO
#        data = "{'field1': '3 meses'}\n"
        data = "{'field1': '3 mêses'}\n"
        
        table = con.dataset(dataset_id).table('table_name')
        conf = LoadJobConfig()
        conf.write_disposition = 'WRITE_TRUNCATE'
        conf.autodetect = True
        conf.source_format = 'NEWLINE_DELIMITED_JSON'

        r = con.load_table_from_file(StringIO(data), table, job_config=conf).result()
```

**Comment by WillFuks** [comment] 2018-01-15 13:24
Hmm interesting. I also tried not using `conf.autodetect = True` and instead defining the schema but got the same error.

For now my workaround has been to first load the data to Storage and then upload it to BigQuery. 

If it's working for you then it should be something in my environment...just wondering, did you test with Python3? Maybe the difference between strings being unicodes or bytes could have caused something?

I forgot to mention but here is also the versions I'm using for the API:

```
google-api-core==0.1.4
google-auth==1.3.0
google-cloud-bigquery==0.29.0
google-cloud-core==0.28.0
google-cloud-storage==1.6.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3

```

Thanks!

**Comment by chemelnucfin** [comment] 2018-01-15 16:44
Yes it was python 3.6.

**Comment by tswast** [comment] 2018-01-16 21:38
What is the encoding of the JSON file you are uploading? BigQuery expects UTF-8. There is a known issue that BigQuery doesn't support the other unicode encodings such as UTF-16.

**Comment by tswast** [comment] 2018-01-16 21:39
Perhaps we need to make sure the client library indicates that it is using UTF-8 in the resumable media upload?

**Comment by WillFuks** [comment] 2018-01-16 23:10
Hi Tim,

For what I understood the API only accepts unicode strings that are not yet encoded. The encoding seems to happen in the http request (I'm guessing). 

I also tested with `conf.encoding = 'UTF-8'` and 'ISO-8859-1' but it didn't work.

I didn't test on other docker images but for what @chemelnucfin commented it seems this issue is only happening in the `python:latest` image, don't know if something in the environment setup is doing something to the request.

**Comment by tseaver** [comment] 2018-03-16 18:39
FWIW, UTF-8 is actually mandated for *all* JSON in [RFC 8259](https://tools.ietf.org/html/rfc8259#section-8.1).

**Comment by tswast** [comment] 2018-03-16 19:45
With Python 3 one needs to use BytesIO for uploads instead of StringIO and explicitly set the encoding to `utf-8` when you encode your JSON string to get bytes. The `pandas-gbq` library also encountered this issue and resolved it in https://github.com/pydata/pandas-gbq/pull/108

**Comment by tswast** [comment] 2018-03-16 19:46
I think we can close this as "intended behavior", since we expect bytes for file uploads.

**Closed by tswast** 2018-03-16 19:46 UTC
Labels: api: bigquery, priority: p2, type: bug

**Comment by WillianFuks** [comment] 2018-04-05 15:26
@tswast you're right! Just tested using `BytesIO` instead and it worked normally...My bad! I thought the conversion would happen in the http request.

Thanks for the help :)
