### ISSUE TITLE
batch.delete...

### ISSUE THREAD

**Issue by isaachq** [GoogleCloudPlatform/google-cloud-python#3774] opened 2017-08-09 15:46 UTC
Dont! Work batch.delete+

File "quickstart.py", line 37, in 
batch.delete('tb_articulo',keyset['bharney@example.com', 'nonesuch@example.com'])
NameError: name 'keyset' is not defined

What is this ???

And this
keyset = ['2017-08-01', '2017-08-01']
batch.delete('tb_articulo',keyset)

key_set=keyset.to_pb(),
AttributeError: 'list' object has no attribute 'to_pb'

??????

The code is from this site
https://googlecloudplatform.github.io/google-cloud-python/stable/spanner/batch-usage.html
in the section
Delete records using a Batch

Everything works except delete :(

**Comment by lukesneeringer** [comment] 2017-08-09 15:54
@tseaver What is `keyset` in that example? It does not seem to be defined in previous examples and it is not obvious to me what it should be.

**Comment by isaachq** [comment] 2017-08-09 15:57
so? How to implement batch.delete
@tseaver @lukesneeringer :?

**Comment by isaachq** [comment] 2017-08-09 21:57
:?

**Comment by tseaver** [comment] 2017-08-10 19:05
Duplicate of #3773.

**Closed by tseaver** 2017-08-10 19:05 UTC
Labels: api: spanner, docs, priority: p2+
