### ISSUE TITLE
FireStore GaxError: Request Entity Too Large

### ISSUE THREAD

**Issue by alexanderwhatley** [GoogleCloudPlatform/google-cloud-python#4120] opened 2017-10-05 00:04 UTC
Not clear if this is a bug or not, but the error message seemed pretty strange. The code below threw the following error messsage:

```
import json
from google.cloud import firestore

db = firestore.Client.from_service_account_json('serviceAccountCredentials.json')
data = json.load(open('/home/alexander/Downloads/cresicor-dev-export.json'))

companies = data['companies']

# update companies
for cid, company in companies.items():
    company_ref = db.collection('companies').document(cid)
    company_ref.set(company)
```

Error Message:

```
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 

_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, 413:Request Entity Too Large)>

During handling of the above exception, another exception occurred:

GaxError                                  Traceback (most recent call last)
<ipython-input-8-b018dddf4a82> in <module>()
     12 for cid, company in companies.items():
     13     company_ref = db.collection('companies').document(cid)
---> 14     company_ref.set(company)
     15 
     16 # update users

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/document.py in set(self, document_data, option)
    222         batch = self._client.batch()
    223         batch.set(self, document_data, option=option)
--> 224         write_results = batch.commit()
    225         return _first_write_result(write_results)
    226 

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/batch.py in commit(self)
    133             commit_response = self._client._firestore_api.commit(
    134                 self._client._database_string, self._write_pbs,
--> 135                 transaction=None, options=self._client._call_options)
    136 
    137         self._write_pbs = []

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/gapic/firestore_client.py in commit(self, database, writes, transaction, options)
    849         request = firestore_pb2.CommitRequest(
    850             database=database, writes=writes, transaction=transaction)
--> 851         return self._commit(request, options)
    852 
    853     def rollback(self, database, transaction, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(request, options)
    450                 func, this_settings.timeout, **this_settings.kwargs)
    451         api_call = _catch_errors(api_call, gax.config.API_ERRORS)
--> 452         return api_caller(api_call, this_settings, request)
    453 
    454     if settings.page_descriptor:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in base_caller(api_call, _, *args)
    436     def base_caller(api_call, _, *args):
    437         """Simply call api_call and ignore settings."""
--> 438         return api_call(*args)
    439 
    440     def inner(request, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    378         except tuple(to_catch) as exception:
    379             utils.raise_with_traceback(
--> 380                 gax.errors.create_error('RPC failed', cause=exception))
    381 
    382     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/future/utils/__init__.py in raise_with_traceback(exc, traceback)
    417         if traceback == Ellipsis:
    418             _, _, traceback = sys.exc_info()
--> 419         raise exc.with_traceback(traceback)
    420 
    421 else:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    374         """Wraps specified exceptions"""
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception
    378         except tuple(to_catch) as exception:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     66         """Updates args with the timeout."""
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 
     70     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    505         state, call, deadline = self._blocking(request, timeout, metadata,
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 
    509     def with_call(self, request, timeout=None, metadata=None, credentials=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    453             return state.response
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 
    457 

GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, 413:Request Entity Too Large)>)
```

**Comment by alexanderwhatley** [comment] 2017-10-05 02:36
I tried breaking the write operation down, and I got another weird error:

```
import json
from google.cloud import firestore

db = firestore.Client.from_service_account_json('serviceAccountCredentials.json')
data = json.load(open('/home/alexander/Downloads/cresicor-dev-export.json'))

companies = data['companies']

# update companies
for cid, company in companies.items():
    for fid, field in company.items():
        field_ref = db.collection('companies').document(cid + '/' + fid)
        field_ref.set(field)
```
Error:
```
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 

_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Document name "projects/cresicor-dev/databases/(default)/documents/companies/4Ksz1cDrEA/actual" lacks "/" at index 79.)>

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-22-3f0c888825ab> in <module>()
     23     for fid, field in company.items():
     24         field_ref = db.collection('companies').document(cid + '/' + fid)
---> 25         field_ref.set(field)

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/document.py in set(self, document_data, option)
    222         batch = self._client.batch()
    223         batch.set(self, document_data, option=option)
--> 224         write_results = batch.commit()
    225         return _first_write_result(write_results)
    226 

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/batch.py in commit(self)
    133             commit_response = self._client._firestore_api.commit(
    134                 self._client._database_string, self._write_pbs,
--> 135                 transaction=None, options=self._client._call_options)
    136 
    137         self._write_pbs = []

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/gapic/firestore_client.py in commit(self, database, writes, transaction, options)
    849         request = firestore_pb2.CommitRequest(
    850             database=database, writes=writes, transaction=transaction)
--> 851         return self._commit(request, options)
    852 
    853     def rollback(self, database, transaction, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(request, options)
    450                 func, this_settings.timeout, **this_settings.kwargs)
    451         api_call = _catch_errors(api_call, gax.config.API_ERRORS)
--> 452         return api_caller(api_call, this_settings, request)
    453 
    454     if settings.page_descriptor:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in base_caller(api_call, _, *args)
    436     def base_caller(api_call, _, *args):
    437         """Simply call api_call and ignore settings."""
--> 438         return api_call(*args)
    439 
    440     def inner(request, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    378         except tuple(to_catch) as exception:
    379             utils.raise_with_traceback(
--> 380                 gax.errors.create_error('RPC failed', cause=exception))
    381 
    382     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/future/utils/__init__.py in raise_with_traceback(exc, traceback)
    417         if traceback == Ellipsis:
    418             _, _, traceback = sys.exc_info()
--> 419         raise exc.with_traceback(traceback)
    420 
    421 else:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    374         """Wraps specified exceptions"""
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception
    378         except tuple(to_catch) as exception:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     66         """Updates args with the timeout."""
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 
     70     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    505         state, call, deadline = self._blocking(request, timeout, metadata,
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 
    509     def with_call(self, request, timeout=None, metadata=None, credentials=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    453             return state.response
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 
    457 

InvalidArgumentError: InvalidArgumentError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Document name "projects/cresicor-dev/databases/(default)/documents/companies/4Ksz1cDrEA/actual" lacks "/" at index 79.)>)
```

**Comment by dhermes** [comment] 2017-10-05 03:13
So for the first error, it seems you are clear on what the issue is, your entity was too large. I'm not sure what the limits are, maybe @samtstern can help there?

As for the second, the string which is the full document key has a length of 79, so the error essentially says it's an incomplete key.

The issue is essentially my fault (I'm the sole dev of the `firestore` package) for allowing a `/` in collection or document names.

So if you use a delimiter other than `/` in 

```python
field_ref = db.collection('companies').document(cid + '/' + fid)
```

when combining `cid` and `fid`, you will have no issues.

**Comment by alexanderwhatley** [comment] 2017-10-05 03:30
Hmm, I changed the line in question to 
` field_ref = db.collection('companies').document(cid + '.' + fid)`
and I got a different error message:

```
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 

_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Too many indexed properties)>

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-23-2b0be71d20d1> in <module>()
     23     for fid, field in company.items():
     24         field_ref = db.collection('companies').document(cid + '.' + fid)
---> 25         field_ref.set(field)

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/document.py in set(self, document_data, option)
    222         batch = self._client.batch()
    223         batch.set(self, document_data, option=option)
--> 224         write_results = batch.commit()
    225         return _first_write_result(write_results)
    226 

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/batch.py in commit(self)
    133             commit_response = self._client._firestore_api.commit(
    134                 self._client._database_string, self._write_pbs,
--> 135                 transaction=None, options=self._client._call_options)
    136 
    137         self._write_pbs = []

/home/alexander/anaconda3/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/gapic/firestore_client.py in commit(self, database, writes, transaction, options)
    849         request = firestore_pb2.CommitRequest(
    850             database=database, writes=writes, transaction=transaction)
--> 851         return self._commit(request, options)
    852 
    853     def rollback(self, database, transaction, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(request, options)
    450                 func, this_settings.timeout, **this_settings.kwargs)
    451         api_call = _catch_errors(api_call, gax.config.API_ERRORS)
--> 452         return api_caller(api_call, this_settings, request)
    453 
    454     if settings.page_descriptor:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in base_caller(api_call, _, *args)
    436     def base_caller(api_call, _, *args):
    437         """Simply call api_call and ignore settings."""
--> 438         return api_call(*args)
    439 
    440     def inner(request, options=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    378         except tuple(to_catch) as exception:
    379             utils.raise_with_traceback(
--> 380                 gax.errors.create_error('RPC failed', cause=exception))
    381 
    382     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/future/utils/__init__.py in raise_with_traceback(exc, traceback)
    417         if traceback == Ellipsis:
    418             _, _, traceback = sys.exc_info()
--> 419         raise exc.with_traceback(traceback)
    420 
    421 else:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/api_callable.py in inner(*args, **kwargs)
    374         """Wraps specified exceptions"""
    375         try:
--> 376             return a_func(*args, **kwargs)
    377         # pylint: disable=catching-non-exception
    378         except tuple(to_catch) as exception:

/home/alexander/anaconda3/lib/python3.5/site-packages/google/gax/retry.py in inner(*args)
     66         """Updates args with the timeout."""
     67         updated_args = args + (timeout,)
---> 68         return a_func(*updated_args, **kwargs)
     69 
     70     return inner

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials)
    505         state, call, deadline = self._blocking(request, timeout, metadata,
    506                                                credentials)
--> 507         return _end_unary_response_blocking(state, call, False, deadline)
    508 
    509     def with_call(self, request, timeout=None, metadata=None, credentials=None):

/home/alexander/anaconda3/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    453             return state.response
    454     else:
--> 455         raise _Rendezvous(state, None, None, deadline)
    456 
    457 

InvalidArgumentError: InvalidArgumentError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Too many indexed properties)>)
```

**Comment by dhermes** [comment] 2017-10-05 03:35
@alexanderwhatley You are really putting the API through it's paces :grinning: 

I'm surprised to see this, as the concepted of unindexed properties doesn't seem to be part of the Firestore [API definition][1].

I'd guess a more proper reading of that error message is "too many properties" rather than "Too many indexed properties". Though it's also very possible I have made a programming mistake.

Do you mind sharing how many properties you are trying to add when the failure occurs?

[1]: https://github.com/googleapis/googleapis/tree/3273178ea4684acc4f512f7bef7349dd72db88f6/google/firestore/v1beta1

**Comment by alexanderwhatley** [comment] 2017-10-05 03:44
@dhermes, would you mind if I email you the data and the code I used so you can try to replicate on your end? Would probably be easier that way.

**Comment by dhermes** [comment] 2017-10-05 03:46
That would be fine with me.

**Comment by alexanderwhatley** [comment] 2017-10-05 03:53
Emailed you.

**Comment by alexanderwhatley** [comment] 2017-10-08 18:43
@samtstern, @dhermes any updates on this?

**Comment by alexanderwhatley** [comment] 2017-10-10 23:30
Bump.

**Comment by alexanderwhatley** [comment] 2017-10-16 18:25
It's been a couple weeks now @dhermes. Any updates?

**Comment by dhermes** [comment] 2017-10-17 18:18
Sorry for the delay, I am a bit swamped.

**Comment by dhermes** [comment] 2017-10-17 18:59
@alexanderwhatley @samtstern After checking out the data, I have found the issue (I think).

Two of the entities (named `actual` and `expected`) had 20,510 keys, but there is a hard limit that is less than that number.

@samtstern Can the limit be published? Can we file a bug with the backend team to make the issue clearer in the error message? Either say "you tried to upload X MB and the limit is Y MB" or "you tried to upload Z properties and the limit is T properties"?

**Comment by boblepepeur** [comment] 2017-10-17 21:58
+1

**Comment by alexanderwhatley** [comment] 2017-10-18 20:27
@dhermes, would the solution for now to be to break the request up (say into chunks of size <=10000)?

**Comment by dhermes** [comment] 2017-10-18 20:33
@alexanderwhatley Yes. 20,000 properties is **a lot**. It seems you'd rather have a list with 20,000 entities than unique keys in a dictionary?

I can't really give recommendations on how to use the Firestore API though, I just wrote the client. (i.e. I don't have intimate knowledge of the backend). @samtstern May know better.

**Comment by alexanderwhatley** [comment] 2017-10-18 20:35
@dhermes, oh, perhaps there is a misunderstanding on my part then. I was trying to import this data from firebase, and store all of the entries in the same way, i.e. as dictionary entries under the main fields.

**Comment by dhermes** [comment] 2017-10-18 20:41
I'm a bit confused at this point. This issue presented in two ways:

- "413:Request Entity Too Large"
- "Too many indexed properties"

Both of these involve you **adding** data to Firebase, not importing/reading **from** Firebase. There is no issue with reading data that is already stored.

**Comment by alexanderwhatley** [comment] 2017-10-18 20:43
So what I did was what the Firestore documentation recommended: I downloaded my Firebase data as a JSON file (which is what I emailed to you.) I then tried to push all of the data in the exact same format to Firestore.

**Comment by dhermes** [comment] 2017-10-18 20:50
Gotcha. I have to tap out at this point: my Firebase knowledge is too limited.

@jonparrott @samtstern do you know of any resources I can point to? (There doesn't seem to be any Firebase link on https://cloud.google.com/support/docs/issue-trackers)

**Comment by tseaver** [comment] 2017-10-18 21:30
@dhermes Just for clarity: the source data is from *firebase*, being migrated into *firestore*.

@alexanderwhatley Maybe the [difference in the data models](https://firebase.google.com/docs/firestore/rtdb-vs-firestore#data_model) between Firebase RTD and Firestore is what is tripping you up?  I.e., you need to break up that one, massive JSON top-level mapping into individual documents (one per key?  I'm just guessing).

**Comment by alexanderwhatley** [comment] 2017-10-18 22:52
Hi @tseaver, I tried that, but it was incredibly slow (I have more than 20,000 keys for some of the fields after all), which is why I'm looking for a reasonable workaround here.

**Comment by samtstern** [comment] 2017-10-18 23:49
Apologies for my delay here.  Just to recap, there are the following limits on a document (all specified here):
https://cloud.google.com/firestore/quotas

  * Your document can only have 20,000 fields due to indexing limits. 
  * The total size of your document can only be 1MB.

For the fields limit nested fields count as well, so this doc has 5 properties:
```
{
  name: Sam, // 1
  age: 100,  // 2
  likes: {
     turtles: true, // 3
     ponies: false, // 4 
     football: true // 5
  }
}
```

When you get "too many indexed properties" your document has >= 20,001 fields.  When you get "request entity too large" you have exceeded the 1MB document total size limit.

Neither of these can be solved by "breaking up" your request into multiple calls, these are limits on documents themselves.

What does one `company` object look like?  I am trying to understand why it would have 20,000 properties.  If I see an example we can discuss alternate data structures.

**Comment by alexanderwhatley** [comment] 2017-10-19 00:09
@samtstern, would you mind if I email the same data file to you? It would probably be easier to directly view the data than for me to describe it here.

**Comment by samtstern** [comment] 2017-10-19 00:11
@alexanderwhatley sure, that will work.

**Comment by samtstern** [comment] 2017-10-19 16:25
@dhermes I believe we can close this issue as it's not a problem with the Python library but rather just a more general issue of proper data structuring in Cloud Firestore.  I can confirm that the example data for a "company" that Alexander sent over to me is both over 1MB and has more than 20,000 fields so the errors are expected.

I will see what I can do about getting clearer error messages and I am working with Alexander privately over email to choose a more efficient structure.

**Comment by dhermes** [comment] 2017-10-19 16:28
Great thanks!

**Closed** 2017-10-19 16:27 UTC
Labels: api: firestore
