### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\sanja\AppData\Local\Temp\pip-build-ppc44asr\googleapis-common-protos\

### ISSUE THREAD

**Issue by Sanjay-B** [GoogleCloudPlatform/google-cloud-python#3884] opened 2017-08-26 20:47 UTC
1. Windows 10
2. Python 3.6.2
3. N/A
4. Stacktrace
```
C:\Users\sanja\Desktop\Sapphire\api>pip install --upgrade gcloud
Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454kB)
    100% |████████████████████████████████| 460kB 1.0MB/s
Requirement already up-to-date: httplib2>=0.9.1 in c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages (from gcloud)
Collecting googleapis-common-protos (from gcloud)
  Using cached googleapis-common-protos-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\sanja\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\sanja\AppData\Local\Temp\pip-build-ppc44asr\googleapis-common-protos\
```

5. Refer to ``#6``
6. ``pip install gcloud`` or ``pip install --upgrade gcloud``

Looking for a solution, 
Thanks in advance.

**Comment by Sanjay-B** [comment] 2017-08-26 20:49
Side note: Also occurs when installing pyrebase through pip (``pip install pyrebase``).

**Comment by dhermes** [comment] 2017-08-26 20:55
@Sanjay-B You have an out of date version of `setuptools`, sorry for the inconvenience (and hard to understand error).

Simply `pip install --upgrade setuptools`

If it doesn't work, we can re-open and discuss. Pre-emptively closing since the issue seems clear.

**Closed by dhermes** 2017-08-26 20:55 UTC

**Comment by dhermes** [comment] 2017-10-03 18:54
For anyone who comes here, see #2990.

**Comment by dawong8** [comment] 2017-10-31 02:27
When I run 'pip install --upgrade setuptools', I get 



Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/var/folders/7n/w1bdv55j4tv4lqb71wk2xv0c0000gn/T/pip-gukfzS-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]



What happened? :(

**Comment by dhermes** [comment] 2017-10-31 02:35
You can't overwrite some packages owned by system Python on OS X (i.e. the `python` binary that lives in `/System/Library/Frameworks/Python.framework/Versions/2.7/...`, which you can see if you ask for `sys.executable` in the interpreter). Using system Python on OS X is not really a good idea, because it can't be updated. Instead, I recommend (in this order):

- using `pyenv` so you can manage your own Python install
- installing directly with `.pkg` files from python.org
- using `conda` / Anaconda / Miniconda
- using Homebrew Python

**Comment by ApsRajput** [comment] 2017-12-30 09:11
hello dawong8,
its permission problem, try 'sudo pip install --upgrade setuptools'

**Comment by Khotso-t** [comment] 2018-01-19 21:07
sudo apt-get install python3.6-dev libmysqlclient-dev

**Comment by fishruti** [comment] 2018-01-20 08:49
Hello guys, 

The problem is ONLY with Python 3.7 . When I moved back to Python 3.6 I was able to install !! :D :D

**Comment by tuneum** [comment] 2018-01-20 20:00
(I'm using/have only eve4r used 3.6, but am still unable to install)

**Comment by rahul6612** [comment] 2018-02-12 19:24
ma ka bhosara koi batayega dhang se sab kar liya phir v error aa rha

**Comment by srish** [comment] 2018-02-14 06:31
@rahul6612 Mind your language, please? Contributors and users of these libraries are not sitting idle and are not here just to support you! Just because people who speak and write different languages are here on this thread does not mean that you can use abusive and foul language and just get away with it? Please don't use such language next time. And, have patience in seeking a response on public forums.

**Comment by Sanjay-B** [comment] 2018-02-14 13:13
Keep this on topic. Meant as a solution for others having this problem. Be mindful.

**Comment by sparimi1** [comment] 2018-02-15 04:29
Hello Geeks, 

I am also receiving the same error: 
C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts>pip ins
tall robotframework-sudslibrary
Collecting robotframework-sudslibrary
  Using cached robotframework-sudslibrary-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-ygs6x3qj\robotframewo
rk-sudslibrary\setup.py", line 8, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-ygs6x3qj\robotframewo
rk-sudslibrary\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1
\AppData\Local\Temp\pip-build-ygs6x3qj\robotframework-sudslibrary\

setup-tools package has latest and up to date in system, any pointers?

**Comment by chemelnucfin** [comment] 2018-02-15 06:06
@sparimi1 
Hello, you are probably looking for this library [robotframework-sudslibrary](https://github.com/ombre42/robotframework-sudslibrary)

**Comment by Ayushverma8** [comment] 2018-03-01 12:02
Please specify for CentOS as well . :-(

**Comment by abuayub** [comment] 2018-03-20 21:42
sudo apt-get install libmysqlclient-dev

**Comment by srcolinas** [comment] 2018-04-04 16:41
Please solve this issue, I am using Ubuntu and the command:  `pip install google-cloud-dataflow`
produces the following error:
pip install google-cloud-dataflow==2.2.0
Collecting google-cloud-dataflow==2.2.0
  Using cached google-cloud-dataflow-2.2.0.tar.gz
Collecting apache-beam[gcp]==2.2.0 (from google-cloud-dataflow==2.2.0)
  Using cached apache-beam-2.2.0.zip
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        For performance reasons, doesn't actually impose an ordering
        on unequal values (always returning 1).
        """
        if type(left) is not type(right):
          return cmp(type(left), type(right))
                ^
    ------------------------------------------------------------

    apache_beam/utils/windowed_value.py:83:13: undeclared name not builtin: cmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lfsu689y/apache-beam/setup.py", line 173, in <module>
        'apache_beam/utils/windowed_value.py',
      File "/home/srcolinas/anaconda3/envs/gcp_test27/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
        cythonize_one(*args)
      File "/home/srcolinas/anaconda3/envs/gcp_test27/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: apache_beam/utils/windowed_value.py
    Compiling apache_beam/coders/stream.pyx because it changed.
    Compiling apache_beam/runners/worker/statesampler.pyx because it changed.
    Compiling apache_beam/coders/coder_impl.py because it changed.
    Compiling apache_beam/metrics/execution.py because it changed.
    Compiling apache_beam/runners/common.py because it changed.
    Compiling apache_beam/runners/worker/logger.py because it changed.
    Compiling apache_beam/runners/worker/opcounters.py because it changed.
    Compiling apache_beam/runners/worker/operations.py because it changed.
    Compiling apache_beam/transforms/cy_combiners.py because it changed.
    Compiling apache_beam/utils/counters.py because it changed.
    Compiling apache_beam/utils/windowed_value.py because it changed.
    [ 1/11] Cythonizing apache_beam/coders/coder_impl.py
    [ 2/11] Cythonizing apache_beam/coders/stream.pyx
    [ 3/11] Cythonizing apache_beam/metrics/execution.py
    [ 4/11] Cythonizing apache_beam/runners/common.py
    [ 5/11] Cythonizing apache_beam/runners/worker/logger.py
    [ 6/11] Cythonizing apache_beam/runners/worker/opcounters.py
    [ 7/11] Cythonizing apache_beam/runners/worker/operations.py
    [ 8/11] Cythonizing apache_beam/runners/worker/statesampler.pyx
    [ 9/11] Cythonizing apache_beam/transforms/cy_combiners.py
    [10/11] Cythonizing apache_beam/utils/counters.py
    [11/11] Cythonizing apache_beam/utils/windowed_value.py

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lfsu689y/apache-beam/

I have upgrated setuptools and tried on python 3.6 and python 2.7 using conda as the manager of virtual environments. Nothing works! when I try to do `pip install apache-beam` I get the same error.

**Comment by chemelnucfin** [comment] 2018-04-04 16:47
@srcolinas do you need dataflow 2.2.0?  I just tested and had no problems with installing the newest version, but I did encounter the same error on 2.2.0

**Comment by srcolinas** [comment] 2018-04-04 17:59
No, the latest version would be great. However, I got the following when I do `pip install google-cloud-dataflow`

Collecting google-cloud-dataflow
  Using cached google-cloud-dataflow-2.4.0.tar.gz
Collecting apache-beam[gcp]==2.4.0 (from google-cloud-dataflow)
  Could not find a version that satisfies the requirement apache-beam[gcp]==2.4.0 (from google-cloud-dataflow) (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0)
No matching distribution found for apache-beam[gcp]==2.4.0 (from google-cloud-dataflow)

Which is why I tried 2.2.0
(Thanks for your help)

**Comment by candscientecon** [comment] 2018-04-05 20:09
Hi guys!
I need  to run "pip install matplotlib" from a Windows command prompt to install matplotlib.
I need that because in python I should run the following:

import matplotlib.pyplot as plt
plt.plot([0, 0.25, 1], [0, 1, 0.5], "r-")
plt.plot([0.25, 0.5, 1.5, 1], [0.5, 1.0, 0.5, 0], "go")
plt.show()

But "pip install matplotlib" i cmd leads to an error code 1, i.e. there is no permission.
![error_code_1](https://user-images.githubusercontent.com/38114894/38389068-8714aace-391d-11e8-9ef3-01adc63faf6b.PNG)
![error_code_1 2](https://user-images.githubusercontent.com/38114894/38389085-96cda68c-391d-11e8-920c-565f621ad6ca.PNG)

I did follow previous recommendations for solving this but no luck.

I need help

Thanks in advance!

**Comment by Ashton08** [comment] 2018-05-02 15:55
Did you ever find a solution for this? I'm currently having the same problem. @candscientecon

**Comment by candscientecon** [comment] 2018-05-02 16:06
Hi guys
@Sanjay-B Im using Python 3.7 for win 64 bit and matplotlib supports every version, so i tried degrade my Python and vice versa but no luck.
@fishruti I tried that!
@Ashton08 no solutions. But it worked on Spyder through Anaconda, since Anaconda has the most packages installed.

**Comment by tseaver** [comment] 2018-05-02 16:34
@srcolinas In spite of the appearance given by its name, `google-cloud-dataflow` is not maintained in this repository.  Please use https://cloud.google.com/dataflow/support for issues relating to that API / wrapper library.

@candscientecon Your issue is with `matplotlib`, or else with `pip` / `setuptools`.  We can't really help you with it here.

**Comment by candscientecon** [comment] 2018-05-02 16:46
@tseaver I came up with the idea that I had installed Python wrongly e.g. Pipy or somthing wrong with my path from packages to python. 
Or Python is install at a place where windows cant make changes through cmd?

**Comment by tseaver** [comment] 2018-05-02 17:00
@candscientecon For help with `matplotlib`, please see https://matplotlib.org/#need-help.  For help with `setuptools`, please see https://github.com/pypa/setuptools

**Comment by nimeshneema** [comment] 2018-05-11 09:01
@rahul6612 Please be conscious of your language and show respect to the community. I have already reported abuse to GitHub for your user account.

**Comment by EvilPatick** [comment] 2018-05-25 11:42
[https://i.imgur.com/9gVCeH7.png](url)
