### ISSUE TITLE
BigQuery: document proper use of run_async_query/QueryJob/QueryResult

### ISSUE THREAD

**Issue by bits01** [GoogleCloudPlatform/google-cloud-python#4153] opened 2017-10-11 03:04 UTC
If I run an async query using `run_async_query()`, get a `QueryJob` from it and a `QueryResult` from that by calling `job.query_results()`, the `rows` attribute of QR is empty. It seems that when the `GET` request is sent a parameter `maxResults=0` is automatically added, in the client code, which explains why rows is empty.

But this is confusing and not how it behaves for sync queries. I think it should allow getting some rows in that first `GET` request.

Can you please document the proper use of async queries and QueryResult? Thank you.

**Comment by lukesneeringer** [comment] 2017-10-12 12:27
@tswast @jba Assigning you two since I am pretty sure this is likely already fixed in the BigQuery work you are doing, but please verify.

**Comment by tswast** [comment] 2017-10-12 17:37
We still need to update the docs, but yes, it's covered by the work we're doing.

The sample at https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/query.py has the current best practices for async queries.

The gist is to ignore QueryResult for the most part. We are doing some work to make this easier in a future version.

**Comment by bits01** [comment] 2017-10-12 17:45
How does one get a count of the rows returned by a query without using `QueryResult`? Not possible it seems from the `destination_table.fetch_data()` iterator, even though the REST API does return a `totalRows` property. Will this also be addressed in the future improvements?

**Comment by tswast** [comment] 2017-10-12 17:46
Thanks for the feedback. I'll double-check that this property is covered.

**Comment by tswast** [comment] 2017-10-24 16:50
I believe https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4153#issuecomment-336213296 is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4152. The problem is that the `total_rows` property is only updated after doing the first request to fetch the first page.

I plan to address this by prefetching the first page of results when doing the function call to list rows.

**Closed by tswast** 2017-10-24 16:50 UTC
Labels: api: bigquery
