### ISSUE TITLE
conflict between google-cloud-pubsub==0.28.2 google-cloud-logging==1.3.0

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#3906] opened 2017-08-31 17:14 UTC
ubuntu 16.04.2 LTS
Fresh virtualenv
python2

```
pip install google-cloud-pubsub==0.28.2 google-cloud-logging==1.3.0
```

success but then any python command is broken:

```
(ta_15) tristan@tristanxu ~/tmp $ python
Traceback (most recent call last):
  File "/home/tristan/env/ta_15/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/home/tristan/env/ta_15/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/home/tristan/env/ta_15/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/tristan/env/ta_15/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/tristan/env/ta_15/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'google.cloud.gapic'
(ta_15) tristan@tristanxu ~/tmp $ 
```
It works fine with python3
It works fine with previous versions (google-cloud-pubsub==0.27.0 google-cloud-logging==1.2.0)
It works fine if I install only either google-cloud-pubsub==0.28.2 or google-cloud-logging==1.3.0

I cannot reproduce it on another computer so that might be related to my conf but as said, I try with a clean virtualenv

**Comment by dhermes** [comment] 2017-08-31 18:07
@tcroiset Thanks for reporting, I'm checking it out right now.

**Comment by dhermes** [comment] 2017-08-31 18:08
@tcroiset I can't reproduce. I think the issue may be your `--user` install for Python 2.7 (since `site.py` is involved).

**Comment by tcroiset** [comment] 2017-09-01 09:15
It looks like it was related with something in my .cache
sorry for the noise

**Comment by tcroiset** [comment] 2017-09-01 10:39
Hi @dhermes I reopen this issue with an example you should reproduce:
https://github.com/tcroiset/python-docs-samples/tree/dep_issue/appengine/flexible/hello_world_django
```
docker build -t dep_issue -f Dockerfile .
```
works then
```
docker run --rm -it --net=host dep_issue
```
outputs
```
(s1) tristan@tristanxu ~/p/api_libraries/python-docs-samples/appengine/flexible/hello_world_django (master)*$ docker run --rm -it --net=host dep_issue
Error processing line 4 of /usr/local/lib/python2.7/dist-packages/gapic_google_cloud_logging_v2-0.91.3-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google.cloud.gapic'

Remainder of file ignored
Error processing line 4 of /usr/local/lib/python2.7/dist-packages/proto_google_cloud_logging_v2-0.91.3-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google.cloud.proto'

Remainder of file ignored
[2017-09-01 10:38:33 +0000] [6] [INFO] Starting gunicorn 19.7.1
```

**Comment by dhermes** [comment] 2017-09-05 15:53
@tcroiset Thanks for finding a way to reproduce it!

Our resident packaging expert @jonparrott is also in charge of `python-docs-samples`, so it may just be easier to file this issue there?

**Comment by lukesneeringer** [comment] 2017-09-05 21:27
Hi @tcroiset,
I think we got to the bottom of this one. We were not properly declaring `google.cloud.gapic` and `google.cloud.proto` as namespace packages in `setup.py`. See #3921. The end result would be exactly what you described.

We are publishing an updated package now. I am going to close this as I am 95% sure it will address your issue, but feel free to re-open if I am wrong.

**Closed by lukesneeringer** 2017-09-05 21:27 UTC
Labels: type: question
