### ISSUE TITLE
Datastore: querying in imported file at module scope fails with 401 Deadline Exceeded error

### ISSUE THREAD

**Issue by expz** [GoogleCloudPlatform/google-cloud-python#4534] opened 2017-12-06 20:30 UTC
This error happens when executing a datastore query at module scope **triggered by importing the module into another script.** To reproduce make two files in the same directory together with a JSON service account credentials file. Notice where the datastore specific variables need to be set for the example to work.

`test.py`:

```python
from main import main

if __name__ == '__main__':
    main()
```

`main.py`:
```python
import os

from google.cloud import datastore

CREDENTIALS = 'YOUR-JSON-FILENAME-HERE'
PROJECT = 'YOUR-PROJECT-NAME-HERE'
NAMESPACE = 'YOUR-NAMESPACE-HERE'
KIND = 'YOUR-KIND-HERE'

PROJECT_DIR = os.path.dirname(os.path.realpath(__file__))
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = \
    os.path.join(PROJECT_DIR, CREDENTIALS)
ds_client = datastore.Client(project=PROJECT, namespace=NAMESPACE)

keys = []
query = ds_client.query(kind=KIND)
for entity in query.fetch():
    keys.append(entity.key.name)


def main():
    print('\n'.join(keys))
```

This will *always* fail with the following stacktrace:

```
File "test.py", line 1, in <module>
    from main import main
  File "/home/user/src/consult/test/main.py", line 11, in <module>
    for entity in query.fetch():
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 186, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 217, in _page_iter
    page = self._next_page()
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/datastore/query.py", line 498, in _next_page
    query=query_pb,
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 134, in run_query
    return super(GAPICDatastoreAPI, self).run_query(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 82, in _catch_remap_gax_error
    six.reraise(error_class, new_exc, sys.exc_info()[2])
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 74, in _catch_remap_gax_error
    yield
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 134, in run_query
    return super(GAPICDatastoreAPI, self).run_query(*args, **kwargs)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 258, in run_query
    return self._run_query(request, options)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/home/user/src/consult/test/venv/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.api_core.exceptions.Unauthorized: 401 Deadline Exceeded
```

The error goes away if:
1. the query is moved inside of the `main()` function or
2. the code in `test.py` is merged into the bottom of `main.py`

Now, perhaps it is sloppy to run a query at module scope, but I think this should at least be documented here. In my case, the query was buried deep in functions, but the initial call was made at module scope.

**OS type and version**

Ubuntu 17.04

**Python version and virtual environment information `python --version`**

Python 2.7.13

**google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`**

google-cloud-datastore == 1.4.0

**Comment by dhermes** [comment] 2017-12-06 20:36
I'm trying to reproduce right now.

**Comment by tseaver** [comment] 2017-12-06 20:47
@dhermes Is it worth the effort?  The notion of doing a `google.cloud` API call at import time is borderline insane, and the "workarounds" just remove the insanity.

**Comment by dhermes** [comment] 2017-12-06 20:52
@expz I just tried this with a kind that had no entities and it did not time out, it just exited after printing nothing.

If I add 3 entities for that kind, then it did the following:

```python
$ .../bin/python test.py
k123
k456
k789
```

The `DEADLINE EXCEEDED` is happening because the query is failing. It may be failing because:

- There are too many results for the kind (this shouldn't happen though)
- There is no connection to the web
- The error is actually bad credentials (since a 401), but a "Deadline exceeded"

I'd recommend you debug the query independent of the import, and then go back to re-factoring the import-time side effect.

I am going to close this out since there is no actual issue with the library (as far as I can tell). I'm happy to continue discussing and potentially re-open if need be. Thanks for taking the time to file the issue either way @expz!

**Comment by expz** [comment] 2017-12-06 21:21
Thanks for trying out such an unusual issue. Your answer makes complete sense, but it does not match my experience on my machine. If I were you, I would have trouble believing it. I have trouble believing it, but I have reproduced it many times now in multiple virtual environments, and the success/failure is perfectly correlated with moving the query (unchanged) out of module scope. Even if I have not botched my analysis, I do not think there is a need to re-open, since I agree with @tseaver. It is enough to have it google-able.

**Comment by dhermes** [comment] 2017-12-06 21:31
@expz Can you run in Python 3.6 so we get a higher quality traceback (i.e. it will print the original exceptions that were caught and raised as different names)?

**Comment by dhermes** [comment] 2017-12-06 21:36
OK, I **was** able to reproduce in Python 2.7!

**Comment by expz** [comment] 2017-12-06 21:36
I just tried Python 3.5.3, and the error does not happen.

**Comment by tseaver** [comment] 2018-02-27 18:51
@dhermes feel free to reopen if you still have a notion of what needs to be fixed in `google-cloud-datastore`.

**Closed by tseaver** 2018-02-27 18:51 UTC
Labels: api: datastore, priority: p2, status: investigating, type: bug

**Comment by Armyke** [comment] 2019-02-12 10:30
@tseaver 

> The notion of doing a `google.cloud` API call at import time is borderline insane

I couldn't find any trace of this inside google documentation, but maybe I didn't search well enough. Or is it something you worked out from your experience? If it's not the case can you please provide a link relating to your statement? Thanks in advance :D

**Comment by tseaver** [comment] 2019-02-12 18:13
@Armyke Import-time side effects are widely considered bad practice in Python, e.g.:

- https://chrismorgan.info/blog/say-no-to-import-side-effects-in-python.html
- http://pydev.blogspot.com/2016/11/python-import-world-anti-pattern.html
