### ISSUE TITLE
AbortionError(code=StatusCode.UNAUTHENTICATED, details="Request had invalid authentication credentials.")

### ISSUE THREAD

**Issue by forsberg** [GoogleCloudPlatform/google-cloud-python#2684] opened 2016-11-04 11:36 UTC
Very seldom, like 9 out of 450k publish requests, we get the following error:

```
AbortionError(code=StatusCode.UNAUTHENTICATED, details="Request had invalid authentication credentials.")
```

Retrying 2 times doesn't help, and we loose the message. 

What's the recommended way of dealing with this problem? Retry until it works? Should application code have to deal with it, or is it something that should be handled automatically by SDK? 

Versions, traceback etc is the same as in #2683.

**Comment by dhermes** [comment] 2016-11-04 18:07
@forsberg `AbortionError` indicates you are using an old version of this library. That was a beta feature of `grpc` and we have been using the stable version for some time.

Can you explain how you are installing?

**Comment by dhermes** [comment] 2016-11-04 18:09
@forsberg FWIW we've seen something similar in #1917. The issue is essentially one of timing: your token may not be expired when we check the expiry before making a request, but by the time it reaches the server, it is expired. Do you know what kind of credentials you are using? (e.g. service account or a user credentials)

**Comment by forsberg** [comment] 2016-11-04 19:10
We have a very simple retry logic here - it will simply try 3 times in a row. For the problem in #2683, this seems to have done the trick. For this, it doesn't. I guess it's matter of timing. 

I'll make sure we do a fresh install from master without old crap lying around on Monday to see if problem still appears. 

Agree that having built-in retry functionality would be very convenient. Or at least have documented what kind of exceptions are worth retrying.

**Comment by forsberg** [comment] 2016-11-07 08:24
And to answer your question: It's a service account.

**Comment by forsberg** [comment] 2016-11-17 15:07
After fixing our borked install to use a relatively fresh master [e1fbb6bc](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/e1fbb6bc28b02a2c36d190133dd0924ff585a97al), we have not observed this particular error anymore, but we have not had it running for a very long time. I'll report back again when we've had it running for a week or so without problems.

**Comment by dhermes** [comment] 2016-11-17 19:26
@forsberg Thanks for the update. This error is in some sense unavoidable because we [check][2] "is the [token valid][3]" (and [here][1]) before sending, but by the time it's sent it may have become invalid. (However, I'm fairly certain the server gives 5 minutes of wiggle room, which [isn't part of the expiry][4] so it seems "impossible".)

[1]: https://github.com/google/oauth2client/blob/92e4ad332992b91d4674335f3d83a7181e38967d/oauth2client/client.py#L642-L647
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b92f0cf5af596dd41951a8505a7eea037fd1a48a/core/google/cloud/_helpers.py#L621
[3]: https://github.com/google/oauth2client/blob/92e4ad332992b91d4674335f3d83a7181e38967d/oauth2client/service_account.py#L613
[4]: https://github.com/google/oauth2client/blob/92e4ad332992b91d4674335f3d83a7181e38967d/oauth2client/service_account.py#L672-L673

**Comment by lukesneeringer** [comment] 2017-08-08 06:11
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!

**Closed by lukesneeringer** 2017-08-08 06:11 UTC
Labels: api: pubsub, priority: p2+
