### ISSUE TITLE
Missing protobuf descriptor: google.appengine.logging.v1.RequestLog

### ISSUE THREAD

**Issue by Fkawala** [GoogleCloudPlatform/google-cloud-python#2572] opened 2016-10-19 16:37 UTC
Hello, 

To send a protobuf RequestLog entry through the stackdriver logging facility fails with the error stack below. 

``` python
Traceback (most recent call last):
  File "do_log.py", line 28, in <module>
    logger.log_proto(Struct(fields=pb_fields), labels=labels)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 260, in log_proto
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_gax.py", line 110, in write_entries
    entry_pbs = [_log_entry_mapping_to_pb(entry) for entry in entries]
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_gax.py", line 612, in _log_entry_mapping_to_pb
    Parse(json.dumps(mapping['protoPayload']), entry_pb.proto_payload)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/json_format.py", line 413, in ConvertMessage
    methodcaller(_WKTJSONMETHODS[full_name][1], value, message)(self)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/json_format.py", line 518, in _ConvertAnyMessage
    sub_message = _CreateMessageFromTypeUrl(type_url)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/json_format.py", line 341, in _CreateMessageFromTypeUrl
    'Can not find message descriptor by type_url: {0}.'.format(type_url))
TypeError: Can not find message descriptor by type_url: type.googleapis.com/google.appengine.logging.v1.RequestLog.
```

The protobuf is created / sent as follows:

``` python
from google.cloud import logging
from google.protobuf.struct_pb2 import Struct, Value, ListValue
client = logging.Client()
logger = client.logger('test')

line = Struct(fields={'time': Value(string_value='2016-09-04T13:00:08.139759Z'), 
                      'severity': Value(string_value='INFO'),
                      'logMessage': Value(string_value='Simply testing')})
lines = ListValue()
lines.values.add(struct_value=line)

pb_fields = {'@type': Value(string_value='type.googleapis.com/google.appengine.logging.v1.RequestLog'),
             'startTime':Value(string_value='2016-09-04T13:00:08.117102Z'),
             'endTime':Value(string_value='2016-09-04T13:00:08.117102Z'),
             'latency':Value(string_value='0s'),
             'responseSize':Value(string_value='349'),
             'userAgent': Value(string_value='agent'),
             'resource': Value(string_value='test resource'),
             'line': Value(list_value=lines)}

labels =  {'serviceName': 'custom.googleapis.com',
           'custom.googleapis.com/primary_key': 'fake_module',
           'custom.googleapis.com/secondary_key': 'fake_version',
           'zone': 'us6'}

logger.log_proto(Struct(fields=pb_fields), labels=labels)
```

This [gist](https://gist.github.com/Fkawala/654093301c47241386b5cd4e02791e56) provides a docker test environment. 

Is this a bug or am I missing something ? 
François.

**Comment by dhermes** [comment] 2016-10-19 17:08
@bjwatson Is there some kind of automated conversion for `Any` messages (i.e. with a type url)?

**Comment by bjwatson** [comment] 2016-10-19 22:31
@dhermes Looks like there is, but it doesn't recognize `type.googleapis.com/google.appengine.logging.v1.RequestLog`. The relevant code seems to be [here](https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L338) and [here](https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/python/google/protobuf/descriptor_pool.py#L251).

**Comment by dhermes** [comment] 2016-10-20 03:13
@bjwatson Do you know how types get registered with `symbol_database.Default()`? Do any of the GAPIC / gRPC generated libraries register types?

/cc @waprin @jonparrott

**Comment by bjwatson** [comment] 2016-10-20 18:21
Hi @pherl. I was referred to you by @giegerj. Do you have any thoughts on this issue involving `protobuf/json_format.py`?

**Comment by dhermes** [comment] 2016-10-20 18:26
@Fkawala Sorry I missed this and focused on the wrong thing. Why are you manually specifying the contents of the protobuf? The implementation expects usage of "registered" types, and the failure is due to the fact that the type URL you used is not in the registry in `google.protobuf`.

**Comment by Fkawala** [comment] 2016-10-20 19:27
@dhermes I got the idea here. How could I list the URL in the registry? This PB type is rendered in a particularly convenient way in the Google cloud log browser. F.

**Comment by dhermes** [comment] 2016-10-20 20:08
@Fkawala It's probably not something you want to do. Seems [`AddDescriptor`][1] is what you want, but that requires an actual protobuf type, and those are not usually written by hand ([e.g.][2]).

Why do you want to add logs that you copy-pasted from a browser?

[1]: https://github.com/google/protobuf/blob/9c6940f3bb4d7893b4d453870acd374c1ae43a58/python/google/protobuf/descriptor_pool.py#L142
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/881a95330dfb0dbab71e9c405acd2a8423ff1fee/bigtable/google/cloud/bigtable/_generated/bigtable_pb2.py

**Comment by dhermes** [comment] 2016-10-20 20:10
@bjwatson What do you think is the right answer here? The message is essentially an `Any` type if it doesn't have a registered type URL but `parser.ConvertMessage(js_dict, message)` doesn't really have a way to convert to a native `Any`.

**Comment by Fkawala** [comment] 2016-10-25 16:08
@dhermes A side note, the code I provided works with gcloud-python 0.18.3. I wonder I could find the actual descriptor for this PB type, any hints ?

**Comment by dhermes** [comment] 2016-10-25 16:10
Whoa, that's surprising. Let me check it out!

**Comment by dhermes** [comment] 2016-10-25 16:35
I [confirmed][1] this. Differences in deps are:

```
                        | 0.18.3   | 0.20.0
------------------------+----------+-------
                 grpcio | 1.0.1rc1 | 1.0.0
             google-gax | 0.12.5   | 0.14.1
gapic-google-logging-v2 | (NA)     | 0.10.1
gax-google-logging-v2   | 0.8.3    | (NA)
grpc-google-logging-v2  | 0.8.1    | 0.10.1
```

Both use: `protobuf==3.1.0.post1`, `googleapis-common-protos==1.3.5`,

[1]: https://gist.github.com/dhermes/3338cec56ebb6f6cd574de6fbfe8bdaf

**Comment by dhermes** [comment] 2016-10-25 16:37
@bjwatson This is really crazy, do you think somehow the `gapic` / `gax` deps are registering extra types?

**Comment by bjwatson** [comment] 2016-10-26 18:28
@dhermes Like you said earlier, it looks like only the gRPC-generated code (`grpc-google-*` packages and `googleapis-common-protos`) register any extra types. I don't see the GAPIC or GAX code doing this.

@Fkawala Looks like we need to add [`google.appengine.logging.v1.RequestLog`](https://cloud.google.com/logging/docs/api/reference/rest/Shared.Types/RequestLog) (and [`google.appengine.logging.v1.LogLine`](https://cloud.google.com/logging/docs/api/reference/rest/Shared.Types/LogLine)) to `googleapis-common-protos`. I'll look into this.

I don't know why this worked for you in an earlier version of `gcloud-python`; it seems like it shouldn't have.

**Comment by bjwatson** [comment] 2016-10-31 16:16
@Fkawala This is almost fixed. Once https://github.com/googleapis/api-client-staging/pull/89 is approved by @geigerj, I will publish a new version of https://pypi.python.org/pypi/googleapis-common-protos containing the RequestLog class definition.

**Comment by bjwatson** [comment] 2016-11-01 00:26
@Fkawala This should now be fixed by the `1.4.0` release of https://pypi.python.org/pypi/googleapis-common-protos. Please re-open this issue if the problem still exists for you.

**Comment by bjwatson** [comment] 2016-11-01 18:25
@dhermes Please see the discussion in https://github.com/googleapis/packman/pull/147. I am wondering why [`Logger.log_proto(...)`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a0e492b4098fe3c2df4d1821a432cbaee15edd6/logging/google/cloud/logging/logger.py#L228) is [converting the message to JSON](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a0e492b4098fe3c2df4d1821a432cbaee15edd6/logging/google/cloud/logging/logger.py#L138), just to [parse it back into a message](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a0e492b4098fe3c2df4d1821a432cbaee15edd6/logging/google/cloud/logging/_gax.py#L611) again?

**Comment by dhermes** [comment] 2016-11-01 18:31
@bjwatson The two lines you linked don't **always** follow one another. The [conversion to JSON][1] is nominally for sending an HTTP request, but may be repurposed in the gRPC code as well. It may end up [parsed back to protobuf][2] in the gRPC case because @tseaver was trying to minimize the parsing code, so at times was converting PBs as JSON resources to avoid repeating code.

Also

> I'm not yet convinced this needs to be in a common protos

I and @jonparrott have said it doesn't belong there. A true "fix" could be for `MessageToDict` to just punt when it can't find the type and just cast it to an `Any`?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c56e6e7a69441c84426866019bc114a4010ee9f8/logging/google/cloud/logging/logger.py#L138
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c56e6e7a69441c84426866019bc114a4010ee9f8/logging/google/cloud/logging/_gax.py#L438

**Comment by bjwatson** [comment] 2016-11-01 18:55
@dhermes Thanks. I better understand the design of `log_proto` now.

I'm surprised by your objection to putting `RequestLog` in `googleapis-common-protos`. I posted my plan to do that [six days ago](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2572#issuecomment-256436316), and I never saw an objection from you or @jonparrott. I just double-checked my email to make sure I'm not missing anything.

I published `googleapis-common-protos 1.4.0` with the `google/appengine/logging` message types yesterday.

**Comment by dhermes** [comment] 2016-11-01 19:05
@bjwatson It's not a problem that it's in there, it just isn't a "common" proto, that's all.

**Comment by bjwatson** [comment] 2016-11-01 20:05
@dhermes and I discussed offline. I see his point that these messages could be in their own separate package, like `grpc-google-appengine-logging-v1`. We're currently committed to them being in `googleapis-common-protos`, but can fix this later with a 2.0 release. (see https://github.com/googleapis/api-client-staging/issues/90)

**Comment by Fkawala** [comment] 2016-11-02 09:06
@bjwatson thanks !

**Comment by jonparrott** [comment] 2016-11-02 18:20
@bjwatson @dhermes this is just caused all sorts of problems. oauth2client now thinks that all environments are app engine because now `google.appengine` exists. Also, it seems `google.appengine` isn't a proper namespace package.

**Comment by jonparrott** [comment] 2016-11-02 18:27
https://github.com/googleapis/packman/pull/147#issuecomment-257956109

**Comment by bjwatson** [comment] 2016-11-02 18:58
Per the issue flagged by @jonparrott, I have removed GAE Logging from `googleapis-common-protos`. I will publish it in its own package soon.

**Comment by bjwatson** [comment] 2016-12-12 20:49
@nkubala just wanted to let you know that @geigerj will fix this issue this week.

**Comment by jaitaiwan** [comment] 2017-03-20 00:23
Just been hit by this myself for the past few days when trying to use the cloud logging api

**Comment by geigerj** [comment] 2017-03-20 16:59
@lukesneeringer @bjwatson I can update googleapis/googleapis#226 and googleapis/api-client-staging#144 and have a new `logging-extra-types` package pretty quickly. Does that sound reasonable?

**Comment by lukesneeringer** [comment] 2017-03-20 17:47
Just discussed with @geigerj offline, and based on https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2572#issuecomment-257954412, I am pretty sure we should _not_ do that. It would just move the problem, because as soon as you installed that package, oauth2client would think you were on GAE.

**Comment by bjwatson** [comment] 2017-03-20 18:56
@lukesneeringer @geigerj This seems like a P1 issue given the user impact. I assigned to Luke; feel free to re-assign to Jacob if you prefer.

**Comment by geigerj** [comment] 2017-03-20 19:00
@jonparrott Do you have thoughts on the right way to handle this?

**Comment by jonparrott** [comment] 2017-03-20 19:40
@bjwatson good news and bad news:

1. We no longer depend on oauth2client. The new library does a narrow check and wouldn't be triggered by the presence of that package.
2. If we installed that package, we'll break any app engine users. This library already has tenuous support for App Engine, so let's try not to do anything more to rock the boat.

If the extra types library can have an import path that doesn't start with `google.appengine` then we're in the clear. But, as far as I can tell `google.appengine` should *only* be used by the GAE SDK.

**Comment by dhermes** [comment] 2017-03-20 20:52
The fix is to loosen the way we parse `Any` protobufs here. (We had discussed this before and I let it fall through the cracks, my bad.) No need for any new generated libraries

**Comment by dhermes** [comment] 2017-03-31 20:07
Duplicate of #2674

**Comment by mikelambert** [comment] 2017-04-21 01:14
Thanks for investigating and pushing for this @Fkawala, I see dhermes has added support for `Any` protobufs now.

But François I was curious how you accumulate your application logs? If you've already built that, I'd love to take a peek (if possible!), to save me the trouble of digging into the complexity of python loggers, handlers, exclusions, etc. Thanks!

**Comment by dhermes** [comment] 2017-04-21 02:27
@mikelambert Have you seen the "getting started" doc for logging? https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html

**Closed by dhermes** 2017-04-21 02:27 UTC
Labels: api: logging, grpc, priority: p1, status: acknowledged, type: enhancement

**Comment by mikelambert** [comment] 2017-04-21 03:17
Yup, it's quite helpful, but didn't quite answer the above for me. My confusion was more about python's logging system.

If I dig into `google/cloud/logging/handlers/handlers.py` for inspiration, and make a best-guess about how python's `logging` works (and ignore stuff like `propagate` and `sub-loggers`), then my test code would be something like this:
```
import logging
class AggregatingLogger(logging.StreamHandler):
  def __init__(self):
    super(AggregatingLogger, self).__init__()
    self.logs = []
  def emit(self, record):
    self.logs.append(record)

def aggregated_logging_middleware(app):
    def wsgi_app(environ, start_response):
      logger = logging.getLogger()
      handler = AccumulatingLogger()
      logger.addHandler(handler)
      try:
        return app(environ, start_response)
      finally:
        cloud_logger = client.logger('aggregated_logs')
        cloud_logger.log_proto(build_request_proto(handler.logs))
        logger.removeHandler(handler)
```

I was just hoping to save the time of writing and testing this, if Francois had already done it, since it looks like he's trying to do the same thing I am. I'm already spending enough time reimplementing GAE Standard features, so I can migrate off the now-deprecated Managed VMs onto Flexible VMs, trying to leverage work where I can. :)

**Comment by dhermes** [comment] 2017-04-21 03:37
Ah I see, maybe @waprin can give some pointers there.

**Comment by Fkawala** [comment] 2017-08-29 07:53
Hi @mikelambert, for some reason I missed the notifications from this thread. Sorry. I doubt that you still need help on this topic, but just in case here is some information.

My current solution (which I wrote when the PB issue wasn't solved) does not rely on the `log_proto` method, but instead uses `log_struct`. The `logName` field is set to : `projects/<project-name>/logs/<module-name>` so that the log viewer puts my logs in a nicely usable way (section: Global, subsection <module-name>).

More precisely, I use `logging.StreamHandler`, `logging.handlers.QueueListener` (in case of multiprocessing) and `google.cloud.logging.Batch`. If you don't use multiprocessing the solution boils down to a subclass of `logging.StreamHandler` that processes log records to extract input parameters for the `log_struct` method. This `logging.StreamHandler` also do periodic commit of the `google.cloud.logging.Batch` that actually sends logs.

If you need it I might be able to share the source, but I'll I have to check with my company first, let me know.

**Comment by eyalev** [comment] 2017-08-29 08:04
One of my motivations for working with `log_proto` is to be able to get multiple `line` elements per log entry, similar to that in `GAE Standard`.

@Fkawala by looking at your example I guess this was also your motivation. Have you succeeded with multiple `line` elements that are collapsible in the Cloud Console Logging UI (with `log_struct`)? 

In any case I would love if could share your working source code. Thanks.

**Comment by Fkawala** [comment] 2017-08-29 08:19
@eyalev I was digging into PB logging for the exact same reason :) From what I understood back then PB logging was the only way to achieve that. Note that the google cloud support team kindly suggested me not to spent to much time on that because it is hackish and the log viewer might change without notice.

Also, when I opened the issue I was quite short on time so I moved to `struct_log` and prefixed my logs with  [host_uuid:process_uuid:task_uuid] that is a lame (but working) solution. It allows me to extract a sequence of related log lines quite effectively.

**Comment by eyalev** [comment] 2017-08-29 08:30
Even if this solution will work for a few months I'm ok with it. If/when it will break I will update to a new solution or fallback to the current setup.

From my experience with GCP timelines I'm guessing I have at least a year :)

BTW, currently when using `log_proto` I get en error, but if I set the env var `GOOGLE_CLOUD_DISABLE_GRPC` to `true` it works. I have no idea why :)

**Comment by snarfed** [comment] 2019-11-07 18:15
hi! i've hit this recently too, with google-cloud-logging 1.14.0 and googleapis-common-protos 1.6.0:

```
>>> from google.cloud.logging import Client
>>> c = Client()
>>> entries = c.list_entries(('brid-gy',), filter_='resource.type="gae_app" AND protoPayload.@type="type.googleapis.com/google.appengine.logging.v1.RequestLog"', order_by='timestamp desc')
>>> next(iter(entries)).to_api_repr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../google/cloud/logging/entries.py", line 357, in to_api_repr
    info["protoPayload"] = MessageToDict(self.payload)
  File ".../google/protobuf/json_format.py", line 168, in MessageToDict
    return printer._MessageToJsonObject(message)
  File ".../google/protobuf/json_format.py", line 202, in _MessageToJsonObject
    return methodcaller(_WKTJSONMETHODS[full_name][0], message)(self)
  File ".../google/protobuf/json_format.py", line 314, in _AnyMessageToJsonObject
    sub_message = _CreateMessageFromTypeUrl(type_url, self.descriptor_pool)
  File ".../google/protobuf/json_format.py", line 389, in _CreateMessageFromTypeUrl
    'Can not find message descriptor by type_url: {0}.'.format(type_url))
TypeError: Can not find message descriptor by type_url: type.googleapis.com/google.appengine.logging.v1.RequestLog.
```

we've been discussing this on the [google-appengine group](https://groups.google.com/d/topic/google-appengine/xTDZ-da27ow/discussion) [and StackOverflow](https://stackoverflow.com/questions/58753378/how-to-deserialize-app-engine-application-logs-from-stackdriver-logging-api). i've tried to follow the discussions here and in #2674, but i can't tell what the conclusion is. anyone know how i can fix this?

**Comment by snarfed** [comment] 2019-12-19 17:57
i ended up generating my own `request_log_pb2.py` file based on `request_log.proto`, and it parses `google.appengine.logging.v1.RequestLog` serialized protobufs great! details in https://stackoverflow.com/a/59414384/186123.

obviously not ideal, i'd rather use an official version of that file maintained by Google instead, but this is an ok workaround in the meantime for now.
