### ISSUE TITLE
Remove pubsub and logging as namespace packages

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2258] opened 2016-09-07 17:24 UTC
This should be assigned to @bjwatson but I can't assign to him in this repo.

Blocking on having the GAX generated Pub / Sub and Logging clients no longer use `google.cloud.logging` and `google.cloud.pubsub` as namespace packages.

**Comment by bjwatson** [comment] 2016-09-07 18:00
If the admin for GoogleCloudPlatform adds me, then you can assign away. :) (FYI, @omaray and @jgeewax)

I'm just resolving the email thread that you're copied on for correct package naming. After that, it's pretty easy to re-generate these surfaces, since they've already been thoroughly tested (a simple diff will tell me they still look good).

**Comment by jonparrott** [comment] 2016-09-07 18:04
I can add you to this repo, @elibixby can add you to the veneer team.

**Comment by jonparrott** [comment] 2016-09-07 18:04
Invitation sent.

**Comment by bjwatson** [comment] 2016-09-07 18:31
Thanks @jonparrott

**Comment by dhermes** [comment] 2016-09-07 22:31
> I'm just resolving the email thread that you're copied on for correct package naming. After that, it's pretty easy to re-generate these surfaces, since they've already been thoroughly tested

Yup. Just wanted to have this as a placeholder

**Comment by bjwatson** [comment] 2016-09-07 22:49
Awesome, thanks Danny.

**Comment by bjwatson** [comment] 2016-09-13 21:00
@dhermes I published `0.9.0` to https://testpypi.python.org/pypi/ for Pub/Sub, Logging, Vision, and Language.

I did a little testing with Vision, and ran into the same `AttributeError: 'grpc._cython.cygrpc.Channel' object has no attribute 'unary_unary'` that I did for Speech v1beta1 a couple weeks ago. I keep testing and refining more tomorrow.

BTW, the gRPC path changes for Vision required a small hand-edit to the `image_annotator_pb2.py` file (fixing an import statement for `geometry_pb2.py`). We're going to have to figure out if we can automate this or fix it upstream in the Python proto generator, or it will be non-maintainable as auto-gen code.

**Comment by dhermes** [comment] 2016-09-13 21:12
Thanks for the update.

**Comment by bjwatson** [comment] 2016-09-15 01:06
@dhermes As it turns out, the `AttributeError: 'grpc._cython.cygrpc.Channel' object has no attribute 'unary_unary'` error is due to https://github.com/googleapis/gax-python/pull/127. When I use `google-gax` `0.12.5` (which does not have this change), the error goes away and Cloud Vision works perfectly.

I discussed with @geigerj, and there's more work we need to do to fully remove `grpc.beta`. The problem is that `google-gax` is fixed, but our GAPIC generated code still references the `grpc.beta` code. The error above is because `grpc` and `grpc.beta` use different default channels.

We have two options to move forward:
1) I'll generate the GAPIC code for `google-gax` `0.12.5`, which will still use `grpc.beta`. I think I can get this done tonight, but it means you won't have https://github.com/googleapis/gax-python/issues/126 in your next release.
2) We remove `grpc.beta` from our autogen code. Jacob estimates that this will take most of tomorrow to finish, so we'll be delayed by at least a day with this option.

What's your preference?

**Comment by dhermes** [comment] 2016-09-15 01:07
My preference is that we dump `grpc.beta`, so we can wait for releases that do the same.

**Comment by bjwatson** [comment] 2016-09-15 01:09
Ok, we will start work on that immediately. FYI @geigerj

**Comment by dhermes** [comment] 2016-09-15 01:27
Thanks.

**Comment by bjwatson** [comment] 2016-09-16 00:07
Latest versions referenced in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2324

BTW, when will the ML APIs start being used? (Vision, Language)

**Comment by dhermes** [comment] 2016-09-16 16:23
@bjwatson I didn't realize language was generated yet. I can do that ASAP. Pointer to PyPI links?

**Comment by daspecster** [comment] 2016-09-16 16:29
@dhermes is this it? https://pypi.python.org/pypi/gapic-google-cloud-language-v1beta1/0.9.1

**Comment by bjwatson** [comment] 2016-09-16 17:20
@daspecster @dhermes That's correct.

**Comment by dhermes** [comment] 2016-09-16 17:22
Still need to remove the namespace package bits. On it now.

**Comment by bjwatson** [comment] 2016-09-16 17:22
@daspecster @dhermes FYI, this has the updated links: https://github.com/googleapis/googleapis/pull/140

**Closed** 2016-09-16 17:57 UTC
Labels: GAX, logging, packaging, pubsub
