### ISSUE TITLE
Cloud Logging Handler import statement incorrect

### ISSUE THREAD

**Issue by Kagadar** [GoogleCloudPlatform/google-cloud-python#3264] opened 2017-04-03 01:10 UTC
On https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html#cloud-logging-handler the import statement is:
`from google.cloud.logging.handlers import CloudLoggingHandler`

According to the documentation for CloudLoggingHandler, https://googlecloudplatform.github.io/google-cloud-python/stable/logging-handlers.html#google.cloud.logging.handlers.handlers.CloudLoggingHandler, this should be:
`from google.cloud.logging.handlers.handlers import CloudLoggingHandler`

**Comment by waprin** [comment] 2017-04-03 17:16
The class is imported into the `handlers` package in `__init__.py` as a convenience to minimize redundancy. The class documentation gives the fully qualified name. Both import statements will work. Closing this as works as intended, feel free to re-open if you're not happy with this answer.

**Closed by waprin** 2017-04-03 17:16 UTC
Labels: api: logging
