### ISSUE TITLE
Expose BigQuery scopes

### ISSUE THREAD

**Issue by jlowin** [GoogleCloudPlatform/google-cloud-python#3067] opened 2017-02-24 15:53 UTC
The default [scopes](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L75) for the BigQuery Client do not include Google Drive, which makes it difficult to access federated data sources in Google Sheets. 

This can be worked around by manually constructing service account credentials with the appropriate scopes but that feels cumbersome. Am I not seeing a hook that allows scope modification when instantiating `bigquery.Client()`?

**Comment by daspecster** [comment] 2017-02-24 16:15
I don't believe that Google Drive is directly support to import data from for BigQuery.

This is the list of supported sources that I'm aware of.
https://cloud.google.com/bigquery/loading-data

**Comment by dhermes** [comment] 2017-02-24 17:36
@tswast Can you comment?

**Comment by tswast** [comment] 2017-02-24 17:46
Google Drive is in fact a supported federated query source. https://cloud.google.com/bigquery/external-data-sources#creating_an_external_table_using_google_drive

I don't think it should in the default scopes, but we definitely need a way to amend the scopes used in the client. This will be an issue for any of the external data sources described in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2372 For example, Cloud Storage will need it's scope to query files there.

**Comment by jlowin** [comment] 2017-02-24 18:29
@tswast I agree it shouldn't be in the default set, but it would be great to be able to flag it from the default `Client`. That was it could also be passed as a kwarg to `bigquery.Client.from_service_account_json()` without modification.

**Comment by jlowin** [comment] 2017-02-24 18:31
@daspecster I think the reason it isn't listed there is because unlike GCS files, GDrive files (including Google Sheets) can only be external -- not loaded as native tables.

**Comment by clifton** [comment] 2017-04-22 01:12
Ran into this today and couldn't find a work-around (even overwriting scopes wouldn't work!). In the mean-time I'm manually re-materializing the google sheets table.

**Comment by cdchan** [comment] 2017-05-05 16:44
I had the same issue as well -- created a client subclass that added the Drive scope but still couldn't get it to work.

**Comment by tswast** [comment] 2017-05-05 16:55
In the meantime you should be able to create a credentials object using `google.auth.default(scopes=...)`

https://google-auth.readthedocs.io/en/latest/reference/google.auth.html#google.auth.default

or from a service account file

https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials.from_service_account_file

You can pass the credentials object to the client constructor.

https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-client.html

I wonder if the helper methods such as `from_service_account_json()` should be removed in favor of using Google Auth credentials directly?

**Comment by cdchan** [comment] 2017-05-05 17:09
@tswast cool, thanks! I was able to get

```python
SCOPE = ('https://www.googleapis.com/auth/bigquery',
           'https://www.googleapis.com/auth/cloud-platform',
           'https://www.googleapis.com/auth/drive')
credentials, _ = google.auth.default(scopes=SCOPE)
client = bigquery.Client(credentials=credentials)
```
to work. Don't know why my subclass didn't before but this'll do.

**Comment by cdchan** [comment] 2017-05-05 17:26
@tswast I forgot that used the same workaround as @clifton and materialized the sheet into a real table. ☹️  What I have above doesn't actually work, so it's likely not a scoping issue.

**Comment by cdchan** [comment] 2017-05-10 20:24
Another update after taking a crack at this again. I was able to get the below to work, but only if I used the `GOOGLE_APPLICATION_CREDENTIALS` method with [Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) (the `google.auth.default`), not the Google Cloud SDK method. Maybe the scoping interacts weirdly with the SDK method, I'm uncertain.

```python
SCOPE = ('https://www.googleapis.com/auth/bigquery',
           'https://www.googleapis.com/auth/cloud-platform',
           'https://www.googleapis.com/auth/drive')
credentials, _ = google.auth.default(scopes=SCOPE)
client = bigquery.Client(credentials=credentials)
```

**Comment by dhermes** [comment] 2017-05-10 21:06
@cdchan That (i.e. using `google.auth.default`) is precisely what I would've suggested.

I'm not sure what the "Google Cloud SDK method" you refer to is, but would be happy to clear it up if I understood better.

**Comment by cdchan** [comment] 2017-05-10 21:14
@dhermes from what I understand, `google.auth.default` supplies [Application Default Credentials](http://google-auth.readthedocs.io/en/latest/reference/google.auth.html). Those are generated in a variety of methods, one of which pulls from the environment variable `GOOGLE_APPLICATION_CREDENTIALS` (which worked for me). Another method is to authenticate as a user via the Google Cloud SDK (as explained in the link). The Google Cloud SDK method for getting credentials works for queries in general but I couldn't get it to work with Google Sheets tables.

I did notice that `gcloud auth application-default login` (the Google Cloud SDK method) does have a `--scopes` flag and played around with that but still wasn't able to get it to work.

**Comment by dhermes** [comment] 2017-05-10 21:23
Ah gotcha. Yeah it just depends on what account was being used. I'd guess it was your personal account, which maybe didn't have the right permissions? When you say "couldn't get it to work", this means you got some kind of error?

**Comment by cdchan** [comment] 2017-05-10 21:30
@dhermes it had the right permissions (my work account) -- I was able to query the regular tables without issues and I had access to the Google Sheet itself.

The error I got was `400 The job encountered an internal error during execution and was unable to complete successfully.`  once I scoped the SDK method like so

```gcloud auth application-default login --scopes=https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/bigquery,https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/spreadsheets```

I didn't pursue this much further since that error message was pretty much a dead end. I can provide job ids if that helps.

**Comment by dhermes** [comment] 2017-05-10 21:36
Thanks for the info! The error message isn't clear to me though maybe @tswast recognizes it?

**Comment by tswast** [comment] 2017-05-10 22:02
Not a super helpful error message, but it is true that Google Cloud SDK credentials can't be used for all APIs. The reason is that it is using your user credentials, but associated with the Google Cloud SDK project. My guess is that the Drive and Sheets APIs aren't enabled on the Cloud SDK project.

With service account credentials, GOOGLE_APPLICATION_CREDENTIALS, it is using the project associated with that service account.

**Comment by dhermes** [comment] 2017-05-10 22:18
Ah good point @tswast. @cdchan You can "verify" this by hitting the [tokeninfo endpoint][1] or just check out

```python
>>> credentials.client_id
u'{SOMEID}-BLAHBLAH.apps.googleusercontent.com'
```

where `{SOMEID}` is a stand-in for a numerical ID. Then you can navigate to

```
https://console.cloud.google.com/home/dashboard?project={SOMEID}
```

to see the settings for that project (or to realize you don't have access to that project).

[1]: https://developers.google.com/apis-explorer/#p/oauth2/v2/oauth2.tokeninfo

**Comment by LauraRichter** [comment] 2017-10-25 14:01
A question on this --
When I do:

> SCOPE = ('https://www.googleapis.com/auth/bigquery',
>          'https://www.googleapis.com/auth/cloud-platform',
>          'https://www.googleapis.com/auth/drive')
> credentials, _ = google.auth.default(scopes=SCOPE)
> client = bigquery.Client(credentials=credentials)

The scopes on the credentials don't seem to be set? 

> credentials.scopes

gives nothing?

**Comment by tswast** [comment] 2017-10-25 15:18
/cc @jonparrott

For thoughts on allowing extra scopes in this client library.

**Comment by jonparrott** [comment] 2017-10-25 18:12
I don't want to add any more options to the constructor of clients and scopes are firmly in the purview of the auth layer. In the context of Cloud APIs and service accounts, scopes are essentially becoming meaningless.

If anything, we should just document how to obtain credentials with different scopes.

**Comment by LauraRichter** [comment] 2017-10-26 08:34
Is there a better way to do this then? I have a google sheet external data source BQ table, and I'm trying to read it using the python bigquery module. But I get an error about needing drive scope:

"Forbidden: 403 Access Denied: BigQuery BigQuery: No OAuth token with Google Drive scope was found."

What is the correct way to deal with permissions here?

**Comment by tswast** [comment] 2017-10-26 16:53
Hmm,

```
SCOPE = ('https://www.googleapis.com/auth/bigquery',
'https://www.googleapis.com/auth/cloud-platform',
'https://www.googleapis.com/auth/drive')
credentials, _ = google.auth.default(scopes=SCOPE)
client = bigquery.Client(credentials=credentials)
```

appears to be correct. Are you using a service account? If using the credentials from the `gcloud` command (cloud sdk) the sheets API is not enabled for that project. Better to use a service account as described at https://cloud.google.com/docs/authentication/getting-started

**Comment by jcommaroto** [comment] 2017-11-01 03:01
OK I am just starting out with all of this BUT I have been searching far and wide for a solution to the federated table issue and I haven't' been able to find much.  My code is below. I tried adding in the solution above but it won't work. I still receive " 403 Access Denied: BigQuery BigQuery: No OAuth token with Google Drive scope was found."

I am using a service account. Any ideas on where I am going wrong?

`import json

from httplib2 import Http


#Client Library that handles the complicated process of authentication
from oauth2client.service_account import ServiceAccountCredentials
from apiclient.discovery import build

scopes = (
    'https://www.googleapis.com/auth/bigquery',
    'https://www.googleapis.com/auth/cloud-platform',
    'https://www.googleapis.com/auth/drive',
)
credentials, _ = google.auth.default(scopes=scopes)
client = bigquery.Client(credentials=credentials)

credentials = ServiceAccountCredentials.from_json_keyfile_name(
    'client_key_dev.json', scopes)

import uuid

from google.cloud import bigquery

def query_myproject():
    client = bigquery.Client(project='MYPROJECTID')
    query_job = client.run_async_query(str(uuid.uuid4()), """
        #standardSQL
        SELECT *
        FROM test.test123
        LIMIT 10""")

    query_job.begin()
    query_job.result()  # Wait for job to complete.

    destination_table = query_job.destination
    destination_table.reload()
    for row in destination_table.fetch_data():
        print(row)

if __name__ == '__main__':
    query_myproject()
`

**Comment by tswast** [comment] 2017-11-13 19:31
@jcommaroto The `from oauth2client.service_account import ServiceAccountCredentials` is not the correct one to use for this library. The correct one to use is [google.oauth2.service_account.Credentials](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#module-google.oauth2.service_account)

Second, I see you create a `Client` in the root of the module, but then discard it and create a new one in the `query_myproject()` function. You should create a client in the way you do above that function to pass in scopes to the credentials first.

**Comment by tswast** [comment] 2017-11-13 19:33
@jonparrott I think you mentioned we should close this method, as we want to recommend people pass in credentials objects explicitly to the client constructor rather than add more options to the client for auth stuff?

**Closed** 2017-11-13 20:02 UTC
Labels: api: bigquery, type: question

**Comment by emetselaar** [comment] 2018-02-08 12:54
I had some issues with this as well. Solved it like this:

```python
from google.cloud import bigquery
from google.oauth2.service_account import Credentials

scopes = (
        'https://www.googleapis.com/auth/bigquery',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/drive'
    )
    credentials = Credentials.from_service_account_file('bq_auth.json')
    credentials = credentials.with_scopes(scopes)
    client = bigquery.Client(credentials=credentials)
```

Perhaps usable for someone.

**Comment by dmasin** [comment] 2018-02-16 15:21
Is that correct that the following is not expected to work by design or is it just a bug which will be fixed at some point:


(I understand that I could work around with service accounts if really necessary)

**Comment by tswast** [comment] 2018-02-16 16:56
@dmasin That's correct.

Using

```
$ gcloud auth application-default login \
> --scopes=https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/bigquery
```

is not expected to work, as that is using the credentials from the Cloud SDK. Instead it is recommended that you either use a [service account credentials](https://cloud.google.com/docs/authentication/getting-started) or [user authentication with client secrets](https://cloud.google.com/bigquery/docs/authentication/end-user-installed) from a project you have created.

**Comment by dmasin** [comment] 2018-02-17 18:23
thanks for the confirmation @tswast.
I've tried the service account route and it work fine. 

If we have 100 analysts querying bigquery (and spreadsheets) locally, is my understanding correct that we would need to share every of those spreadsheets with all analysts because you can't create groups of service accounts? This doesn't sound very scalable and is not usable in practice. I'm probably just missing something. Would you have an advice on how to share >100 spreadsheets with hundreds of service accounts?

**Comment by tswast** [comment] 2018-02-17 19:03
@dmasin I am able to add a service account to a Google Group on https://groups.google.com, but I wasn't able to on my GSuite account due to administrator restrictions.

Options:
- You could create an invite-only group and direct-add the service accounts.
- Use  [user authentication with client secrets](https://cloud.google.com/bigquery/docs/authentication/end-user-installed) from a project you have created. This requires using the [google-auth-oauthlib library](https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib) to create a credentials object.

**Comment by aymanfarhat** [comment] 2018-08-12 05:07
Quick tip in case anyone is facing this issue when setting up a drive based federated source to BQ via Apps Script. Enabling the Drive API in the UI won't be enough. In case the app doesn't explicitly call any Drive related API calls, the drive scope won't get added into the script. 

This worked in my case by explicitly enabling the drive scope in the manifest.json file (make sue to select  "show manifest file" in the UI). The scope for drive is https://www.googleapis.com/auth/drive to be added into the *oauthScopes* list, example:

```
{
  "timeZone": "Asia/Dubai",
  "oauthScopes": [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/spreadsheets"
  ],
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "Drive",
      "serviceId": "drive",
      "version": "v3"
    }, {
      "userSymbol": "BigQuery",
      "serviceId": "bigquery",
      "version": "v2"
    }]
  },
  "webapp": {
    "access": "MYSELF",
    "executeAs": "USER_DEPLOYING"
  },
  "exceptionLogging": "STACKDRIVER"
}

```
**Disclaimer: This is not an official solution from Google. It worked for my specific individual use case and it might (or not) work for yours. No warranties given, use and test at your own risk.**

**Comment by ikendoit** [comment] 2021-09-13 00:38
Adding to this thread for passer by's who met this error:
- My use case was: To use local gcloud credential to query external-table (spreadsheet) using python
- Not to use service account ( each analyst in my company don't have their own service account, that will change soon but not for now ) 

I found that by running:
`gcloud auth login --enable-gdrive-access --update-adc`

This allows the local ADC to have access to Drive, with that, python bq-client can successfully queries from external-table. 

Reference: https://cloud.google.com/sdk/gcloud/reference/auth/login
