### ISSUE TITLE
ImportError: cannot import name JSONClient

### ISSUE THREAD

**Issue by znewman01** [GoogleCloudPlatform/google-cloud-python#3322] opened 2017-04-24 14:27 UTC
I believe this is a packaging bug; I'm reporting on behalf of a StackOverflow user.

http://stackoverflow.com/questions/43584965/importerror-cannot-import-name-jsonclient

    $ sudo pip install --upgrade google-cloud
    File "/usr/local/bin/pip", line 7, in <module>
        from pip import main
      File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 26, in <module>
        from pip.utils import get_installed_distributions, get_prog
      File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 27, in <module>
        from pip._vendor import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
        @_call_aside
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
        declare_namespace(pkg)
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2091, in _handle_ns
        loader.load_module(packageName)
      File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
        mod = imp.load_module(fullname, self.file, self.filename, self.etc)
      File "/home/engineer/.local/lib/python2.7/site-packages/google/cloud/logging/__init__.py", line 18, in <module>
        from pkg_resources import get_distribution
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
        @_call_aside
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
        f(*args, **kwargs)
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3064, in _initialize_master_working_set
        for dist in working_set
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3064, in <genexpr>
        for dist in working_set
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2594, in activate
        declare_namespace(pkg)
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2162, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/engineer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2097, in _handle_ns
        loader.load_module(packageName)
      File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
        mod = imp.load_module(fullname, self.file, self.filename, self.etc)
      File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/__init__.py", line 18, in <module>
        from google.cloud.logging.client import Client
      File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/client.py", line 32, in <module>
        from google.cloud.client import JSONClient
    ImportError: cannot import name JSONClient

1. OS type and version
Looks like Linux? Possibly macOs.
2. Python version and virtual environment information `python --version`
Python 2.7, don't know details.
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
This isn't working generally.
4. Stacktrace if available
See above.
5. Steps to reproduce
??
6. Code example
N/A

You may want to engage the user on SO instead.

**Comment by dhermes** [comment] 2017-04-24 17:09
Here is my answer (as a comment) from StackOverflow:

> The `pip` error stack trace isn't that useful. More useful would be to run `pip show google-cloud google-cloud-core google-cloud-vision`

I am going to close this out since the issue is almost certainly an old version of `pip` (H/T to @lukesneeringer) or a strange combination of old and new versions of some packages and their dependencies.

Happy to re-open if there is a way to get more information.

**Closed by dhermes** 2017-04-24 17:09 UTC
Labels: packaging
