### ISSUE TITLE
Udpate contributing.rst

### ISSUE THREAD

**Issue by geigerj** [GoogleCloudPlatform/google-cloud-python#3300] opened 2017-04-14 01:43 UTC
Information in [contributing.rst](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst) referring to `tox` or to the `system_tests` directory no longer works after #3146.

**Comment by dhermes** [comment] 2017-04-14 02:10
Closing as a duplicate of #3205, thanks for taking the time to file @geigerj!

Last I recall, @lukesneeringer was on the hook for this, though maybe that's no longer true.

**Closed by dhermes** 2017-04-14 02:10 UTC
Labels: priority: p2+, type: enhancement

**Comment by lukesneeringer** [comment] 2017-04-14 16:09
I am still on the hook for this. :-)
