### ISSUE TITLE
Pubsub: New version (0.37.2) caused the stream to be throttled and spiky

### ISSUE THREAD

**Issue by joshuahendinata** [GoogleCloudPlatform/google-cloud-python#5841] opened 2018-08-24 04:37 UTC
I have an unusual issue that might be particular to my use case.

I am comparing the data emitted from kafka and pubsub. Starting from 0.37 release, when an error occurred (log below), the stream from pubsub seems to be throttled and spiky.

Screenshot below. Blue is stream from kafka, Red is stream from pubsub. Notice that before the error at 11:35:00, there are minimal to no difference between the 2 streams

![kafka-pubsub-comparison](https://user-images.githubusercontent.com/5980973/44564700-045e7680-a797-11e8-8933-a4a2ccad6341.png)

When I revert back to 0.35.4, the issue does not surface (I have monitored it for 3 days). But as soon as I redeploy using 0.37.2, the issue appear in about 1 hour after deployment

I noticed there's an error at the time of divergence between the two. This error also happened in 0.35.4 but it did not cause the divergence

![pubsub-logging](https://user-images.githubusercontent.com/5980973/44564938-2efcff00-a798-11e8-99a5-88ce58e6c46b.png)
![logging-2](https://user-images.githubusercontent.com/5980973/44565227-98c9d880-a799-11e8-99d8-fdefbe7d22b8.png)

Here's a snippet for my code
```python 
while self._running:
   logger.info("starting for subscription: {}".format(self._subscription_name))
   self._future = self._consumer.subscribe(self._subscription_name, self.callback)
   try:
      self._future.result()  
   except Exception as ex:
      logger.error("Exception in subscriber for {}. Error message: {}. ".format(self._subscription_name, ex.message))
      logger.info("retrying for subscription {}...".format(self._subscription_name))
      self._consumer = pubsub.SubscriberClient()
```

Additional detail
1. OS type and version: **Debian 9**
2. Python version: **Python 2.7.15**
3. google-cloud-pubsub version: **0.37.2**

**Comment by theacodes** [comment] 2018-08-24 16:58
This is *probably* expected behavior. The stream gets re-established about every 60 minutes, and when it's re-established you will see a spike in the backlog of messages as the Pub/Sub server will send a much higher number on that initial request if the subscriber has been down for a while.

What is concerning to me is the presence of "Can not recv()" errors, that shouldn't happen in normal operation. It's also weird to see so many consecutive timeouts - are you starting multiple subscribers in the same process?

**Comment by joshuahendinata** [comment] 2018-08-24 19:41
I think if you count the overall sum of value then in the end it is the same, however, we are running an anomaly detection and hence the spiky behaviour might cause an issue. 

I have tried several thing that fixed the issue
1. Deleting and re-creating the subscription 
2. Redeploying the application

For the consecutive deadline, yes I am running multiple subscriber on the process and it’s difficult to pinpoint which log is which. 

But what I notice is that, the “deadline exceeded” always come before the error occured

**Comment by theacodes** [comment] 2018-08-24 19:43
Yeah, the deadline exceeded is an expected error and is part of the design (basically, our servers force a re-connect every so often, and that's what you're seeing there).

I think this is working as intended given the design of the Pub/Sub service, so I'm going to close this, but if you think there's more we can do let me know.

**Closed by theacodes** 2018-08-24 19:43 UTC
Labels: api: pubsub, type: question
