### ISSUE TITLE
Pubsub stops receiving messages

### ISSUE THREAD

**Issue by anmol1vw13** [GoogleCloudPlatform/google-cloud-python#5314] opened 2018-05-09 05:55 UTC
I have storage as my publisher and a subscriber on the compute engine as the receiver. 
Below is the subscriber code that I use.
```
def receive_messages_with_flow_control(project, subscription_name):
    """Receives messages from a pull subscription with flow control."""
    subscriber = pubsub_v1.SubscriberClient()
    subscription_path = subscriber.subscription_path(
        project, subscription_name)
    idocStorageAbsolutePath = config.idocsStorageAbsolutePath
    makeDirIfNotExist(idocStorageAbsolutePath)
    def callback(message):
        storage_data = message.data
        process_data(storage_data,idocStorageAbsolutePath)
        message.ack()

    # Limit the subscriber to only have ten outstanding messages at a time.
    flow_control = pubsub_v1.types.FlowControl(max_messages=50)
    subscriber.subscribe(
        subscription_path, callback=callback, flow_control=flow_control)

    # The subscriber is non-blocking, so we must keep the main thread from
    # exiting to allow it to process messages in the background.
    logger.info('Listening for messages on {}'.format(subscription_path))
    while True:
        time.sleep(5)
```
After a day or two of the subscriber running, it stops consuming the messages. I have to manually restart it to make it work again.  
Please suggest what I am doing wrong.

PS: The data flowing speed into the topic is high during the day and reduces at night.

**Comment by crwilcox** [comment] 2018-05-09 15:18
@anmol1vw13 , which version of google-cloud-pubsub are you using? Could you please share the output of `pip freeze`?

**Comment by shomratalon** [comment] 2018-05-10 08:51
I have the same issue, this is my `pip freeze`:

```
backports-abc==0.5
cachetools==2.0.1
certifi==2017.11.5
chardet==3.0.4
cognitive-luis==0.1
colorama==0.3.2
dill==0.2.7.1
ecdsa==0.11
enum34==1.1.6
euca2ools==3.1.0
funcsigs==1.0.2
future==0.16.0
futures==3.2.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gcimagebundle==1.3.1
google-api-core==0.1.4
google-auth==1.4.1
google-cloud==0.32.0
google-cloud-bigquery==0.28.0
google-cloud-bigquery-datatransfer==0.1.1
google-cloud-bigtable==0.28.1
google-cloud-container==0.1.1
google-cloud-core==0.28.1
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.1
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.1
google-cloud-pubsub==0.33.1
google-cloud-resource-manager==0.28.1
google-cloud-runtimeconfig==0.28.1
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.17.0
google-cloud-translate==1.3.1
google-cloud-videointelligence==1.0.1
google-cloud-vision==0.29.0
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
googlemaps==2.5.1
grpc-google-iam-v1==0.11.4
grpcio==1.11.0
html5lib==0.999
httplib2==0.11.3
idna==2.6
intervaltree==2.1.0
Jinja2==2.10
lxml==3.4.0
MarkupSafe==1.0
oauth2client==3.0.0
paramiko==1.15.1
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
protobuf==3.5.2.post1
psutil==5.4.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
python-apt==0.9.3.12
pytz==2018.4
PyYAML==3.11
requestbuilder==0.2.3
requests==2.18.4
rsa==3.4.2
singledispatch==3.4.0.3
six==1.10.0
sortedcontainers==1.5.7
tornado==4.5.3
urllib3==1.22
virtualenv==1.11.6
```

I upgraded to `google-cloud-pubsub==0.33.1`, but this issue isn't solved yet. My callback is the same (process the data, ack the message).

**Comment by theacodes** [comment] 2018-05-11 20:53
Hi there, please try using the `subscribe_experimental` function present in pubsub `0.34.0`.  This will soon become the default behavior in 0.35.0 and it resolves several issues with streaming pull. If you're still experiencing issues after that, let us know and we'll re-open.

**Comment by anmol1vw13** [comment] 2018-05-13 10:54
Sorry for the delayed response.
pip freeze:
acme==0.14.2
Babel==1.3
beautifulsoup4==4.4.1
boto==2.38.0
cachetools==2.0.1
certbot==0.14.2
certbot-apache==0.14.2
certifi==2018.1.18
chardet==3.0.4
ConfigArgParse==0.11.0
configobj==5.0.6
crcmod==1.7
cryptography==1.7.1
dnspython==1.15.0
docutils==0.12
enum34==1.1.2
feedparser==5.1.3
funcsigs==0.4
futures==3.2.0
gdata==2.0.18
google-api-core==0.1.4
google-api-python-client==1.6.5
google-auth==1.4.1
google-cloud-core==0.28.1
google-cloud-datastore==1.5.0
google-cloud-pubsub==0.32.0
google-cloud-storage==1.7.0
google-compute-engine==2.3.6
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
grpcio==1.10.0
gyp==0.1
html5lib==0.999
httplib2==0.11.1
idna==2.6
ipaddress==1.0.17
Jinja2==2.8
linecache2==1.0.0
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
mock==1.3.0
ndg-httpsclient==0.4.2
oauth2client==4.1.2
parsedatetime==2.1
pbr==1.8.0
Pillow==3.1.2
protobuf==3.5.2.post1
psutil==5.4.3
psycopg2==2.6.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyChart==1.39
pycrypto==2.6.1
pycurl==7.43.0
pydot==1.0.29
Pygments==2.1
PyICU==1.9.2
pyinotify==0.9.6
PyMySQL==0.8.0
PyOpenGL==3.0.2
pyOpenSSL==17.0.0
pyparsing==2.0.3
Pyrex==0.9.8.5
pyRFC3339==1.0
python-apt==1.1.0b1
python-augeas==0.5.0
python-dateutil==2.4.2
python-http-client==2.4.0
python-ldap==2.4.22
python-openid==2.2.5
python-stdnum==1.2
python2-pythondialog==3.3.0
pytz==2014.10
PyWebDAV==0.9.8
PyYAML==3.11
reportlab==3.3.0
requests==2.18.4
roman==2.0.0
rsa==3.4.2
sendgrid==4.2.0
simplejson==3.8.1
six==1.10.0
traceback2==1.4.0
unittest2==1.1.0
untangle==1.1.1
uritemplate==3.0.0
urllib3==1.22
uTidylib==0.2
vatnumber==1.2
vobject==0.8.1rc0
Werkzeug==0.10.4
xlwt==0.7.5
zope.component==4.2.2
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.1.3
ZSI==2.1a1

**Comment by shomratalon** [comment] 2018-05-13 11:07
Hi, getting an exception with 0.34.0:
```
[2018-05-13 12:30:14,744 - ERROR - Thread-17 - _channel] Exception iterating requests!
Traceback (most recent call last):
  File "/Users/alonshomrat/Library/Python/2.7/lib/python/site-packages/grpc/_channel.py", line 187, in consume_request_iterator
    request = next(request_iterator)
  File "/Users/alonshomrat/Library/Python/2.7/lib/python/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py", line 100, in __iter__
    yield self._initial_request()
  File "/Users/alonshomrat/Library/Python/2.7/lib/python/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 313, in _get_initial_request
    lease_ids = self._leaser.ack_ids
AttributeError: 'NoneType' object has no attribute 'ack_ids'
```
I think it's the CleanupThread.

Created a script to reproduce:

1. Create topic
2. Insert message to it.
3. Create subscription.
4. Start subscribe.
5. Get exception (CleanupThread in _channel -> grpc package).

```
# Create a topic
# Insert data to the topic
# Create subscription and connect it to the topic
# Start subscriber
# Get exception
from google.cloud.pubsub_v1 import PublisherClient, SubscriberClient

publisher_obj = PublisherClient()
subscriber_obj = SubscriberClient()
topics_path = [u'projects/your-project-name/topics/topic_general']
subscribers_path = [u'projects/your-project-name/subscriptions/instance_general']

def create_topics():
    for topic in topics_path:
        try:
            publisher_obj.create_topic(topic)
        except Exception as e:
            print("Topic {}: {}. Notice: don't forget to run pubsub emulator before".format(topic, e.message))

def publish_messages(data, message_type):
    response = publisher_obj.publish(topics_path[0], data=data, type=message_type)
    return response

def create_subscriptions():
    subscriptions = []
    for subscribe, topic in zip(subscribers_path, topics_path):
        subscriptions.append(subscriber_obj.create_subscription(subscribe, topic))
    return subscriptions

def start_subscribe():
    subscription_path = SubscriberClient().subscription_path("your-project-name", "instance_general")
    _ = SubscriberClient().subscribe(subscription_path, callback=lambda x: x)

def pubsub_error():

    create_topics()
    a = publish_messages(data='{"key3": "value3", "key2": "value2", "key1": "value1"}', message_type="/webhook/webhook_type")
    create_subscriptions()
    start_subscribe()


if __name__ == "__main__":
    pubsub_error()
```

**Comment by anmol1vw13** [comment] 2018-05-13 11:15
@theacodes What I've done is replace subscriber.subscribe(...) with subscriber.subscribe_experimental(...).
Is that correct? I didn't find any exception while running it.
Btw, could you tell me what's different between subscribe and subscribe_experimental? I mean what in subscriber() was causing it to stop!

**Comment by anmol1vw13** [comment] 2018-05-13 16:08
@theacodes @crwilcox Please reopen the issue.  Below is the part of the code which has subscriber.subscribe changed to subscriber.subscribe_experimental.

The script this time, stopped after just a few hours. I had to restart it to get it to start working.
Need your help to figure this out.
`def receive_messages_with_flow_control(project, subscription_name):
    """Receives messages from a pull subscription with flow control."""
    subscriber = pubsub_v1.SubscriberClient()
    subscription_path = subscriber.subscription_path(
        project, subscription_name)
    idocStorageAbsolutePath = config.idocsStorageAbsolutePath
    makeDirIfNotExist(idocStorageAbsolutePath)
    def callback(message):
        storage_data = message.data
        process_data(storage_data,idocStorageAbsolutePath)
        message.ack()

    # Limit the subscriber to only have ten outstanding messages at a time.
    flow_control = pubsub_v1.types.FlowControl(max_messages=50)
    subscriber.subscribe_experimental(
        subscription_path, callback=callback, flow_control=flow_control)

    # The subscriber is non-blocking, so we must keep the main thread from
    # exiting to allow it to process messages in the background.
    logger.info('Listening for messages on {}'.format(subscription_path))
    while True:
        time.sleep(5)`

**Comment by crwilcox** [comment] 2018-05-13 17:46
@anmol1vw13 sorry for the delay. Both @theacodes and myself are at PyCon US so responses may be a bit more asynchronous than normal. 

Thanks for trying out the experimental method. As @theacodes said, that is the future implementation so figuring out how that implementation works would be very beneficial to us and hopefully other users.

Could you describe what you mean by 'it stopped'? Is the process terminating, are you monitoring unprocessed messages?

**Comment by anmol1vw13** [comment] 2018-05-13 18:15
@crwilcox Thanks for the response. Badly need it.

The process is still alive but there are unprocessed messages left. 
If you could help me in getting the process killed when the messages stop being consumed, that would do too. I say this because, I have a cron which restarts the process if the process isn't alive.

**Comment by anmol1vw13** [comment] 2018-05-13 18:25
I haven't put any logger.debug statements in my code. All my logs are of info level. Would debug level logs do any good?

**Comment by theacodes** [comment] 2018-05-13 18:29
Yes, the subscriber does a significant amount of logging specifically to
help in this case.

**Comment by anmol1vw13** [comment] 2018-05-13 18:34
PFB, the logger code I had written. I changed the logging level to debug but it still isn't giving the subscriber logs in.
This project was the first time I put logging into a python code. Prior to that I mostly used print statements.
Please let me know where I am wrong.
```
import logging
import logging.config
import time
import os
# def logger():
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

try:
    os.mkdir("../logs")
except:
    None
hdlr = logging.FileHandler('../logs/topicSubscriber.log')
# os.environ["TZ"] = "US/Pacific"
# logging.Formatter.

formatter = logging.Formatter('[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s','%Y-%m-%d %H:%M:%S')
hdlr.setFormatter(formatter)
logger.addHandler(hdlr)
logger.info('Completed configuring logger()!')
```

**Comment by theacodes** [comment] 2018-05-13 18:36
You may need to config the root logger. Please try logging.basicConfig.

**Comment by anmol1vw13** [comment] 2018-05-13 19:11
So, I have got the debug logging working and yes, the subscriber logs are coming in. But, it stops arbitrarily in a few hours and I don't know how to notify myself when that happens. If I could know that, I might as well could kill the process :)
Do you have an idea of how that could be done?
If not, I'll check up on it after a few hours.

**Comment by anmol1vw13** [comment] 2018-05-13 20:29
It stopped. 
The logs: https://gist.github.com/anmol1vw13/eea5d5a8a15798e2d5221a67adb444b0

**Comment by theacodes** [comment] 2018-05-14 02:42
Thanks, @anmol1vw13. Your logs confirm this is a duplicate of #5306. I'm closing this - you can follow the progress of the fix over there.

**Closed by theacodes** 2018-05-14 02:42 UTC
Labels: api: pubsub, type: question

**Comment by anmol1vw13** [comment] 2018-05-17 03:40
@theacodes I'm not using `subscriber_experimental` coz it's not very stable right now but would continue to use `subscriber` present in 0.32.0.
All I want to know is, when `subscriber` stops it gives out the following in the logs. How should I handle it, so I'm able to restart the subscriber?

```
[2018-05-16 21:24:03] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/thread.py:291} DEBUG - Handling 1 batched requests
[2018-05-16 21:24:03] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_consumer.py:246} DEBUG - Sending request on stream
[2018-05-16 21:24:06] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:362} DEBUG - The current p99 value is 10 seconds.
[2018-05-16 21:24:06] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:368} DEBUG - Renewing lease for 0 ack IDs.
[2018-05-16 21:24:06] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:388} DEBUG - Snoozing lease management for 8.475584 seconds.
[2018-05-16 21:24:14] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:362} DEBUG - The current p99 value is 10 seconds.
[2018-05-16 21:24:14] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:368} DEBUG - Renewing lease for 0 ack IDs.
[2018-05-16 21:24:14] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:388} DEBUG - Snoozing lease management for 5.516442 seconds.
[2018-05-16 21:24:20] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:362} DEBUG - The current p99 value is 10 seconds.
[2018-05-16 21:24:20] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:368} DEBUG - Renewing lease for 0 ack IDs.
[2018-05-16 21:24:20] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:388} DEBUG - Snoozing lease management for 4.373885 seconds.
[2018-05-16 21:24:22] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_consumer.py:399} DEBUG - Resuming consumer
[2018-05-16 21:24:22] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_consumer.py:440} DEBUG - Stopping helper thread Thread-ConsumeBidirectionalStream
[2018-05-16 21:24:22] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_consumer.py:243} DEBUG - Request generator signaled to stop.
[2018-05-16 21:24:24] {/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/policy/base.py:355} DEBUG - Consumer inactive, ending lease maintenance.
```

**Comment by anmol1vw13** [comment] 2018-05-17 11:27
@theacodes @crwilcox Anything on this?

**Comment by anmol1vw13** [comment] 2018-05-19 03:34
@crwilcox Where should this be checked? In the while loop that I have.(I have given the sample code above)
Could you provide me with an example of how it must be used.
Also, is there any other way? subscriber_experimental isn't reliable.

**Comment by anmol1vw13** [comment] 2018-05-23 14:46
@crwilcox @theacodes Please help me out people?
