### ISSUE TITLE
`Blob.upload_from_filename` fails silently if the blob name starts with '/'

### ISSUE THREAD

**Issue by tillahoffmann** [GoogleCloudPlatform/google-cloud-python#3675] opened 2017-07-26 12:30 UTC
Using `google-cloud-storage==1.2.0`, attempting to upload files using `Blob.upload_from_filename` fails silently (i.e. no error is raised but the blob is not uploaded) if the blob name starts with a forward slash `/`. A basic example is given below.

```python
import google.cloud.storage

client = google.cloud.storage.Client()
bucket = client.get_bucket('some-bucket')
blob = bucket("/some-blob")
blob.upload_from_filename("some-file")
```

**Comment by dhermes** [comment] 2017-07-26 17:08
Whoa! Thanks for the bug report @tillahoffmann, I'll look into it.

**Comment by tseaver** [comment] 2017-07-26 17:20
I can't reproduce:

```python
>>> bucket = client.create_bucket('gcp-issue-3675')
>>> list(bucket.list_blobs())
[]
>>> blob = bucket.blob('/some-blob')
>>> blob.upload_from_filename('/tmp/gcp-issue-3675.txt')
>>> 
>>> blob.exists()
True
>>> [b.name for b in bucket.list_blobs()]
['/some-blob']
>>> blob.download_as_string()
b'Now is the time for all good men to come to the aid of the party.\n'
```

**Comment by lukesneeringer** [comment] 2017-08-07 16:29
@tillahoffmann Can you give us the exact code so we can attempt to reproduce?

**Comment by tillahoffmann** [comment] 2017-08-08 08:27
@lukesneeringer, sorry that this has taken me so long. I'll try and get a reproducible example to you by the end of next week.

**Comment by lukesneeringer** [comment] 2017-08-08 17:49
@tillahoffmann Not a problem.

I am going to close the issue in the meantime, just for tracking sanity. Feel free to reopen when you have a repro case. :-)

**Closed by lukesneeringer** 2017-08-08 17:49 UTC
Labels: api: storage, priority: p2+, status: investigating

**Comment by tillahoffmann** [comment] 2017-08-15 21:07
I can no longer reproduce this issue using `1.3.0`.

**Comment by And03380** [comment] 2019-12-13 22:56
I am having issues uploading a file from the "/tmp/my_file.csv" in a Google Cloud Function. I can read from the file, but on "blob.upload_from_file(/tmp/my_file.csv)" the function does not find the file.

Thanks,

**Comment by jusjosgra** [comment] 2021-01-12 18:34
I also have this same issue.
Silent failure with a data blob starting with '/' but it works if it starts without, which doesnt match the usage pattern for downloading a blob

**Comment by axeltidemann** [comment] 2021-06-04 16:10
Same here. I am on `1.3.0`.

**Comment by tseaver** [comment] 2021-06-07 11:57
I still cannot reproduce this issue:

```bash
$ python3.9 -m venv /tmp/repro-gcp-3675
$ /tmp/repro-gcp-3675/bin/pip install google-cloud-storage
...
Successfully installed cachetools-4.2.2 certifi-2021.5.30 cffi-1.14.5 chardet-4.0.0 google-api-core-1.29.0 google-auth-1.30.1 google-cloud-core-1.6.0 google-cloud-storage-1.38.0 google-crc32c-1.1.2 google-resumable-media-1.3.0 googleapis-common-protos-1.53.0 idna-2.10 packaging-20.9 protobuf-3.17.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyparsing-2.4.7 pytz-2021.1 requests-2.25.1 rsa-4.7.2 six-1.16.0 urllib3-1.26.5
$ cat > /tmp/my_file.csv
"Date","Action","Count"
"2021-06-07","Testing", 1
$ cat /tmp/repro-gcp-3675/repro_gcp_3675.py 
from google.cloud.storage import Client

BUCKET_NAME = "repro-gcp-3675"
BLOBNAME = "/my_file.csv"
FILENAME = f"/tmp{BLOBNAME}"

def main():
    client = Client()
    bucket = client.get_bucket(BUCKET_NAME)
    blob = bucket.blob(BLOBNAME)
    blob.upload_from_filename(FILENAME)

    assert blob.exists()

    assert BLOBNAME in [blob.name for blob in bucket.list_blobs()]


if __name__ == "__main__":
    main()
$ /tmp/repro-gcp-3675/bin/python /tmp/repro-gcp-3675/repro_gcp_3675.py
$
```

Note that the `google-cloud-storage` library is no longer maintained in this repository.  If you can provide a reproducible case for this issue, please open a new issue in the [new repository](https://github.com/googleapis/python-storage/issues).
