### ISSUE TITLE
Pull Subscription Errors

### ISSUE THREAD

**Issue by fabltd** [GoogleCloudPlatform/google-cloud-python#5800] opened 2018-08-14 17:12 UTC
Hi 

I am using the python example for receive messages ( Pull Subscription)

    subscriber = pubsub_v1.SubscriberClient()
    subscription_path = subscriber.subscription_path(project, subscription_name)

This is working but the following error is logged.

Observed recoverable stream error 504 Deadline Exceeded
Observed recoverable stream error 504 Deadline Exceeded
Re-established stream

Where does this come from ? How to fix.

These messages appear every 10 Mins. The stream does appear to be re-established and continues to work.

There are no messages being sent while this is occurring.

Thanks

JT

**Comment by theacodes** [comment] 2018-08-14 17:36
Those are normal.

**Comment by theacodes** [comment] 2018-08-14 19:49
Closing for now, but let us know if there's anything else we can help with.

**Closed by theacodes** 2018-08-14 19:49 UTC

**Comment by fabltd** [comment] 2018-08-14 19:59
Any way to mute these notifications?

**Comment by theacodes** [comment] 2018-08-14 20:14
You can use the standard library logging utilities to filter these logs.

**Comment by aloosley** [comment] 2019-12-03 12:43
I thought I'd add for anybody ending up at this page that there is an explanation for these types of errors here:

https://cloud.google.com/pubsub/docs/reference/error-codes

**Comment by vinpalace** [comment] 2020-06-03 09:00
A simple way you can filter out these is by adding a filter to your Handler.

[here](https://stackoverflow.com/q/879732/6740036)
```
    def filter(self, record):
        # filter out google_api notifications
        return not record.getMessage().startswith('Observed')
```

**Comment by asfaltboy** [comment] 2021-02-14 12:36
The docs have this to say about 504 errors:
> The request did not complete in the time allocated. This can be caused by network issues from the client to the server, and it can also occur rarely on the server. On this error, the server may or may not execute the operation requested.

With that in mind, I wonder if this should be treated as a bug, since the error notifications occur exactly every 10 minutes (-1 second), and seems to be reproducible by different users.

**Comment by rajithavk** [comment] 2021-08-24 04:09
> The docs have this to say about 504 errors:
> 
> > The request did not complete in the time allocated. This can be caused by network issues from the client to the server, and it can also occur rarely on the server. On this error, the server may or may not execute the operation requested.
> 
> With that in mind, I wonder if this should be treated as a bug, since the error notifications occur exactly every 10 minutes (-1 second), and seems to be reproducible by different users.

Agreed, if the document says it should be rare but we notice it periodically as in 10 minutes as observed by ourselves too, something is not right. Surprising why google has not yet clarified this.
