### ISSUE TITLE
Performance with multiple upload in parallel.

### ISSUE THREAD

**Issue by esseti** [GoogleCloudPlatform/google-cloud-python#3451] opened 2017-05-24 08:38 UTC
Hello

I'm using the library to store data in the cloud storage from some containers run by kubernetes. The overview of the system is this:

- we provide an API to upload blob files
- this API allows chunk uploads, such that, you can call it in parallel and chunks are uploaded. This is done using the client
```
 blob = Blob(user_id + '/' +upload_id + "-" + chunk.chunk_tmp_name,
                    BlobStorage.bucket_tmp)
        res = blob.upload_from_string(data)
```
- when all the chunks are uploaded an API must be called to recompose everything in one single file.

Now, i've the system up and running. but there's a different in the performance if the calls are sequential or parallel.

I've a python script that calls my API and works ok, very fast.

I've a nodejs script that calls the API, and it does it asynchronously, thus multithreading and this goes in timeout.

 I see up to 15s per upload when using node (uwsgi goes in harkiri mode sometime) whit python it takes 0.2s at max. 

Is the upload blocking and only 1 operation at time? 
is there a way to make this working somehow or what could i do?

**Comment by lukesneeringer** [comment] 2017-08-08 05:11
Hi @esseti,
I admit I am a bit confused by this issue (in particular since you say that in Python it takes at worst 0.2 seconds...perhaps you have the languages switched?).

Due to the differences in Python and Node.js, it is correct that things like uploads will block here. This is by design. You can easily run an upload in a thread or process if you so desire, but we leave that to you. because concurrency strategies in Python differ so widely.

Beyond that, I am having trouble determining what issue you are reporting, so I am going to close this. I am very happy to revisit it if needed; feel free to reopen in that case.

**Closed by lukesneeringer** 2017-08-08 05:11 UTC

**Comment by esseti** [comment] 2017-08-08 12:37
In reality the problem was that I instantiate the `client` and the `blob` at class level and not within the method. Such that, if there are multiple calls to the funzion the code stucks and have problem to perform the calls. By moving everything within the method, the things works just fine.
