### ISSUE TITLE
enum34 installed for pip -t

### ISSUE THREAD

**Issue by eyaler** [GoogleCloudPlatform/google-cloud-python#5260] opened 2018-04-29 16:48 UTC
when installing with pip install -t target, enum34 gets installed for python 3.6, and prevents later imports

**Comment by tseaver** [comment] 2018-04-30 15:28
Can you please provide the exact command line you are using (i.e., which API libraries are you installing)?

**Comment by eyaler** [comment] 2018-04-30 15:37
pip install google-cloud-vision==0.31.0 -t my_folder

**Comment by tseaver** [comment] 2018-04-30 16:32
OK, that one has the following dependency:

```python
vision/setup.py:    'enum34;python_version<"3.4"'
```
I tried reproducing via:

```bash
$ /opt/Python-3.6.3/bin/python3 -m venv /tmp/gcp-5260
$ /tmp/gcp-5260/bin/pip install --upgrade setuptools pip wheel
$ /tmp/gcp-5260/bin/pip install google-cloud-vision -t /tmp/gcp-5260/waaa
...
Installing collected packages: pytz, chardet, certifi, idna, urllib3, requests, six, setuptools, protobuf, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, googleapis-common-protos, grpcio, google-api-core, enum34, google-cloud-vision
Successfully installed cachetools-2.0.1 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 google-api-core-1.1.1 google-auth-1.4.1 google-cloud-vision-0.31.0 googleapis-common-protos-1.5.3 grpcio-1.11.0 idna-2.6 protobuf-3.5.2.post1 pyasn1-0.4.2 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.18.4 rsa-3.4.2 setuptools-39.1.0 six-1.11.0 urllib3-1.22
```

When I install directly in the virtualenv (without the `-t`) it is also installing `enum34`:

```bash
$ /tmp/gcp-5260/bin/pip install google-cloud-vision
...
Installing collected packages: enum34, six, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, protobuf, chardet, idna, certifi, urllib3, requests, pytz, googleapis-common-protos, grpcio, google-api-core, google-cloud-vision
Successfully installed cachetools-2.0.1 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 google-api-core-1.1.1 google-auth-1.4.1 google-cloud-vision-0.31.0 googleapis-common-protos-1.5.3 grpcio-1.11.0 idna-2.6 protobuf-3.5.2.post1 pyasn1-0.4.2 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.18.4 rsa-3.4.2 six-1.11.0 urllib3-1.22
```

@jonparrott Any clues why the platform spec isn't working?

**Comment by tseaver** [comment] 2018-04-30 17:31
See PyPA discussion linked from PR #4991, which landed the change to `vision/setup.py`.

**Comment by jonparrott** [comment] 2018-04-30 17:44
This is a bug in pip, not on us. I'm closing this and opening a bug over there.

**Comment by tseaver** [comment] 2018-04-30 17:44
Looks like an issue with `wheel`:  the built wheel on PyPI has the following metadata:

```ini
Metadata-Version: 2.0
Name: google-cloud-vision
Version: 0.31.0
Summary: Google Cloud Vision API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Platform: Posix; MacOS X; Windows
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Operating System :: OS Independent
Classifier: Topic :: Internet
Requires-Dist: enum34
Requires-Dist: google-api-core[grpc] (>=0.1.0,<2.0.0dev)
```
https://github.com/pypa/wheel/issues/181 seems to describe this behavior, but claims that the fix was in `setuptools 36.2.0`

When  I build the wheel locally using up-to-date setuptools / wheel, it has correct metadata:

```bash
$ cd /path/to/gcp/vision
$ /tmp/gcp-5260/bin/python setup.py bdist_wheel
```

```ini
Metadata-Version: 2.1
Name: google-cloud-vision
Version: 0.31.0
Summary: Google Cloud Vision API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Platform: Posix; MacOS X; Windows
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Operating System :: OS Independent
Classifier: Topic :: Internet
Requires-Dist: google-api-core[grpc] (<2.0.0dev,>=0.1.0)
Requires-Dist: enum34; python_version < "3.4"
```

**Comment by tseaver** [comment] 2018-04-30 17:45
@jonparrott We might need to ensure that we `pip install --upgrade setuptools wheel` in our deployment step.

**Comment by jonparrott** [comment] 2018-04-30 17:51
Yeah, we'll need to do a follow-up publish on this. PR incoming for CI, then I'll get @crwilcox to release a new version.

**Comment by jonparrott** [comment] 2018-04-30 17:56
CI change done in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5265

We need to publish patch releases of:

- [ ] api-core
- [ ] vision
- [ ] language

**Comment by tseaver** [comment] 2018-04-30 17:59
We should update `language/setup.py` to use the newer `install_requires` format while we're at it.

**Comment by jonparrott** [comment] 2018-04-30 17:59
> We should update language/setup.py to use the newer install_requires format while we're at it.

Done in #5266

**Comment by jonparrott** [comment] 2018-04-30 22:17
The packages are all published and this should be resolved.

**Closed by jonparrott** 2018-04-30 22:17 UTC
Labels: packaging, priority: p0, type: bug
