### ISSUE TITLE
Bigquery: add ability to restrict Client class to particular dataset 

### ISSUE THREAD

**Issue by blainehansen** [GoogleCloudPlatform/google-cloud-python#6042] opened 2018-09-20 22:12 UTC
We have a multi-tenant approach, and want to be able to create multiple "binds" to different "databases", much like you can with traditional databases like postgres.

This started as a discussion in in the bigquery sqlalchemy dialect project:
https://github.com/mxmzdlv/pybigquery/issues/24
https://github.com/mxmzdlv/pybigquery/pull/25

Especially in this comment:
https://github.com/mxmzdlv/pybigquery/pull/25#issuecomment-423078408

It would elegantly solve all our problems to add the ability to restrict the `Client` class to a specific dataset.

This might be related to this existing issue, but it doesn't seem to be the priority.
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5183

We would be happy to put together a pull request for this if it's a welcome change.

Thanks!

**Comment by blainehansen** [comment] 2018-09-20 22:16
I should mention, that if there's another, similarly ergonomic way to achieve this kind of safe multi-tenancy, we're very open to it. The only other way I could think of was to create many google cloud "projects", but it seems like that would have a substantial maintenance overhead.

**Comment by tswast** [comment] 2018-09-21 19:31
Since `pybigquery` supports a credentials path (and this library supports arbitrary google-auth credentials to the `Client` constructor), I think that part is covered with some automation on your part for [creating service accounts](https://cloud.google.com/iam/docs/creating-managing-service-accounts#iam-service-accounts-create-python), [downloading keys](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys), and [granting the service account access to the dataset](https://cloud.google.com/bigquery/docs/managing-datasets#bigquery-update-dataset-acl-python). I don't think this is something we'd do at the client-library layer, since it covers several APIs and storing keys is application-specific.

Closing as a duplicate of #5183

**Closed by tswast** 2018-09-21 19:31 UTC
Labels: api: bigquery, type: feature request, type: question
