### ISSUE TITLE
Failing MD5 checksum with latest Storage release

### ISSUE THREAD

**Issue by shumin** [GoogleCloudPlatform/google-cloud-python#4227] opened 2017-10-19 21:49 UTC
Hey, not sure this directly related to this [merged PR](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3380) but after upgrading to latest storage release (1.5.0) all the download is keep failing and just throwing MD5 checksum exception.

My upload code:
```
blob = self.bucket.blob(filename)

with io.BytesIO() as f:
    with gzip.GzipFile(fileobj=f, mode='wb', compresslevel=9) as fgz:
        fgz.write(json.dumps(data).encode())
    blob.upload_from_file(f, size=f.tell(), rewind=True, content_type='application/json')

blob.cache_control = 'public, max-age=3600'
blob.content_encoding = 'gzip'
blob.patch()
blob.make_public()
```

Download code:
```
blob = self.bucket.get_blob(filename)
data = blob.download_as_string()
```

It all works with previous version but now throws exception in `download_as_string()` with message like this:
```
The X-Goog-Hash header indicated an MD5 checksum of:
  60oRCFTCzLBifVMH18gi4A==

but the actual MD5 checksum of the downloaded contents was:
  OrNQk+VCLH29Nlsbwn4BIA==
```

Is there anything can be done to resolve this issue?

Thanks

**Comment by dhermes** [comment] 2017-10-19 22:04
This is a duplicate of https://github.com/GoogleCloudPlatform/google-resumable-media-python/issues/34, but I'll leave it open since these are different repositories.

@shumin For now you can get around it by downgrading your version of `google-resumable-media`:

```
pip install google-resumable-media==0.2.3
```

This will work fine without having to modify the version of `google-cloud-storage`.

@mfschwartz is working on a fix as far as I know.

**Comment by dhermes** [comment] 2017-10-20 21:36
As of the release of https://pypi.org/project/google-resumable-media/0.3.1/ I am going to close this issue as "fixed".

There is still more to be done in `google-resumable-media`, but this at least fixes the reported issue.

**Closed by dhermes** 2017-10-20 21:36 UTC
Labels: api: storage
