### ISSUE TITLE
google.cloud.storage.bucket.Bucket  list_bucket list_blob max_results does not work as described

### ISSUE THREAD

**Issue by thefunkjunky** [GoogleCloudPlatform/google-cloud-python#2482] opened 2016-10-03 18:35 UTC
from a customer:

"list_bucket returns more values than max_results argument. Here is the python code...

bucket = Bucket(client, 'my-bucket-name')
blobs = bucket.list_blob(max_results=10, pageToken=None, fields="items/name,nextPageToken)

for b in blobs:
   printb.name

etc.... it returns all the blob names from the bucket, far more than max_results=10"

**Comment by dhermes** [comment] 2016-10-03 18:36
Indeed. This needs to be fixed ASAP.

Duplicate of #1467

**Closed by dhermes** 2016-10-03 18:36 UTC
Labels: storage
