### ISSUE TITLE
Vision: ImportError: No module named 'google.cloud.proto.vision'

### ISSUE THREAD

**Issue by aryan-solo** [GoogleCloudPlatform/google-cloud-python#4565] opened 2017-12-11 13:26 UTC
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1.     import google.cloud.proto.vision.v1.image_annotator_pb2 as pvv 

2. ubuntu 16.04
3. python 3.5`
4. code : 
from google.cloud import vision
import google.cloud.proto.vision.v1.image_annotator_pb2 as pvv 
import io

def makeReqListImage(imageStr):
	im_obj = pvv.Image(content = imageStr)
	return pvv.AnnotateImageRequest(image = im_obj, features = [{"type": "TEXT_DETECTION"}])

i am not getting any break , i guess there is some version conflict , need help!

**Comment by chemelnucfin** [comment] 2017-12-11 16:29
Could you please try
`import google.cloud.vision_v1.proto import image_annotator_pb2` instead?

**Comment by chemelnucfin** [comment] 2017-12-11 16:40
I will close this issue, but please feel free to reopen if it doesn't solve your problem.

**Closed by chemelnucfin** 2017-12-11 16:40 UTC
Labels: api: vision, type: question

**Comment by aryan-solo** [comment] 2017-12-11 16:49
you mean i should import 
import google.cloud.vision_v1.proto and  
import image_annotator_pb2 
separately ? 

i tried it ,
the error is 
ImportError: No module named 'image_annotator_pb2'

**Comment by dhermes** [comment] 2017-12-11 16:50
@aryan-solo IIUC, the issue is that you've used `vision.v1` when you should've used `vision_v1`

**Comment by aryan-solo** [comment] 2017-12-11 16:55
still the same issue.
ImportError: No module named 'google.cloud.proto.vision_v1'

**Comment by chemelnucfin** [comment] 2017-12-11 16:56
Please try reversing proto and vision_v1
`from google.cloud.vision_v1.proto import image_annotator_pb2`
I mistyped "from" as "import" in my first message.

**Comment by aryan-solo** [comment] 2017-12-11 16:57
i am sorry by using what you both said , its resolved thanks alot. 
now you can close this thread.

correct ->
import google.cloud.vision_v1.proto.image_annotator_pb2  as pvv
