### ISSUE TITLE
Installing with pip -t broken

### ISSUE THREAD

**Issue by StephenCarboni** [GoogleCloudPlatform/google-cloud-python#3806] opened 2017-08-14 13:49 UTC
1. OS type and version
`Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Rest of the questions are context sensitive.

If I install google-cloud in someEnv like so...

```bash

[stephen@localhost ~]$ python2.7 -m pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)

[stephen@localhost ~]$ virtualenv someEnv
New python executable in /home/stephen/someEnv/bin/python2.7
Also creating executable in /home/stephen/someEnv/bin/python
Installing setuptools, pip, wheel...done.

[stephen@localhost ~]$ source someEnv/bin/activate
(someEnv) [stephen@localhost ~]$ python2.7 -m pip install google-cloud --upgrade
# ...snip...
(someEnv) [stephen@localhost ~]$ ls someEnv/lib/python2.7/site-packages/google
api  auth  cloud  gapic  gax  iam  logging  longrunning  oauth2  protobuf  resumable_media  rpc  type

```
Those folders look good, right?

Now, lets say I want to use `cloud` with AppEngine Standard. You would normally use `-t some_target` with pip and vendor `some_target` in your appengine_config.py, right?

```bash
[stephen@localhost ~]$ mkdir myAppEngineProject
[stephen@localhost ~]$ python2.7 -m pip install google-cloud -t myAppEngineProject/lib --upgrade
# ...snip...
[stephen@localhost ~]$ ls myAppEngineProject/lib/google
protobuf
```

So only protobuf makes it through. Without the `--upgrade` switch, this happens:

```bash

[stephen@localhost ~]$ rm myAppEngineProject/lib/ -rf
[stephen@localhost ~]$ python2.7 -m pip install google-cloud -t myAppEngineProject/lib
# ...snip...
Target directory /home/stephen/myAppEngineProject/lib/google already exists. Specify --upgrade to force replacement.
[stephen@localhost ~]$ ls myAppEngineProject/lib/google
api  auth  cloud  gapic  gax  iam  logging  longrunning  oauth2  resumable_media  rpc  type

```
So now `protobuf ` is missing and pip just wants to wipe the whole google dir when upgrading, even from a fresh install.

This is also an issue with just wanting to install `google-cloud-pubsub`, guess other sub-projects might be affected.

**Comment by lukesneeringer** [comment] 2017-08-14 14:23
Summoning @jonparrott, who I am hoping will have some insight on this. :-)

**Comment by lukwam** [comment] 2017-08-18 20:25
I'm having the same issue.

My `requirements.txt` looks like:

```
google-endpoints==2.1.2
google-endpoints-api-management==1.1.3
google-cloud-datastore==1.2.0
```

I start out with an empty `lib/` dir in my project.

I run `pip install -r requirements.txt -t lib/`, I get the warning:

`Target directory /path/to/app/lib/google already exists. Specify --upgrade to force replacement.`

And it looks like everything but `protobuf` is installed.

```
> ls -1 lib/google
__init__.py
__init__.pyc
api/
auth/
cloud/
gapic/
gax/
logging/
longrunning/
oauth2/
rpc/
type/
```

Then I try to manually add protobuf with `pip install -t lib/ protobuf` it gives me errors:

```
Target directory /path/to/app/lib/six.pyc already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/pkg_resources already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/easy_install.py already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/setuptools-36.2.7.dist-info already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/six-1.10.0.dist-info already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/six.py already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/easy_install.pyc already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/setuptools already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/google already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/protobuf-3.4.0-py2.7-nspkg.pth already exists. Specify --upgrade to force replacement.
Target directory /path/to/app/lib/protobuf-3.4.0.dist-info already exists. Specify --upgrade to force replacement.
```

and if I do it again with `--upgrade` it replaces the entire directory.

```
> ls -1 lib/google
protobuf/
```

Is there a workaround?

**Comment by jonparrott** [comment] 2017-08-18 20:38
You can try specifying protobuf directly in your requirements.txt.

**Comment by lukwam** [comment] 2017-08-19 00:41
If you install protobuf into a "lib" directory and there is already a "google" subdirectory in there, the installation of protobuf will fail, unless you add the `--upgrade` flag, in which case it will blow away all the contents of the "google" directory and will replace it with "google/protobuf".

**Comment by bbayles** [comment] 2017-08-26 19:27
This issue makes creating a stable environment across test runs difficult. Ideally you'd want to pin all your requirements to a known version, but with this issue you can't pin `protobuf`.

**Comment by jonparrott** [comment] 2017-10-25 21:29
Closing this in favor of the umbrella issue around GAE standard support #1893.

**Closed by jonparrott** 2017-10-25 21:29 UTC
Labels: core, packaging, type: question

**Comment by LeKristapino** [comment] 2019-03-13 01:05
@theacodes I can't find the solution in the issue you have referenced. I have this exact issue with installing `google-cloud-vision==0.36.0` with `-t` flag. Could you post a solution regarding this specific problem here, please?

**Comment by amarjandu** [comment] 2019-05-15 19:53
@LeKristapino @theacodes was this ever resolved? Running on python 3.6.5

**Comment by tseaver** [comment] 2019-05-15 20:08
@amarjandu Seems solved to me:

```bash
$ mkdir /tmp/gcp/3806
$ python3.6 -m pip install -t /tmp/gcp/3806/ google-cloud-vision
...
Installing collected packages: setuptools, six, protobuf, googleapis-common-protos, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, pytz, chardet, idna, certifi, urllib3, requests, grpcio, google-api-core, google-cloud-vision
Successfully installed cachetools-3.1.0 certifi-2019.3.9 chardet-3.0.4 google-api-core-1.11.0 google-auth-1.6.3 google-cloud-vision-0.36.0 googleapis-common-protos-1.5.10 grpcio-1.20.1 idna-2.8 protobuf-3.7.1 pyasn1-0.4.5 pyasn1-modules-0.2.5 pytz-2019.1 requests-2.21.0 rsa-4.0 setuptools-41.0.1 six-1.12.0 urllib3-1.24.3
$ PYTHONPATH="/tmp/gcp/3806/" python3.6 
Python 3.6.7 (default, Oct 22 2018, 11:30:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import vision
>>> dir(vision)
['ImageAnnotatorClient', 'ProductSearchClient', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'absolute_import', 'enums', 'types']
```

**Comment by amarjandu** [comment] 2019-05-15 20:29
@tseaver  i was working with this requirements.txt file https://github.com/HumanCellAtlas/data-store/blob/master/requirements.txt

the command was
`python3 -m pip install -t dependencies/lib/python3.6/site-packages/ -r requirements.txt`
i still see the warning for
`WARNING: Target directory /data-store/dependencies/lib/python3.6/site-packages/google already exists. Specify --upgrade to force replacement.`

and confirmed with
```
bash-4.2# ls /data-store/dependencies/lib/python3.6/site-packages/google
api  api_core  auth  cloud  logging  longrunning  oauth2  resumable_media  rpc	type
```

**Comment by olivier-heurtier-idemia** [comment] 2019-09-25 10:32
I still have this issue with Python 3.5 and pip 19.2.3. I'm installing sphinxcontrib packages and not Google modules.
Example:
```
pip install -t test  sphinxcontrib-plantuml
ls test/sphinxcontrib
applehelp  devhelp  htmlhelp  jsmath  plantuml.py  __pycache__  qthelp  serializinghtml
pip install -U -t test  --no-deps sphinxcontrib-plantuml
ls test/sphinxcontrib
plantuml.py  __pycache__
```
The directory `test/sphinxcontrib` is cleared by the second installation.
(This is not specific to the sphinxcontrib-plantuml module, I tested also with others)

@theacodes, is it possible to reopen this issue?
