### ISSUE TITLE
PubSub: Unexpected exception was thrown in a helper thread

### ISSUE THREAD

**Issue by shileiyu** [GoogleCloudPlatform/google-cloud-python#4436] opened 2017-11-22 01:06 UTC
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b8cde46273fdf6760d8d0bad5329f02fdb81dca8/pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py#L246-L251

Does the exception here was supposed to throw outside?  If so it would make python interpreter output annoying exception trackback. Any reason to do so?

I feel like here should be changed to following code:
```python
except Exception as exc:
    self._policy.on_exception(exc)
    self.stop_consuming()
```

**Comment by dhermes** [comment] 2017-11-28 22:58
After understanding the purpose of #4445, it seems this issue is a duplicate of #4463.

Thanks for filing (and sending the PR) @shileiyu!

**Closed by dhermes** 2017-11-28 22:58 UTC
Labels: api: pubsub, status: investigating
