### ISSUE TITLE
Deadlock in cloud-logging 

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/google-cloud-python#2780] opened 2016-11-30 09:26 UTC
See this traceback (these are the only two threads ever created):
```
Thread 0x00007f7aa5a6c700 (most recent call first):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 804 in acquire
  File "/usr/local/lib/python3.5/logging/__init__.py", line 853 in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1487 in callHandlers
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1425 in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1415 in _log
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1279 in info
  File "/usr/local/lib/python3.5/site-packages/oauth2client/transport.py", line 179 in new_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 274 in _do_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 244 in _make_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 350 in api_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/_http.py", line 165 in write_entries
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/logger.py", line 451 in commit
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 80 in _run
  File "/usr/local/lib/python3.5/threading.py", line 862 in run
  File "/usr/local/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/local/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f7ab4c81700 (most recent call first):
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 136 in enqueue
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 171 in send
  File "/usr/local/lib/python3.5/site-packages/google/cloud/logging/handlers/handlers.py", line 93 in emit
  File "/usr/local/lib/python3.5/logging/__init__.py", line 855 in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1487 in callHandlers
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1425 in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1415 in _log
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1279 in info
  File "/usr/local/lib/python3.5/site-packages/oauth2client/transport.py", line 179 in new_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 274 in _do_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 244 in _make_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/_http.py", line 350 in api_request
  File "/usr/local/lib/python3.5/site-packages/google/cloud/pubsub/_http.py", line 450 in subscription_acknowledge
  File "/usr/local/lib/python3.5/site-packages/google/cloud/pubsub/subscription.py", line 354 in acknowledge
 ```

We have configured cloud-logging globally like this:
```
    import google.cloud.logging
    from google.cloud.logging.handlers import CloudLoggingHandler
    import logging
    client = google.cloud.logging.Client(use_gax=False)
    handler = CloudLoggingHandler(client, name=logger_name)
    logger = logging.getLogger()
    logger.addHandler(handler)
```

Whenever the background-threads causes a log-call itself (here: `oauth2client/transport.py line 179`) there is a chance for a deadlock.

**Comment by daspecster** [comment] 2016-11-30 14:57
Thanks for reporting @flunderpero!

@waprin, have you run into this before?

**Comment by waprin** [comment] 2016-11-30 19:42
Nope, will look into this, thanks for report.

**Comment by waprin** [comment] 2016-12-15 23:18
Hey, 

Sorry for not addressing this issue sooner, deadlock in the title made me think it was trickier than it was.

The problem is you are trying to attach the handler to the root logger. But then logging code in the handlers path (including oauth2client) ends up recursively hitting itself. Even if there was no deadlock, you would hit an infinite recursion.

There is a function in `google.cloud.logging.handlers` called `setup_logging` specifically designed to attach the logging handlers to the root logger, while excluding loggers in library path, including `oauth2client` (in fact that's pretty much the only thing the function does, besides all reattaching the stdout loggers).

So you can just fix the issue by using the snippet I have there:

```
        import logging
        import google.cloud.logging
        from google.cloud.logging.handlers import CloudLoggingHandler

        client = google.cloud.logging.Client()
        handler = CloudLoggingHandler(client)
        google.cloud.logging.setup_logging(handler)
        logging.getLogger().setLevel(logging.DEBUG)
```

Unless the above doesn't solve your problem, I think we can close the issue, although I'd be curious if there is a way to improve the documentation so that it was clearer that you should use that function.

**Comment by waprin** [comment] 2016-12-15 23:18
@flunderpero ^^

**Comment by waprin** [comment] 2016-12-17 00:28
By the way, forgot that I added another helper method that makes the code even simpler:

```
import logging
import google.cloud.logging

client = google.cloud.logging.Client()
client.setup_logging(logging.INFO) # uses client.get_default_handler()
```

There also might some ways to avoid the problem you ran into even with the code you wrote, but I am still investigating.

**Comment by lukesneeringer** [comment] 2017-02-28 20:55
@waprin Can you provide me some guidance on this issue? Do I need to leave it open? Is there something we intend to change in the future, or is the correct answer to provide a workaround.

**Comment by flunderpero** [comment] 2017-02-28 20:59
@waprin: Your solution worked.

In the mean-time we just went to logging JSON-formatted messages directly to STDOUT (we're using GKE) and that works like a charm - no more background-threads (all of our application code is single-threaded on purpose).

Thanks for the help!

**Comment by waprin** [comment] 2017-02-28 21:07
@flunderpero cool glad that worked...if you were on GKE then that default handler is supposed to pick up a GKE handler that writes in the expected JSON format which captures things like severity, but maybe you don't care.

@lukesneeringer there is no bug, it's just if you don't read the docs carefully you can use the handler incorrectly. Jon had some ideas about how we could use logging filters to make it impossible to use incorrectly but I haven't tried yet. That would be a separate issue so I think we can close for now.

**Closed by waprin** 2017-02-28 21:07 UTC
Labels: API: logging, Priority: P2+, Status: Acknowledged

**Comment by waprin** [comment] 2021-02-01 19:05
@JustinBeckwith saw you just assigned me on 3 closed issues,  but I left Google in 2018 so no longer work  on these libraries. I'm guessing these actions were done on your part by a script, and these issues are closed anyway so easy to filter out, but just letting you know. Incidentally I still use these libraries so hoping they stay in good shape, just not a good assignee for issues.Hope all is good!
