### ISSUE TITLE
Record leaf nodes support

### ISSUE THREAD

**Issue by vigbk** [GoogleCloudPlatform/google-cloud-python#2943] opened 2017-01-18 12:54 UTC
Python version - 2.7.13
Google-cloud-bigquery - 0.22.1

I am trying to insert data using the big query python client library. I am getting an error that record leaf types are not supported. The schema contains nested records that are repeatable. Is there a way using the client to insert nested repeatable records ?

my schema is as follows: 
<img width="641" alt="screen shot 2017-01-18 at 6 23 15 pm" src="https://cloud.githubusercontent.com/assets/6189632/22064822/4938bf16-ddab-11e6-93e4-d5d7c943a660.png">

**Comment by daspecster** [comment] 2017-01-18 13:47
Thanks for reporting @vigbk!

Do you have some example code/stacktrace?

@tseaver is this kind of related to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2354?

**Comment by vigbk** [comment] 2017-01-18 14:37
@daspecster Here is an excerpt of the code I used
```python
from google.cloud import bigquery
import os
import json
from datetime import datetime


def transform(item):
    newItem = {"insertId": getUUID(), "json": item}
    return newItem

def getTemplateSuffix():

    utcDate =  datetime.utcnow().strftime("%Y%m%d")
    templateSuffix = "_" + utcDate
    return templateSuffix

def uploadToBigQuery(data):

     rowData = json.loads(data)



     os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "credentials.json"

     # Instantiates a client
     bigquery_client = bigquery.Client("logs")

     dataset = bigquery_client.dataset("eventlogs")
     table = dataset.table("events")

     # Reload the table to get the schema.
     table.reload()

     rows = [rowData]
     print(rows)
     errors = table.insert_data(rows=rows, template_suffix=getTemplateSuffix())

     if not errors:
         print('Loaded 1 row into {}:{}'.format(dataset, table))
     else:
         print('Errors:')
         print(errors)


data = '{"user_dim":{"user_id":"12345","user_properties":[{"key":"subdomain_id","value":{"string_value":"custom.zendesk.com"}}]},"event_dim":{"date":"20170116","category":"ALERT","name":"NUMBER_NOT_A_MOBILE","timestamp_micros":1484580530384000,"params":[{"key":"network","value":{"string_value":"Singapore"}},{"key":"country","value":{"string_value":"Singapore"}}]}}'

uploadToBigQuery(data) 
```

**Comment by lukesneeringer** [comment] 2017-02-28 20:36
Is this a duplicate of #2951? (It seems like it is, but I am hesitant to close without being sure.)

**Comment by dhermes** [comment] 2017-03-01 23:31
@tswast Can you confirm / deny the duplicateness?

**Comment by tswast** [comment] 2017-03-01 23:41
These two issues look like duplicates to me, too.

**Comment by lukesneeringer** [comment] 2017-03-02 22:11
Okay. I marked the other one as important, and am going to close this one for personal sanity / tracking. :-)

**Closed by lukesneeringer** 2017-03-02 22:11 UTC
Labels: API: bigquery, Priority: P1, Status: Acknowledged, Type: Bug
