### ISSUE TITLE
datastore: No way to exclude_from_indexes new properties on updated entities

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-python#3508] opened 2017-06-19 18:36 UTC
When loading an `Entity` from the datastore and updating it, there is no way to exclude new attributes from being indexed, since the only public API for setting `exclude_from_indexes` is on the `Entity` constructor. To work around this, I am currently setting `entity._exclude_from_indexes = (...)` in my code, which is not a "public" API.

Example:

```python
client = google.cloud.datastore.Client()
key = client.key('SomeEntityKey')
entity = google.cloud.datastore.Entity(key, exclude_from_indexes=('foo', 'bar'))
entity['foo'] = 'foo'
print 'entity.exclude_from_indexes:', entity.exclude_from_indexes
client.put(entity)

entity2 = client.get(entity.key)
print 'entity2.exclude_from_indexes:', entity2.exclude_from_indexes
entity2['bar'] = 'bar'
client.put(entity2)
```

Output:

```
entity.exclude_from_indexes: frozenset(['foo', 'bar'])
entity2.exclude_from_indexes: frozenset([u'foo'])
```

This is actually "expected" based on how the Datastore works, however, in the code sample above, there should be some way for me to put the entity back, without copying it into a brand new `Entity`.

Tested using:

* Mac OS X 10.11.6
* Python 2.7.10
* The following Google packages:
```
gapic-google-cloud-datastore-v1==0.15.3
google-auth==1.0.1
google-auth-httplib2==0.0.2
google-cloud-core==0.24.1
google-cloud-datastore==1.0.0
google-cloud-storage==1.1.1
google-gax==0.15.13
google-resumable-media==0.0.2
googleapis-common-protos==1.5.2
proto-google-cloud-datastore-v1==0.90.4
```

**Comment by lukesneeringer** [comment] 2017-08-07 20:22
@evanj Sorry, I do not completely follow. Would you be willing to give me some example code with the actual expected behavior?

**Comment by evanj** [comment] 2017-08-07 20:44
I would have expected that the "excluded from indexes" attributes would be persistent, but they don't seem to be. That is, given the example code above, I expect the following output:

```
entity.exclude_from_indexes: frozenset(['foo', 'bar'])
entity2.exclude_from_indexes: frozenset([u'foo', u'bar'])
```

And that both `foo`, and `bar` are excluded from indexing. In fact, the way they API is specified, there is no "public" way for me to load an entity from the datastore, and add a new unindexed property to it.

I'd like some way to do the following using a publicly documented api:

```python
existing_entity = client.get(entity.key)
existing_entity['some_new_attribute'] = 'bar'
existing_entity.add_exclude_from_indexes('some_new_attribute')
```

The way the API currently works, the attribute `'some_new_attribute'` *will* be indexed, unless I create a *new* entity using the `Entity` constructor.

**Comment by lukesneeringer** [comment] 2017-08-07 20:46
@evanj Thank you. I understand now.

**Comment by lukesneeringer** [comment] 2017-08-07 21:34
Hi @evanj,
I tested this today, and I can not seem to reproduce (note that I am on 1.2.0):

```python
>>> from google.cloud import datastore
>>> client = datastore.Client()
>>> key = client.key('Parent', 'foo')
>>> entity = datastore.Entity(key, exclude_from_indexes=('foo', 'bar'))
>>> entity['foo'] = 'foo'
>>> client.put(entity)
```

And then I pulled it back down:

```python
>>> entity2 = client.get(key)
>>> entity2.exclude_from_indexes
frozenset({'foo'})
```

Additionally, I stepped through [the code where it is assigned](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/helpers.py#L146-L148) in PDB, and verified it.

For now, I am going to close this as working as intended, but if you can give me a reproduction case (on 1.2.0 if possible), I would be happy to investigate further.

**Comment by ernestoalejo** [comment] 2017-08-07 22:09
The issue is when creating a new property in a previously created entity. For example:

```
>>> entity3 = client.get(key)
>>> entity3['baz'] = 'baz'
>>> # There is no way to make "baz" unindexed
>>> entity3.put()
```

**Comment by lukesneeringer** [comment] 2017-08-08 01:58
Ohhh, I mis-understood. Okay, I can put that in.

**Comment by ernestoalejo** [comment] 2017-08-08 04:26
I have found this issue in both ways (add and remove from exclude_from_indexes). I use this library in scripts to make background changes to all entities; e.g. to reindex a field originally tagged with noindex, to rename fields, etc.

**Comment by lukesneeringer** [comment] 2017-08-08 04:44
I am going to sleep on it, but rather than add a bunch of add and remove methods, I am inclined to just change `exclude_from_indexes` to a `set` rather than a `frozenset`.

**Comment by evanj** [comment] 2017-08-08 13:44
That would definitely solve the problem for me. I'm currently just assigning to `_exclude_from_indexes` which works, but I don't like using private APIs in third-party code. Thanks!

**Closed** 2017-08-08 19:37 UTC
Labels: api: datastore

**Comment by chrissyast** [comment] 2021-03-17 10:10
@lukesneeringer Does this work for nested properties?

I am doing     
```python
entity.exclude_from_indexes = {"cloud_storage","token"}  # also tried with [], also tried cloud_storage.token, as per
# https://github.com/googleapis/google-cloud-python/issues/1206#issuecomment-166440080
    datastore_client.put(entity)
    entity.update(
            {
                "cloud_storage":{
                    "provider": provider,
                    "token": token, # token is over 1500 bytes
                }
            }
        )  # also tried entity["cloud_storage"] = {...}
    datastore_client.put(entity)
```
but I still get `The value of property "token" is longer than 1500 bytes.`
