### ISSUE TITLE
Vision Beta: PDF/TIFF document detection returns with a None type error for some pdf

### ISSUE THREAD

**Issue by arvindnrbt** [GoogleCloudPlatform/google-cloud-python#5671] opened 2018-07-23 06:36 UTC
I've been testing the beta pdf/tiff detection from vision API, so far there has been one pdf which throws this error, 

`google.api_core.exceptions.GoogleAPICallError: None Error in extracting images from PDF file gs://xxstorage/yy.pdf`

From the error it seems to me that google internally extracts each page as an image and then processes the document_text_detection on each page. 

When I do this manually, (i.e extracting each page and send a HTTP request/ batch request.) this is working but maybe because of the added HTTP overhead, a document with 20 pages takes about 12 mins to process which is quite much. Any suggestions for me? Why do I get this error when extracting images while I can do it with no problem?

**Comment by arvindnrbt** [comment] 2018-07-26 09:33
Any update on this?

**Comment by arvindnrbt** [comment] 2018-08-13 07:55
So, we've gone forward and extracted images from the pdf and used document_text_detection on each of those images, now we get a response of <type AnnotateImageResponse>. Our codebase is getting a little redundant since we have to deal with the same functionality in two different ways as the beta APIs have a JSON file as response and the latter is producing the AnnotateImageResponse object. I think there's no way to instantiate this class from a JSON as of now. Is there any other way to unify this process so that we can remove this redundancy? [i.e, converting AnnotateImageResponse to JSON or vice versa?]

**Comment by zinjiggle** [comment] 2018-08-15 22:08
Hi Arvind:

What is your pdf file?

**Comment by arvindnrbt** [comment] 2018-08-16 06:04
I can see the difference now, It is noticeably faster. Many thanks for that. But I still get the none type error for some pdf documents. My pdf is a redacted contract agreement, If you do want to have a look at it, I can look into what I can share with you.

**Comment by arvindnrbt** [comment] 2018-08-16 11:37
@zinjiggle Sent you a mail with the document. And what does GAed mean? Is there a google group or something of sorts where I can get latest info on Cloud vision?

**Comment by crwilcox** [comment] 2018-08-16 15:39
@arvindnrbt GA refers to a launch stage for Google Cloud products. https://cloud.google.com/terms/launch-stages

**Comment by arvindnrbt** [comment] 2018-08-17 08:49
Thanks :)

**Comment by Arvin6** [comment] 2018-08-18 14:55
Did you find out what the problem is with the pdf I sent you? This is just for our clarity to know if we could identify which pdf is going to fail beforehand. 
Thank you for your swift response 😄

**Comment by zinjiggle** [comment] 2018-08-28 22:32
Arvin:

your pdf doc's problem should be fixed now. Would you like to try it out again to verify?

It is actually not clear to me what is the problem of the pdf file itself. But we improved our pipeline for image extraction and it should work for all types of pdf files.

If you find out some pdf file which does not work. Feel free to send me those files and we will immediately process your request.

**Comment by arvindnrbt** [comment] 2018-08-29 09:19
Hello @zinjiggle I did verify it again but it didn't work. I'm getting the same error.

```
Version: google-cloud-vision==0.33.0

[2018-08-29 09:10:03,024: ERROR/ForkPoolWorker-2] None Error in extracting images from PDF file gs://<bucket>/<directory>/<file>.pdf
```

**Comment by jianatldd** [comment] 2018-09-13 13:56
Hi: @zinjiggle 
 I have same type of error for any scanned PDF or TIFF file from Xerox Multifunction Printer. I loaded the TIFF file into window Paint program and Save as another TIFF file. it works fine
I attach these files for you to look at 
Scanned from a Xerox Multifunction Printer001.tif    (one page ) not working 
Scanned from a Xerox Multifunction Printer(6).pdf  (multi pages ) not working
saved from Paint.tif    working
[Scanned from a Xerox Multifunction Printer(6).pdf](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2379581/Scanned.from.a.Xerox.Multifunction.Printer.6.pdf)
[2 tiff files.zip](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2379585/2.tiff.files.zip)

**Comment by normster** [comment] 2018-09-14 07:27
I'm having a similar issue- when I call document text detection on a .pdf file it fails but when I export as .jpg and then call document text detection it succeeds. Files attached below:
![kdl-vol1-033](https://user-images.githubusercontent.com/6687910/45535985-f8be0880-b7b4-11e8-90c5-e8297e968ccd.jpg)
[kdl-vol1-033.pdf](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2382368/kdl-vol1-033.pdf)

**Comment by jianatldd** [comment] 2018-09-14 15:38
I found out what is the problem for my scanned document, it is because of default scan resolution is only 200dpi, when i change to 300dpi it works.
however, I believe google vision should allow lower dpi to go through OCR, a lot of scanned PDF coming from fax, the standard fax resolution is only 204x98,  fine mode 204x196 dpi, my email to fax service do OCR on all incoming fax automatically, the OCR result seems ok for 99% of documents.

**Comment by AyKarsi** [comment] 2018-09-18 14:31
We had a very similar problem using the node library. (Error: Error in extracting images from PDF file gs://..) and spent a good day trying to figure out the reason. We were uploading the files using gzip compression.   after disabling gzip compression, it suddenly works.

**Comment by tseaver** [comment] 2018-09-18 20:05
I'm going to close the issue here, as it doesn't seem related to the `google-cloud-vision` library.  Please feel free to keep working on the pipeline stuff here, though.

**Closed by tseaver** 2018-09-18 20:05 UTC
Labels: api: vision, backend, type: question

**Comment by arvindnrbt** [comment] 2018-09-21 17:19
I got this issue back again. @zinjiggle I've sent you one more pdf by mail. Please let us know why the issue occurs.

**Comment by zinjiggle** [comment] 2018-09-26 21:33
@arvindnrbt, @normster, @jianatldd :
Your problem with the pdf issue should have been fixed. Would you mind try the API again for your pdf doc to see?

@jianatldd:

The problem of handling the tiff you provided is still ongoing. But we know the reason, it is due to your tiff file is using old jpeg compression method
https://forums.wxwidgets.org/viewtopic.php?t=35625

We are still working on it as the code handling this type of old jpeg is deprecated and not safe. 

I believe we can handle your pdf file without any problem now. So if the pdf issue is solved, are you OK to use that instead of sending us that tiff file with old jpeg compression format?

**Comment by jianatldd** [comment] 2018-09-29 12:03
Thanks. We are using this service to process customer submit forms. So there is no way to control what format is. I just test these forms from my scanner (Xerox copyer) I guess these machines are very commonly used. I think this service should support as much format as you can. Because a lot of usage case is like me. The source of image cannot be controlled. However. In my case. PDF is most important.

**Comment by zinjiggle** [comment] 2018-10-10 17:56
@jianatldd:

Glad to mention that the pipeline is upgraded thanks to your information.

It should be able to support your special TIFF file now. Would you like to try?

So far, all issues in this thread above should be already fixed. Feel free to add more issues here if you meet one.

**Comment by jianatldd** [comment] 2018-10-29 17:11
@zinjiggle 
I have just tested tiff files from Xerox Printer/Scanner, all works Thank you.

**Comment by jianatldd** [comment] 2018-10-29 17:22
one more issue I don't know if should belong to here. PDF processing does not include PDF field values if filled in.
