### ISSUE TITLE
google cloud logging delete log entries issue with requested entity was not found

### ISSUE THREAD

**Issue by daiyueweng** [GoogleCloudPlatform/google-cloud-python#3155] opened 2017-03-16 10:21 UTC
Hi, I am testing the code at [snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/logging/cloud-client/snippets.py) to write, list and delete log entries. When running `delete_logger`, some errors were generated,

```python
Traceback (most recent call last):
  File "/home/daiyue/.local/lib/python3.5/site-packages/google/gax/retry.py", line 120, in inner
    return to_call(*args)
  File "/home/daiyue/.local/lib/python3.5/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/home/daiyue/.local/lib/python3.5/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/home/daiyue/.local/lib/python3.5/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, Requested entity was not found.)>
```
when running `write_entry` and `list_entries`, there was no any problem. I am wondering how to fix the issue.

I am running the code on `Linux Mint 18.1` with `Python 3.5.2` and latest `Google Cloud SDK`.

many thanks

**Comment by daspecster** [comment] 2017-03-16 14:25
@daiyueweng, are you just running that `snippets.py` file and that error is occuring?

My guess is that the logger hasn't been created by the time you're calling `delete_logger`.

Could you give some steps to reproduce?

**Comment by daiyueweng** [comment] 2017-03-16 14:43
@daspecster I found out the issue is probably due to one cannot delete multiple logs at once? My code snippet is as follows,

```python
def log(logger_name, sev, msg):
    try:
        if sev.value >= LOG_LEVEL.value:
            logging_client = logging.Client()
            logger = logging_client.logger(logger_name)

            if type(msg) is str:
                logger.log_text(msg, severity=sev.name)
            elif type(msg) is dict:
                logger.log_struct(msg, severity=sev.name)
    except Exception:
        print("Could not write log entries to {}".format(logger_name))


def batch_log(logger_name, sevs, msgs):
    try:
        logging_client = logging.Client()
        batch_logger = logging_client.logger(logger_name).batch()

        for msg, sev in zip(msgs, sevs):
            if sev.value >= LOG_LEVEL.value:
                if type(msg) is str:
                    batch_logger.log_text(msg, severity=sev.name)
                elif type(msg) is dict:
                    batch_logger.log_struct(msg, severity=sev.name)

        batch_logger.commit()
    except Exception:
        print("Could not batch log entries to {}".format(logger_name))


def list_entries(logger_name):
    logging_client = logging.Client()
    logger = logging_client.logger(logger_name)

    return [entry for entry in logger.list_entries()]


def delete_logger(logger_name):
    logging_client = logging.Client()
    logger = logging_client.logger(logger_name)

    logger.delete()

def test_gce_logging():
    # Structured log message
    d = dict()
    d["file"] = get_file_name()
    d["function"] = get_function_name()
    d["line"] = get_line_number()
    d["msg"] = "critical error msg"
    d["detail"] = "the critical error message detail"
    log("simple_struct_log_test", Severity.CRITICAL, json.dumps(d))

    # Simple text messages
    log("simple_text_log_test", Severity.CRITICAL, "Critical")
    log("simple_text_log_test", Severity.ERROR, "Error")
    log("simple_text_log_test", Severity.WARNING, "Warning")
    log("simple_text_log_test", Severity.INFO, "Info")
    log("simple_text_log_test", Severity.DEBUG, "Debug")

    # Batch text messages
    batch_log("batch_text_log_test",
              [Severity.ALERT, Severity.CRITICAL, Severity.DEFAULT, Severity.DEBUG, Severity.EMERGENCY],
              ["Alert", "Critical", "Default", "Debug", "Emergency"])

    # Batch struct messages
    batch_log("batch_struct_log_test",
              [Severity.DEFAULT, Severity.DEBUG, Severity.INFO, Severity.NOTICE, Severity.WARNING],
              [{'file': get_file_name(), 'function': get_function_name(), 'line': get_line_number(),
                'msg': 'default msg', 'detail': 'default msg detail'},
               {'file': get_file_name(), 'function': get_function_name(), 'line': get_line_number(),
                'msg': 'debug msg', 'detail': 'debug msg detail'},
               {'file': get_file_name(), 'function': get_function_name(), 'line': get_line_number(),
                'msg': 'info msg', 'detail': 'info msg detail'},
               {'file': get_file_name(), 'function': get_function_name(), 'line': get_line_number(),
                'msg': 'notice msg', 'detail': 'notice msg detail'},
               {'file': get_file_name(), 'function': get_function_name(), 'line': get_line_number(),
                'msg': 'warning msg', 'detail': 'warning msg detail'}
               ])

    # Delete loggers
    delete_logger('simple_struct_log_test')
    delete_logger('simple_text_log_test')
    delete_logger('batch_text_log_test')
    delete_logger('batch_struct_log_test')

if __name__ == '__main__':
    test_gce_logging()
```

**Comment by daspecster** [comment] 2017-03-16 15:12
Yeah, the service does not appear to support [deleting a list of loggers](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.logs/delete).

It might be a nice feature to add! I'm not sure how common of a use case that would be though.

I'm going to close this since it sounds like it's working for you. Feel free to reopen if there's something still not working or more in question.

**Comment by daiyueweng** [comment] 2017-03-16 16:31
@daspecster I did a few more tests and sometimes even a logger is deleted as seen from the `Stackdriver logging console`. I still got the errors,

```python
Traceback (most recent call last):
  File "/home/daiyue/.local/lib/python3.5/site-packages/google/gax/retry.py", line 120, in inner
    return to_call(*args)
  File "/home/daiyue/.local/lib/python3.5/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/home/daiyue/.local/lib/python3.5/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/home/daiyue/.local/lib/python3.5/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, Requested entity was not found.)>
```

**Comment by daspecster** [comment] 2017-03-16 20:23
@waprin any ideas?

**Comment by waprin** [comment] 2017-03-16 20:28
@daiyueweng @daspecster trying to wrap my head around the issue. Did you delete the logger and then have some entries written and then you're surprised it gest deleted? Hopefully you can clarify the question more.

In general it's really useful to keep in mind with Logging and Monitoring that many API calls are eventually consistent. Any sort of write, update, or delete won't always be reflected right away, it can take up to several minutes. This is especially true if you don't write to a specific MonitoredResource and instead use `global`, which this library uses by default (currently a feature request from me to make it easier to write to a MonitoredResource).

**Comment by daiyueweng** [comment] 2017-03-17 10:38
@waprin What I think about `Stackdriver logging` based on my experience of using its `Python API`, is the delay between writing log entries and shown on the `Log Viewer` is severe。 Yes I am using `global` resource, and I am wondering how to shorten the delay that makes it in near real time monitoring. How to use monitored resources, and I can only see [Monitored Resources and Services](https://cloud.google.com/logging/docs/api/v2/resource-list#resource-indexes) that lists monitor resource types and services to resources mappings.

**Comment by lukesneeringer** [comment] 2017-03-17 18:24
> What I think about Stackdriver logging based on my experience of using its Python API, is the delay between writing log entries and shown on the Log Viewer is severe

How are you defining "severe"? Seconds?  Minutes? An hour?

**Comment by daiyueweng** [comment] 2017-03-23 17:24
@lukesneeringer I am more interested in how to use a specific resource type by using the `Python` API, e.g. under `Google Project/project_id`.

**Comment by lukesneeringer** [comment] 2017-03-23 22:11
Huh?

**Comment by daiyueweng** [comment] 2017-03-23 22:29
@lukesneeringer do you know how to use `Monitored Resource` in `Python`?

**Comment by lukesneeringer** [comment] 2017-03-23 22:38
I am not familiar with the details, no. But at this point I also do not know what bug this ticket is reporting.

**Closed** 2017-03-23 23:16 UTC
Labels: api: logging, type: question
