### ISSUE TITLE
Logging in GKE is not using the ContainerEngineHandler

### ISSUE THREAD

**Issue by arthurdarcet** [GoogleCloudPlatform/google-cloud-python#3622] opened 2017-07-18 16:44 UTC
The `KUBERNETES_SERVICE` environment variable is not set in a pod running on GKE, so `ContainerEngineHandler` never actually gets selected as the default handler [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/client.py#L307)

This means all the logs go directly to the "Global" section of the Logging tab in the GCloud console, instead of being parsed by the fluentd pod running on the host, and being routed to the right "GKE > *cluster* > *container name*" section. And of course no pod/host/… metadata is added to the log.

I think the checked variable should read `KUBERNETES_SERVICE_HOST` <del>but i did not open a pull request because `ContainerEngineHandler` does not work either: When I manually add a `ContainerEngineHandler` handler to the logging configuration, the logging interface at console.cloud.google.com does not actually parse the JSON that is written to stderr, so the severity for instance is not set correctly (the JSON produced by `ContainerEngineHandler` is directly displayed as the `textPayload`).</del>

And finally (not really related to this but I'm not sure where this should go): the `fluentd-gcp` pod that is running by default on GKE clusters is configured with this fluentd configuration:
```
<filter …>
  …
  format /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<log>.*)/
</filter>
```
which is a very weird regex:
 - it parses only one char for the `severity`
 - the `time` is parsed as `YYYY` followed by a space, followed by anything _but_ a space: this does not correspond to any datetime format i can think of
 - the `source` attribute is followed by a `]`, but no matching `[` is in the regex

The `severity` issue makes it impossible to actually use this filter since stackdriver does not accept logs with a severity outside the usual `INFO|WARN|ERROR|…`

--

All-in-all, this makes it really hard to log data from a python pod: logging with the `CloudLogging` handler goes to "Global" by default (and is missing many kubernetes-related meta), <del>logging to stderr a JSON-formatted object is not parsed by the console.cloud UI,</del> and the regex in the fluentd setup cannot pick up any valid input

```
OS: Kubernetes 1.6.6, running on GKE with cos
Python version: 3.6 or pypy 5.8
google-cloud-python version: 1.1.0
```

**Comment by duggelz** [comment] 2017-07-19 23:25
Thanks for the bug report!

The regex matches Google's internal log format, which is indeed next to useless for customers.  If you're curious, matching log lines look something like this:

```
I0719 15:48:54.944977 140280647644928 scriptname.py:144] Some message here
```

The format dates back to 1999, so it doesn't necessarily match anything else in the universe :)

**Comment by lukesneeringer** [comment] 2017-08-07 17:19
@duggelz Is this a bug we can fix? Something that is stick as-is? I would appreciate guidance on what to do with this ticket. :-)

**Comment by duggelz** [comment] 2017-08-07 17:51
This is something we can fix.

**Comment by duggelz** [comment] 2017-08-07 19:01
CC @igorpeshansky Can you comment on the environment variable and fluentd sidecar configuration?

**Comment by igorpeshansky** [comment] 2017-08-07 20:14
As I understand it, GKE will keep using the fluentd containers to log the pods' `stdout`/`stderr`. @crassirostris should be able to help you debug why the output isn't parsed correctly.

**Comment by arthurdarcet** [comment] 2017-08-08 07:54
the JSON parsing part was a bug in the k8s config in 1.6, this has been fixed in 1.7, cf https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/143 (i updated the issue to reflect this)


I can create a pull request switch the environment variable to `KUBERNETES_SERVICE_HOST` ; but this will detect if we are running in Kubernetes cluster, not if we are running in a GKE cluster, so fixing this env variable will probably break the installation for people running in a k8s cluster on EC2/… without the fluentd DeamonSet (it will switch them away from the RPC client to this basic JSON over stderr, which won't log anything in stackdriver without the DeamonSet).

I have no idea how a GKE cluster could be detected though

**Comment by crassirostris** [comment] 2017-08-08 07:56
@arthurdarcet Let's sort it out first. What setup do you have (simple pod definition would help), what exactly do you expect and what exactly do you see?

I see a lot of confusion here. Sidecar? Default fluentd configuration? Python library? _Optional_ [glog](https://godoc.org/github.com/golang/glog) format parsing? Those are orthogonal things and it's hard to understand what's the problem is

**Comment by crassirostris** [comment] 2017-08-08 07:58
@duggelz 

> The regex matches Google's internal log format, which is indeed next to useless for customers

It's [not](https://github.com/google/glog) [internal](https://github.com/golang/glog) and it's used in opensource projects, including Kubernetes

**Comment by arthurdarcet** [comment] 2017-08-08 08:25
@crassirostris the issue here is only with this Python library: it decides whether or not the `ContainerEngineHandler` should be used based on the `KUBERNETES_SERVICE` environment variable. This variable does not exist in a k8s cluster, instead `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` are defined.

I did not mention any sidecar, and mention the fluentd DeamonSet only because this `ContainerEngineHandler` works by logging JSON to stderr and expecting a fluentd DeamonSet to pick it up.

**Comment by crassirostris** [comment] 2017-08-08 08:38
@arthurdarcet OK, thanks, now I understand the problem. I checked the code and `KUBERNETES_SERVICE` variable (without a suffix) is not present in any Kuberentes release dating back to to date when this logic was added to the library

@duggelz @waprin Indeed seems like a bug, should be `KUBERNETES_SERVICE_HOST` and/or `KUBERNETES_SERVICE_PORT`

@duggelz 

> Is the plan to migrate to direct RPC calls for logging instead of fluentd, or is that just for App Engine?

What happens inside containers in of no concern for Kubernetes, you can as well do that. However, GKE will always support sending stdout/stderr output to Stackdriver, because it's impossible to make everyone use the same approach and in Cloud Native world writing logs to stdio is more or less standard

**Comment by arthurdarcet** [comment] 2017-08-08 08:50
logging directly with RPC calls on GKE would
 - be more CPU-intensive than logging to stdio, which is problematic in Python because of the GIL
 - mean loosing all the metadata that are added by the fluentd plugin (pod name, …)

so I don't think that's an option here

But i'm not sure fixing the env variable is a great solution either, because using `ContainerEngineHandler` outside GKE - in a k8s cluster with no fluentd DeamonSet - would not work at all.

@crassirostris Any idea how we could detect if the pod is running in a GKE cluster? Could an env variable be added for that?

**Comment by crassirostris** [comment] 2017-08-08 09:08
@arthurdarcet 

> mean loosing all the metadata that are added by the fluentd plugin (pod name, …)

Much of this metadata is available inside the container, via [Downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/)

> But i'm not sure fixing the env variable is a great solution either, because using ContainerEngineHandler outside GKE - in a k8s cluster with no fluentd DeamonSet - would not work at all.

OTOH currently the description doesn't match the reality and this piece of code never works. How important is it not to break people who depend on the non-documented bug -- not for me to decide. Also, it's a `get_default_handler` method, you can always create a handler you need directly.

> Any idea how we could detect if the pod is running in a GKE cluster? Could an env variable be added for that?

Kubernetes is cloud provider agnostic, you can master running on GCP and nodes running on-prem or you can master running on-prem and nodes in GCP. There's no good way of detecting GKE cluster, you can only detect that your worker node is running on GCP by accessing the [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata), though there are some restrictions in GKE what exactly you can query

**Comment by duggelz** [comment] 2017-08-08 21:10
Ok, had some discussion with the other google-cloud-[language] teams.  We're trying to document a common set of behaviors across languages, but there seems to be consensus that we should

1a) Use the [Google Metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) rather than environment variables to detect that we're running on GKE specifically.
1b) Use the Downward API to detect Kubernetes non-GKE
2) Create appropriate logging resource labels from those metadata sources

There isn't strong consensus on stderr vs RPC.  So it should be easily user-configurable, and default (probably) to stderr for both K8 GKE and K8 non-GKE.

The existing ContainerEngineHandler will be rewritten or discarded once we agree on what it should do.

**Comment by crassirostris** [comment] 2017-08-09 06:57
> 1a) Use the Google Metadata server rather than environment variables to detect that we're running on GKE specifically.
> 1b) Use the Downward API to detect Kubernetes non-GKE

GKE -> GCE. If you're running Kubernetes K8s on GCE, you probably don't care much that it's not GKE, you want to use all the available tools. GKE is about making Kubernetes experience better with the same GCP experience, including logging.

> 2) Create appropriate logging resource labels from those metadata sources
> There isn't strong consensus on stderr vs RPC. So it should be easily user-configurable, and default (probably) to stderr for both K8 GKE and K8 non-GKE.

I'd say that stdout/stderr with json-formatted logs is a preferred way, because of the various metadata collection mechanisms @igorpeshansky is working on. Unless Kubernetes controls the log pipeline, it cannot provide the same experience in terms of CLI, UI and integration with other parts of the system.

**Comment by igorpeshansky** [comment] 2017-09-13 22:49
Also note that (a) https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/146 allows enabling JSON detection in any environment, and (b) the fluentd configuration is now decoupled from the contents of the `fluentd-gcp` container image, so can be adjusted at deployment time...

**Comment by jonparrott** [comment] 2018-02-22 19:16
This issue has been open for a long time.

@liyanhui1228, @duggelz is there anything still actionable here?

**Comment by liyanhui1228** [comment] 2018-02-22 21:04
Should be fixed, I'll close it.

**Closed by liyanhui1228** 2018-02-22 21:04 UTC
Labels: api: logging, priority: p2, type: bug
