### ISSUE TITLE
Google Datastore takes 20 minutes to pull a million rows.

### ISSUE THREAD

**Issue by ajudi** [GoogleCloudPlatform/google-cloud-python#4172] opened 2017-10-12 16:00 UTC
1. Linux, Ubuntu 16.04
2. Python 2.7 ipython
3. 
```
Name: google-cloud-datastore
Version: 1.3.0
```
I see that this might be expected behavour but it seems  little extreme, could someone clarify?

**Comment by lukesneeringer** [comment] 2017-10-12 16:03
Hi @ajudi,
Thanks for reporting.

Is this a problem with the _client_ taking a long time to process rows, or the server just takes 20 minutes to return a result? The former is probably an issue in the client library; the latter there is not much we can do about.

Whether 20 minutes to pull a million rows is intended behavior probably depends on your query.

**Comment by ajudi** [comment] 2017-10-12 16:05
Hey @lukesneeringer 
I get a response almost instantly however at the point where i turn that in to a list the time takes 20 minutes. I'm not sure if this is an inefficiency in the client or in the server. How would I be able to work that out. 

Thanks.

**Comment by dhermes** [comment] 2017-10-12 16:06
@ajudi Could you also provide the code you're using to do this?

You **probably** don't want to convert it into a list. `Query.fetch()` returns a paging iterator, so it will make requests from the server, the server will return as many results as it can and then a cursor into the next page. Under the covers, the iterator will then retrieve the next page and continue to yield one entity at a time.

**Comment by ajudi** [comment] 2017-10-12 16:11
Sure:
```
from google.cloud import datastore
client = datastore.Client.from_service_account_json('./precious-secrets.json')
query = client.query(kind='kind')
result = list(query.fetch()) 
```
The last stage takes around 20 minutes and is roughly a million rows.  I want to retrieve all the data. Is there a more efficient way to do this or am I using the wrong kind of DB.

Thanks.

**Comment by dhermes** [comment] 2017-10-12 16:17
@ajudi Just don't bother casting to a `list`, iterate through directly:

```python
query_iter = query.fetch()
for entity in query_iter:
    ...
```

**Comment by dhermes** [comment] 2017-10-12 16:20
You can also **explicitly** inspect each page:

```python
query_iter = query.fetch()
pages_iter = query_iter.pages
for index, page in enumerate(pages_iter):
    print('Page {} has {} entities.'.format(index + 1, page.num_items))
    for entity in page:
        ...
```

I'm not trying to imply this will be faster than 20 minutes, the limit is largely what the API can return per page.

----

I am going to pre-emptively close this since it doesn't seem there is anything we can do to speed up the fetch from the backend.

If you run the snippet and find you are surprised by the results, feel free to comment here and we can discuss / possibly re-open this issue.

**Closed by dhermes** 2017-10-12 16:20 UTC
Labels: api: datastore, type: question
