### ISSUE TITLE
_grpc_catch_rendezvous Unauthorized - Datastore - AppEngine Flexible

### ISSUE THREAD

**Issue by yaalaa** [GoogleCloudPlatform/google-cloud-python#3259] opened 2017-03-31 19:34 UTC
I'm running instance at App Engine Flexible.
I'm working with Google Datastore using `google-cloud-python` (now it's 0.23.0)
I've noticed datastore operations are used to fail with the stack like that:
```
File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 312, in get_multi transaction_id=transaction and transaction.id,
File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 123, in _extended_lookup transaction_id=transaction_id,
File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_http.py", line 340, in lookup lookup_response = self._datastore_api.lookup(project, lookup_request)
File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 111, in lookup return self._stub.Lookup(request_pb)
File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__ self.gen.throw(type, value, traceback)
File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 67, in _grpc_catch_rendezvous raise error_class(exc.details()) Unauthorized: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```
The failure is used to appear every hour.

Any idea?
PS. I suppose the issue is nearly new-born, I haven't seen it around a month ago.

**Comment by jonparrott** [comment] 2017-03-31 19:41
@yaalaa can we get the output of pip freeze / your deployed requirements.txt?

**Comment by yaalaa** [comment] 2017-03-31 19:46
here you are, @jonparrott 
```
appdirs==1.4.3
Babel==2.4.0
cachetools==2.0.0
certifi==2017.1.23
cffi==1.10.0
click==6.7
dill==0.2.6
enum34==1.1.6
Flask==0.12
Flask-Babel==0.11.1
Flask-Login==0.4.0
Flask-Misaka==0.4.1
Flask-Mobility==0.1.1
Flask-Table==0.4.1
future==0.16.0
futures==3.0.5
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.3
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
gapic-google-cloud-speech-v1beta1==0.15.3
gapic-google-cloud-vision-v1==0.90.3
google-auth==0.10.0
google-auth-httplib2==0.0.2
google-cloud==0.23.0
google-cloud-bigquery==0.23.0
google-cloud-bigtable==0.23.1
google-cloud-core==0.23.1
google-cloud-datastore==0.23.0
google-cloud-dns==0.23.0
google-cloud-error-reporting==0.23.2
google-cloud-language==0.23.1
google-cloud-logging==0.23.1
google-cloud-monitoring==0.23.0
google-cloud-pubsub==0.23.0
google-cloud-resource-manager==0.23.0
google-cloud-runtimeconfig==0.23.0
google-cloud-spanner==0.23.1
google-cloud-speech==0.23.0
google-cloud-storage==0.23.1
google-cloud-translate==0.23.0
google-cloud-vision==0.23.3
google-gax==0.15.8
googleapis-common-protos==1.5.2
grpc-google-iam-v1==0.11.1
grpcio==1.2.1
httplib2==0.10.3
httplib2shim==0.0.1
iso8601==0.1.11
itsdangerous==0.24
Jinja2==2.9.5
MarkupSafe==1.0
misaka==2.1.0
oauth2client==4.0.0
packaging==16.8
ply==3.8
proto-google-cloud-datastore-v1==0.90.3
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.3
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3
proto-google-cloud-speech-v1beta1==0.15.3
proto-google-cloud-vision-v1==0.90.3
protobuf==3.2.0
psutil==5.2.1
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
pyparsing==2.2.0
pytz==2017.2
PyYAML==3.12
regex==2017.2.8
requests==2.13.0
rsa==3.4.2
six==1.10.0
termcolor==1.1.0
twilio==5.7.0
Unidecode==0.4.20
urllib3==1.19.1
Werkzeug==0.12.1
```

**Comment by lukesneeringer** [comment] 2017-03-31 19:48
Is this an _intermittent_ failure?

**Comment by jonparrott** [comment] 2017-03-31 19:51
@lukesneeringer 

> The failure is used to appear every hour.

That coincides with the token refresh interval. Is datastore perhaps not retrying requests on 401?

**Comment by yaalaa** [comment] 2017-03-31 19:55
FYI folks, more my observances, if you'd like.
It looks like initermittent. At least there are long enough periods while the issue is not happening.
I haven't dared to retry 401-failed requests, BTW.
I'm not sure whether it tries to refresh the token and then to retry the original request.

**Comment by lukesneeringer** [comment] 2017-04-04 15:12
That seems like something the client should handle for you. We will look into it.

**Comment by mikelambert** [comment] 2017-04-13 08:28
I just started using `datastore` libraries on GAE Flexible (migrating from NDB), and am seeing this exact same error. Glad to see it's being looked into.

However, it doesn't appear to be intermittent for me.
3:47 - deployment
3:51 - (3:51-ish) go-live
4:17 - the above errors start, and keep going...
4:38 - i push again, and the next push goes live, and the errors finally stop
5:30 - errors haven't come back...yet

To be clear, I am constructing a long-lived client at the module level, and then using that global from the functions:
```
client = datastore.Client()

def _save_cache(key, data):
  obj = datastore.Entity(key=client.key('TableName', key), exclude_from_indexes=['data'])
  obj['data'] = data
  client.put(obj)

def _get_cache(key):
  result = client.get(client.key('TableName', key))
  if result:
    return result['data']
  else:
    return None
```
I didn't see best-practices in the docs, so I'm not sure if I should be constructing a new client per-request and then passing-it-down through all of my db calls.

**Comment by dhermes** [comment] 2017-04-13 17:14
> I didn't see best-practices in the docs, so I'm not sure if I should be constructing a new client per-request and then passing-it-down through all of my db calls.

You shouldn't need to, though we are still working on making our clients threadsafe, so if your application is doing any threading you may see issues (though I don't think that is related to this issue).

**Comment by jonparrott** [comment] 2017-04-13 17:15
I'm thinking that this and #3212 have the same root cause.

**Comment by mikelambert** [comment] 2017-04-13 23:27
And perhaps it's obvious, but just to follow-up: If I create a new datastore client on each servlet request, then I no longer get the errors mentioned above.

**Comment by thijsterlouw** [comment] 2017-04-25 08:50
I can confirm we are also seeing this problem:

```

    gamestate = datastore_client.get(datastore_key)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 309, in get
    deferred=deferred, transaction=transaction)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 356, in get_multi
    transaction_id=transaction and transaction.id,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 138, in _extended_lookup
    project, read_options, key_pbs)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 82, in _catch_remap_gax_error
    six.reraise(error_class, new_exc, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 74, in _catch_remap_gax_error
    yield
  File "/usr/local/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 204, in lookup
    return self._lookup(request, options)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/gax/retry.py", line 126, in inner
    ' classified as transient', exception)
google.cloud.exceptions.Unauthorized: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

![gamestate_cloud_datastore_unauthenticated](https://cloud.githubusercontent.com/assets/126053/25376406/54fa4a32-29a4-11e7-86b6-c175687edff3.png)
Orange spikes indicate Unauthorized errors

We are running in K8s (GKE) with volume-mounted pubsub

**Comment by devries** [comment] 2017-04-29 16:58
I am experiencing this issue as well. I basically have had to make a library which retries every put, get or fetch request which fails with a new request that creates a new client.

**Comment by jonparrott** [comment] 2017-05-08 17:08
This should be fixed by https://github.com/GoogleCloudPlatform/google-auth-library-python/releases/tag/v1.0.1 which was just released. Try making sure that package is up-to-date and if this is still an issue, let us know.

**Comment by yaalaa** [comment] 2017-05-09 18:49
Seems fixed, at the first glance. (1.5hour testing).
Thanks

**Comment by mikelambert** [comment] 2017-05-19 12:53
I still see this issue (have verified the libraries on disk contain the patch referenced above):
```
Unauthorized: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
at inner (/env/local/lib/python2.7/site-packages/google/gax/retry.py:127)
at inner (/env/local/lib/python2.7/site-packages/google/gax/api_callable.py:376)
at base_caller (/env/local/lib/python2.7/site-packages/google/gax/api_callable.py:416)
at inner (/env/local/lib/python2.7/site-packages/google/gax/api_callable.py:428)
at lookup (/env/local/lib/python2.7/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py:204)
at lookup (/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py:115)
at _catch_remap_gax_error (/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py:74)
at _catch_remap_gax_error (/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py:82)
at __exit__ (/usr/lib/python2.7/contextlib.py:35)
at lookup (/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py:115)
at _extended_lookup (/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py:138)
at get_multi (/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py:356)
at get (/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py:309)
```

I push an instance at 17:21, which starts receiving traffic at 17:33. Errors start at 17:46 and continue indefinitely until I re-push a new instance.

For the moment, I've gone back to my "create a new client for each incoming request" workaround to keep things working.

**Comment by dhermes** [comment] 2017-05-19 14:46
@mikelambert Any chance there is clock drift on the machine? Is it possible you have multiple envs and one has the old version installed?

**Comment by mikelambert** [comment] 2017-05-19 14:56
These are freshly-created GAE Flexible VM instances. I assume Google's clock drift should be good.

These are then instantiated from the same docker image (so checking on one machine should speak for the rest).

**Comment by mikelambert** [comment] 2017-05-29 18:27
This issue is closed. Should I open a new issue to track the problem I was seeing, under the assumption that it's a different issue with a different cause?

(Mine was perhaps different from the originally-reported error, in that it wasn't intermittent, and instead started-and-kept-occurring after running a certain length of time.)

**Comment by dhermes** [comment] 2017-05-31 16:46
I think it's fine to keep the issue here?

**Comment by lukesneeringer** [comment] 2017-08-10 14:58
@mikelambert Are you still having this issue?
It is a new issue with a new cause, as you said, and hopefully it has been fixed by some of our more recent updates (in particular, getting rid of httplib2).

I am going to close this as stale, but feel free to open a new issue if the problem is still extant.

**Closed by lukesneeringer** 2017-08-10 14:58 UTC
Labels: api: datastore, auth, grpc, priority: p2+, type: bug

**Comment by mikelambert** [comment] 2017-09-06 07:07
My issue appears to have been resolved when I upgraded to the latest version. Thanks!
