### ISSUE TITLE
Streaming upload/download for blobs

### ISSUE THREAD

**Issue by cristicbz** [GoogleCloudPlatform/google-cloud-python#2871] opened 2016-12-15 12:26 UTC
We're in the process of moving from S3 to GCS and we've hit a snag: with `boto` S3 one can stream a download using the `read` method on a key, and stream an upload using multiple 'multipart' calls: `initiate_multipart_upload`, `upload_part_from*` and `complete_upload`.

It's imperfect, but this allows simple streaming uploads and downloads of very large files. Furthermore, stick some buffering in there and you can easily wrap S3 reads and writes into file-like objects (without seeking), like [`smart_open`](https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/smart_open_lib.py#L562) does.

I think that the API supports all the pieces necessary to implement this in the client (which would be greatly appreciated!), but in the meantime can anyone suggest a workaround which does not require a temporary file?

Thanks!

**Comment by linar-jether** [comment] 2017-06-27 07:46
At least for uploads, there is support, https://github.com/GoogleCloudPlatform/google-cloud-python/pull/1914/files

Could be documented better...

**Comment by linar-jether** [comment] 2017-06-27 08:33
Simple example for a streaming upload of a large dataframe

```python
impos os
import threading

r, w = os.pipe()
r, w = os.fdopen(r, 'rb'), os.fdopen(w, 'wb')

df = _large_pandas_df

path = 'gs://test_bucket/testfile.pickle'

# Important to set a chunk size when creating the blob `bucket.blob(blob_path, chunk_size=10 << 20)`
b = get_blob(path)

# Perform the upload in a separate thread
t = threading.Thread(target=lambda b, r: b.upload_from_file(r), name='upload-blob:%s' % path, args=(b, r))

# Since the blob upload is reading from a pipe, the operation is blocking until the pipe closes
t.start()

# This starts writing to the pipe
df.to_pickle(w)

# Make sure to close the pipe so the upload completes
w.close()

# Wait for the upload to complete
t.join()

```

**Comment by teoguso** [comment] 2017-07-14 11:31
@linar-jether that's a great snippet. I have a question though: what does your `get_blob()` function do exactly? Is it the same as the `.blob()` method of the bucket class?

**Comment by linar-jether** [comment] 2017-07-14 11:36
Just a util function that gets a Blob object from a path ('gs://bucket_name/obj.name')

**Comment by teoguso** [comment] 2017-07-14 11:55
Thanks! Do you have suggestions for the recommended chunk size?

**Comment by linar-jether** [comment] 2017-07-14 12:04
Whatever works best for your memory/throughput requirements, when a lower
chunk size will require less memory but might have a lower throughput and
vise versa

**Comment by teoguso** [comment] 2017-07-14 12:09
Thanks a lot, and I'm sorry, I am quite new to this. Could I use the same procedure to stream up JSON strings directly instead of bytes?

**Comment by linar-jether** [comment] 2017-07-14 12:11
Yes sure, will work for any kind of stream

**Comment by lukesneeringer** [comment] 2017-08-11 17:05
This seems to be resolved, as best as I can tell. Closing.

@teoguso, poke if I got it wrong, and I will reopen.

**Closed by lukesneeringer** 2017-08-11 17:05 UTC
Labels: api: storage, status: acknowledged, type: enhancement

**Comment by e4p** [comment] 2017-08-30 04:23
Can I request that this issue is reopened? We use GCS extensively at Verily and we frequently deal with large indexed files since we use a variety of industry-standard genomics file formats (VCF, BAM, SAM, etc...). Being able to read a file header then seek to a specific position is a MAJOR speedup for some processes and we've had to hack around the lack of this by manually modifying the `Content-Range` headers a few times.

It seems to me that implementing Python's [io.IOBase interface](https://docs.python.org/2/library/io.html) would be an ideal solution to this problem.

There is prior work on this task (see [gcs-client](https://github.com/Akrog/gcs-client)) and it's even under a compatible license, but I'm guessing that some amount of work would be needed to clean this code up and adapt it to follow the conventions and style here.

**Comment by dhermes** [comment] 2017-08-30 04:28
@e4p This functionality exists right now in [`google-resumable-media`][1].

I'm fairly certain the thing you're asking for (i.e. partial reads) are not the same as what this issue was originally about.

Just in case I misunderstand you, could you provide a code snippet (real or "fictional") of what you'd like to do and how it fails with the current code?

[1]: https://googlecloudplatform.github.io/google-resumable-media-python/latest/

**Comment by e4p** [comment] 2017-08-30 04:50
First, I want to thank you for pointing me to `google-resumable-media` it certainly will cover some of our uses. That said, it's not a replacement for a standard file object. To use a somewhat synthetic example (because the example that comes to mind includes code I can't share). Biopython, many other python libraries understands the io.IOBase interface and can accept file handles as arguments. The following code can streaming a FASTQ (genomic read quality file) if you have access to a file object.

```
from Bio import SeqIO
with open("example.fastq", "rU") as fileobj:
    for rec in SeqIO.parse(fileobj, "fastq"):
        print(rec.seq)
        print('  name=%s\n  annotations=%r' % (rec.name, rec.annotations)
```

**Comment by gastlich** [comment] 2018-03-21 20:12
@linar-jether do you know if there is any other way to achieve what you have done in your code snippet? It's not working anymore, because of the changes in `reusable-media`, which expects to invoke `seek` on stream object

**Comment by linar-jether** [comment] 2018-03-22 07:55
@gastlich Yes, the snippet seems to be broken with the current version... 

@dhermes, looks like a regression on recent versions

Haven't had the chance to use the [google-resumable-media](https://googlecloudplatform.github.io/google-resumable-media-python/latest/) library but it might provide the functionality to do streaming uploads. 

Don't know the reason but our use case for streaming uploads still works (uploading from a streaming http request), might be a different code path for different objects

```python
import threading
import requests

# Fetch  
res = requests.get('http://speedtest.ftp.otenet.gr/files/test10Mb.db', stream=True)
r = res.raw

path = 'gs://test_bucket/testfile.pickle'

# Important to set a chunk size when creating the blob `bucket.blob(blob_path, chunk_size=10 << 20)`
b = get_blob(path, 1 << 20)

# Perform the upload in a separate thread
t = threading.Thread(target=lambda b, r: b.upload_from_file(r), name='upload-blob:%s' % path, args=(b, r))

# Since the blob upload is reading from a pipe, the operation is blocking until the pipe closes
t.start()

# Wait for the upload to complete
t.join()
```

**Comment by gastlich** [comment] 2018-03-22 12:07
@linar-jether thanks for quick reply

I checked your code and it's working fine with requests `response.raw` object. I think what's happening here is, writing to `response.raw` doesn't move a position of cursor, so that the `upload_from_file` might start from the beginning - otherwise it complains with:

```python
if stream.tell() != 0:
    raise ValueError(u'Stream must be at beginning.')
```

I still haven't solved my issue, because I'm writing into memory buffer `io.BytesIO`, and every write moves the cursor to the end of written bytes... 

```python
with BytesIO() as file:
    destination = f'postgres/{table_name}/{org_id}.csv'
    blob = bucket.blob(destination, chunk_size=10 << 20)

    thread = threading.Thread(
        target=lambda b, r: blob.upload_from_file(r),
        name='upload-blob:%s' % destination,
        args=(blob, file))

    query = f'SELECT * FROM {table_name} WHERE organisation_id={org_id} LIMIT 10000'
    cursor.execute(query)

    # writes into memory, but moves cursor all the time
    export_query = f'COPY ({query}) TO STDOUT WITH CSV HEADER'
    cursor.copy_expert(export_query, file)

    # Seek to the beginning
    file.seek(0)
    # I cannot start thread before `cursor.copy_expert` because resumable_media expects to start from beginning
    thread.start()

    # Wait for the upload to complete
    thread.join()
```

As you can see, in my example I'm able to get rid of threading and do everything in blocking/synchronous way. But my problem is that the data set might be very big, and python will consume all of the allowed RAM memory. I partially solved my issue by using stored temp file on file disk, at least it won't consume memory but it's slower and I'm still hoping to do this properly with in-memory approach.

**Comment by Edorka** [comment] 2021-07-22 06:32
I don't get why `stream.tell() != 0:` should raise an exception instead of a warning.
I was using the example https://github.com/googleapis/google-cloud-python/issues/2871#issuecomment-311291059 we were able to continue mocking the `tell` method as a opened pipe tell will give an os exception.

However when the program continues we get an extrange error from the API:
```
google.api_core.exceptions.BadRequest: 400 PUT https://storage.googleapis.com/upload/storage/v1/b/proteus-dev-eov-delete_me/o?uploadType=resumable&upload_id=ADPycdvFahNsxwUYj0gixPSamAP8N07ru_yTNRef49xdXbAt89IKNiAyY1tp5CDxXzt3U0M0Jo4KRd-awc8tyHYmu48: Client sent query request with a non-empty body.: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>, 308)
```
This error is caused in this line:

```
venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2348, in upload_from_file
      created_json = self._do_upload(
```
