### ISSUE TITLE
gRPC _Rendezvous w/ 'ABORTED' status propagated from 'Session.run_in_transaction'

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3562] opened 2017-06-28 18:54 UTC
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2281

@tseaver Can you triage / update the issue title to be more specific?

**Comment by tseaver** [comment] 2017-06-28 19:21
The code for `Session.run_in_transaction` expects that the `ABORTED` bit will be propagated as an instance of `google.gax.errors.GaxError`:  somehow, the underlying GAPIC code is raising a gRCP `_Rendezvous` instead.

**Comment by tseaver** [comment] 2017-06-28 19:22
@lukesneeringer Do we need to be regenerating the GAPIC code?

**Comment by vladkluev** [comment] 2017-07-20 17:18
Hi this is very annoying, to have a whole bunch of exceptions thrown in my application whenever a transaction is aborted. Is there any workaround to this issue at the moment?

**Comment by tseaver** [comment] 2017-07-25 18:39
@vladkluev I'm hopeful we will have a fix pushed out shortly (this bug blocks PR #3663).

**Comment by tseaver** [comment] 2017-07-25 18:44
So, the issue is that the `streaming_read` and `streaming_execute_sql` calls are propagating the `_Rendezvous` error, rather than wrapping them up in a `GaxError` as the `commit` call does.

**Comment by bjwatson** [comment] 2017-07-25 22:51
@tseaver I'm discuss this with @lukesneeringer offline.

**Comment by lukesneeringer** [comment] 2017-07-25 22:59
Repeating this back to ensure I understand: Basically this is a situation where one call wraps the errors while others do not? Is this a configuration difference? Something else?

**Comment by tseaver** [comment] 2017-07-25 23:06
@lukesneeringer the new system test in #3663 provokes it routinely:  the gRPC `ABORTED` return triggered by `read_streaming` is *not* wrapped, while the other system tests (which mean to trigger it in the `commit` call) do get it wrapped.

**Comment by lukesneeringer** [comment] 2017-07-27 15:31
Okay, so it is literally non-deterministic then?

**Comment by tseaver** [comment] 2017-07-27 15:35
It fails repeatably on #3663.  My *suspicion* is that the GAX/GAPIC streaming support is involved (our `read` and `execute_sql` methods actually call the streaming APIs).

**Comment by tseaver** [comment] 2017-07-27 15:39
@vladkluev The `ABORTED` error is *supposed* to propagate as a `GaxError`, but is somehow escaping as the lower-level `grpc._Rendezvous`.  The `run_in_transaction` code handles retrying correctly when `GaxError` is raised.

**Comment by vladkluev** [comment] 2017-07-27 15:49
Ah gotcha

**Comment by bjwatson** [comment] 2017-07-29 00:57
@eoogbe can you fix this issue in GAPIC/GAX code next week? I'll be OOO Monday and Tuesday, but I think @tseaver can help you understand what's needed here.

This is blocking us from finishing a system test (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3663) required for the Spanner Beta.

**Comment by eoogbe** [comment] 2017-08-03 00:19
It looks like the streaming gRPC methods *return* a `_Rendezvous` on error, while the unary ones *raise* a `_Rendezvous`. The difference seems to have something to do with `_Rendezvous` being an iterator, but tbh I don't really understand the gRPC code enough to know what the fix is rn.

**Comment by bjwatson** [comment] 2017-08-03 00:23
Thanks for the analysis, @eoogbe. @nathanielmanistaatgoogle might be able to help you with understanding the gRPC code, or can point you to someone who can.

**Comment by nathanielmanistaatgoogle** [comment] 2017-08-04 02:38
@eoogbe: the response-streaming methods _return_ [an object that is both a `grpc.Call` and an iterator that emits the response messages of the RPC](https://github.com/grpc/grpc/blob/3e2d05d4a2bd6bae9021a010f34372da83b7a772/src/python/grpcio/grpc/__init__.py#L510-L514). If the RPC fails, attempts to draw another response message from the object (presumably during iteration, but `next(my_response_iterator_object)` would work just as well) raise an exception that is both a `grpc.RpcError` and a `grpc.Call`.

Under the hood, as you've discovered, it's just one object (a `_Rendezvous` instance), but that's expected to change in a future release so be reticent to code relying on it.

Does your code look something like
```python
my_response_iterator_call = my_stub.MyResponseStreamingRpcMethod(
    my_request_or_request_iterator)
try:
    for my_response in my_response_iterator_call:
        do_thing(my_response)
except grpc.RpcError as my_rpc_error_call:
    logging.exception(
        'RPC terminated abnormally with code %s and details %s!',
        my_rpc_error_call.code(), my_rpc_error_call.details())
else:
    logging.info('RPC completed successfully!')
```
? Should it look something like that?

**Comment by eoogbe** [comment] 2017-08-04 17:59
The code that wraps the `RpcError` in a `GaxError` is [here](https://github.com/googleapis/gax-python/blob/master/google/gax/api_callable.py#L376). It is intended to work on both unary and streaming functions, so it can't assume that the return value is an iterator.

**Comment by nathanielmanistaatgoogle** [comment] 2017-08-05 00:05
@eoogbe: it's also not safe to assume that the only problems that can ever happen during an RPC happen during RPC invocation. It's perfectly possible, for example, for a response-streaming RPC to stream one hundred responses and then time out so that the client sees an exception raised from the one-hundred-and-first call to `next(my_response_iterator)`. Or consider another RPC that has streamed fifty responses (and those responses have arrived at the client and been emitted from the response-iterator object) before the user's wireless router falls off the shelf and into the bathtub?

As I assess it `_catch_errors` is not adequate for what you're trying to do. Consider splitting it into `_catch_errors_on_invocation` and `_catch_errors_during_iteration`? Or maybe author some other utility function that given an iterator returns an exception-translating-wrapping of the given iterator? While it may not be the case that `_catch_errors` knows whether or not the RPC invocation is response-unary or response-streaming, something at some level of abstraction must, and I suppose that will be a place where at least part of your fix will have to be made.

**Comment by jonparrott** [comment] 2017-08-07 22:32
#3738 will give us the fundamental building blocks to map exceptions correctly, but @nathanielmanistaatgoogle is right, we need to take special care with unary-streaming methods. I'll address that in the PR that adds gRPC-specific helpers to `google.api.core`.

**Comment by bjwatson** [comment] 2017-08-07 23:06
@jonparrott Is there anything that @eoogbe needs to do in https://github.com/googleapis/gax-python to fix this issue, or does https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3738 provide everything we need to fix this issue?

**Comment by lukesneeringer** [comment] 2017-08-08 02:07
* #3738 is necessary but not sufficient.
  * GAX does not use #3738; @jonparrott will need to port that segment to `google.api.core`.

**Comment by jonparrott** [comment] 2017-08-08 02:12
To further clarify: #3738 is sufficient to solve this specific case because
spanner has significant manual code above the gapic, so the mapping can be
done there. google.api.core will provide a iterator wrapper for
unary-streaming that can be used by gapic.

**Comment by bjwatson** [comment] 2017-08-08 18:27
Fixing this issue that's blocking Python Spanner Beta has the greatest urgency, so it's good to hear that https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3738 is sufficient to fix it.

That said, we'll need to fix this for GAPIC-only libraries. @jonparrott can you show @eoogbe what needs to be done to port your work to GAX, so that she's also familiar with the fix?

**Comment by jonparrott** [comment] 2017-08-08 18:29
Following up internally.

**Comment by bjwatson** [comment] 2017-08-08 18:46
Thanks for the update @jonparrott. I've responded internally.

What needs to be done to close this specific issue for Spanner? Will you do it or should @tseaver?

**Comment by jonparrott** [comment] 2017-08-08 19:07
It's up to @tseaver (see [here](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3663#issuecomment-320799110)) but i'm happy to help.

**Comment by bjwatson** [comment] 2017-08-08 19:45
Thanks, Jon.

**Comment by tseaver** [comment] 2017-08-09 22:19
I will be merging the workaround in #3663 for spanner tonight.

**Comment by bjwatson** [comment] 2017-08-09 22:34
Thanks @tseaver!

**Comment by tseaver** [comment] 2017-08-10 01:20
Via #3663.

**Closed by tseaver** 2017-08-10 01:20 UTC
Labels: api: spanner, flaky, gax, grpc, priority: p1, status: release blocking
