### ISSUE TITLE
PubSub white space not stripped in project name

### ISSUE THREAD

**Issue by eoltean** [GoogleCloudPlatform/google-cloud-python#4520] opened 2017-12-04 17:48 UTC
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
Alpine Linux Docker container
3. Python version and virtual environment information `python --version`
Python 3.6
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
0.29.2
5. Stacktrace if available
```
Exception in thread Thread-MonitorBatchPublisher:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 51, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, Requested project not found or user does not have access to it (project= my-project). Make sure to specify the unique project identifier and not the Google Cloud Console display name.)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 221, in monitor
    return self._commit()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 182, in _commit
    self.messages,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 325, in publish
    return self._publish(request, retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 134, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python3.6/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 53, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 2, in raise_from
google.api_core.exceptions.NotFound: 404 Requested project not found or user does not have access to it (project= my-project). Make sure to specify the unique project identifier and not the Google Cloud Console display name.
```
6. Steps to reproduce
include white space in the project name

7. Code example
publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(" my-project", "my-topic")
publisher.publish(topic_path, data=data)

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by dhermes** [comment] 2017-12-04 17:53
@eoltean Thanks for taking the time to file an issue, but I'm inclined to say this is working as intended: we need the user to pass the actual project, not a project with whitespace at the front.

I am going to pre-emptively close this issue, but am happy to discuss and re-open.

**Closed by dhermes** 2017-12-04 17:53 UTC

**Comment by eoltean** [comment] 2017-12-04 18:09
@dhermes The only reason I saw this as an issue was it used to be stripped in 0.28.4 resulting in a breaking change.

**Comment by dhermes** [comment] 2017-12-04 18:11
Oh that is definitely good to know!

@lukesneeringer Anything to say?

Irrespective of what Luke says about the `0.28.x` -> `0.29.x` transition, I don't think that's a feature that makes sense.

**Comment by eoltean** [comment] 2017-12-04 18:11
but I do tend to agree the user should be passing in the right data. But it was something easy to miss in our cause in the way that we were loading env variables

**Comment by dhermes** [comment] 2017-12-04 18:19
@eoltean Not sure if you're aware but the `project` can be determined from a JSON keyfile for a service account, so you don't actually need the project in an environment variable.

**Comment by eoltean** [comment] 2017-12-04 18:30
ok good to know thanks
