### ISSUE TITLE
How to use MonitoredResource in stackdriver logging

### ISSUE THREAD

**Issue by daiyueweng** [GoogleCloudPlatform/google-cloud-python#3203] opened 2017-03-24 11:51 UTC
Hi, I am wondering how to use `MonitoredResource` in `Stackdriver logging` in `Python`. I found that `MonitoredResource` is available in `REST API`, `JAVA`, `NODE.JS` and `C#`, but I couldn't find it in `Python`. Since all log entries are written to `global` resource by default, I am wondering how to change that to a specific resource in `Python`, an example will be great.

cheers

**Comment by lukesneeringer** [comment] 2017-03-24 15:01
Summoning @waprin.

**Comment by waprin** [comment] 2017-03-27 21:07
@daiyueweng Unfortunately, there's currently no way to do this at the top-level documented API. We are planning to fix this.

In the meantime, your best bet is to use the lower-level APIs. If you take a look at [client.py](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/client.py), you'll notice the code duplexes between a GRPC level (called GAX, which is a helper library for GRPC) `_gax.py` and an HTTP client `_http.py`. They both implement a `write_entries` resource that takes a MonitoredResource string. So you can set it by using that object directly. 

Closing this as duplicate of #2673 , if you have more questions you can re-open but for the sake of organization, it's better to move the discussion to that issue.

**Closed** 2017-03-27 21:07 UTC
Labels: status: acknowledged, type: question
