### ISSUE TITLE
blob.upload_from_filename blocks for upwards of an hour.

### ISSUE THREAD

**Issue by tweeter0830** [GoogleCloudPlatform/google-cloud-python#3441] opened 2017-05-19 15:08 UTC
I am using the following code to upload files to GCS.

```python
    blob = bucket.blob(gcs_filepath)
    logging.info('Uploading file "%s" to "%s".', filepath, gcs_filepath)
    blob.upload_from_filename(filepath)
    logging.info('Uploaded file "%s" to "%s".', filepath, gcs_filepath)
```

This works most of the time. However, it has been stuck uploading for the last hour and has not raised an exception yet. It seems like this method should have a timeout or something for situations like this. It would also be helpful if it had the option to log the progress of the method for further diagnosis.

**Comment by tseaver** [comment] 2017-05-19 15:54
Duplicate of #3442, which has more information.

**Comment by tseaver** [comment] 2017-05-19 15:55
Hmm, not a duplicatie.

**Comment by dhermes** [comment] 2017-05-19 16:29
@tseaver @tweeter0830 It may be somewhat of a duplicate if the real answer is that `httplib2` + threading == a bad time.

**Comment by tweeter0830** [comment] 2017-05-19 20:31
I am using this is a thread.

**Comment by tseaver** [comment] 2017-05-19 20:42
@tweeter0830 Or switch to using a separate `Client` instance per thread (they should be relatively cheap to construct).

**Comment by dhermes** [comment] 2017-05-19 20:43
@tweeter0830 I'm closing this out as that is the culprit. As @tseaver said, you'll want `Client` instances to be thread local (for now). We will soon be dumping `httplib2` altogether (for `requests`).

**Closed** 2017-05-19 20:45 UTC
Labels: api: storage, flaky

**Comment by tweeter0830** [comment] 2017-05-22 14:49
I moved the client into a single thread and I am still having this issue.

**Comment by dhermes** [comment] 2017-05-22 17:18
@tweeter0830 Can you provide some example code so we can discuss the implementation?

**Comment by GEverding** [comment] 2017-05-23 15:21
I'm seeing similar issues. I'm creating new Client Objects each time I want to upload a file.

**Comment by dhermes** [comment] 2017-05-23 16:42
Thanks for the snippet @GEverding. I'm not a regular user of Celery so I'm not sure what the implications are here. Are you saying you put this in a Python module at global scope and then point Celery at that module?

**Comment by GEverding** [comment] 2017-05-23 17:08
@dhermes Yes the function is in the global scope. We run each task on a separate process so there should only be one thread calling this piece of code.

**Comment by tweeter0830** [comment] 2017-05-24 14:48
Sorry, I was mistaken. I appears to have fixed the issue.

**Comment by kain64** [comment] 2017-06-14 16:31
same problem. 100mb upload ~3-4 minutes. using webbrouser gui ~less than 20 sec
`storage_client = storage.Client()
    bucket = storage_client.get_bucket(GOOGLE_BUCKET)
    blob = bucket.blob(file_name)
    blob.upload_from_filename(os.path.join(local_path, file_name))`

**Comment by dhermes** [comment] 2017-06-14 17:40
@kain64 It appears you have a different issue than the original reporter. It's likely that the webbrowser GUI is using multiple threads to upload the file in chunks simultaneously (but I'm not sure).

If you'd really like fast uploads, I recommend looking into `gsutil` (we would like to speed up our uploads, but `gsutil` is fast today).
