### ISSUE TITLE
BigQuery: import on Python 3.7 causes a segmentation fault

### ISSUE THREAD

**Issue by cpcloud** [GoogleCloudPlatform/google-cloud-python#5637] opened 2018-07-17 17:08 UTC
- OS: Arch Linux
- Steps to reproduce and Python version:
```sh
$ conda create -q -y -c conda-forge -n bq python=3.7 google-cloud-bigquery
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/phillip/miniconda3/envs/bq

  added / updated specs:
    - google-cloud-bigquery
    - python=3.7


The following NEW packages will be INSTALLED:

    asn1crypto:               0.24.0-py_1           conda-forge
    ca-certificates:          2018.4.16-0           conda-forge
    cachetools:               2.0.1-py_0            conda-forge
    certifi:                  2018.4.16-py37_0
    cffi:                     1.11.5-py37h9745a5d_0
    chardet:                  3.0.4-py_1            conda-forge
    cryptography:             2.2.2-py37h14c3975_0
    google-api-core:          1.1.0-py_0            conda-forge
    google-auth:              1.5.0-py_0            conda-forge
    google-cloud-bigquery:    1.4.0-py_0            conda-forge
    google-cloud-core:        0.28.1-py_0           conda-forge
    google-resumable-media:   0.3.1-py_0            conda-forge
    googleapis-common-protos: 1.5.3-py_1            conda-forge
    idna:                     2.7-py_1              conda-forge
    libffi:                   3.2.1-3               conda-forge
    libgcc-ng:                7.2.0-hdf63c60_3
    libprotobuf:              3.5.2-hd28b015_1      conda-forge
    libstdcxx-ng:             7.2.0-hdf63c60_3
    ncurses:                  6.1-0                 conda-forge
    openssl:                  1.0.2o-0              conda-forge
    pip:                      10.0.1-py37_0
    protobuf:                 3.5.2-py37hf484d3e_1
    pyasn1:                   0.4.3-py_0            conda-forge
    pyasn1-modules:           0.2.1-py_0            conda-forge
    pycparser:                2.18-py_1             conda-forge
    pyopenssl:                18.0.0-py37_0
    pysocks:                  1.6.8-py37_0
    python:                   3.7.0-hfd72cd7_0      conda-forge
    pytz:                     2018.5-py_0           conda-forge
    readline:                 7.0-ha6073c6_4
    requests:                 2.19.1-py37_0
    rsa:                      3.4.2-py_1            conda-forge
    setuptools:               39.2.0-py37_0
    six:                      1.11.0-py37_1
    sqlite:                   3.24.0-h2f33b56_0     conda-forge
    tk:                       8.6.7-0               conda-forge
    urllib3:                  1.23-py37_0
    wheel:                    0.31.1-py37_0
    xz:                       5.2.3-0               conda-forge
    zlib:                     1.2.11-h470a237_3     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
$ conda activate bq
$ python --version
Python 3.7.0
$ python -c 'import google.cloud.bigquery'
[1]    16222 segmentation fault (core dumped)  python -c 'import google.cloud.bigquery'
```

I suspect that one of the noarch google-* packages is actually dependent on some ABI that changed in Python 3.7, and that this may not be a BigQuery specific issue.

**Comment by cpcloud** [comment] 2018-07-17 17:16
Running

```
$ gdb --eval-command=run --args python -c "import google.cloud.bigquery"
```
shows that importing `google.protobuf.pyext._message` might be related.

When I try to import `google.protobuf.pyext._message` I get a missing symbol error from the shared object:

```
$ python -c "import google.protobuf.pyext._message"                                                                                                                                   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/phillip/miniconda3/envs/bq/lib/python3.7/site-packages/google/protobuf/pyext/_message.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolB5cxx11Eb
```

**Comment by tseaver** [comment] 2018-07-17 19:08
I'm not sure how conda is setting things up, but we *do* support Python 3.7, including running the test suite on it under CI.  The known limitation at the moment is that `pandas` doesn't support Python 3.7, which means that the features which integrate with pandas don't work.  This caveat is distinct from the segfault you are seeing, however.

**Comment by tseaver** [comment] 2018-08-29 17:50
Trying to reproduce in a Python 3.7.0 virtualenv:

```bash
$ python3.7
Python 3.7.0 (default, Aug 29 2018, 13:40:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ python3.7 -m venv /tmp/gcp-5637
$ /tmp/gcp-5637/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-18.0 setuptools-40.2.0 wheel-0.31.1
$ /tmp/gcp-5637/bin/pip install google-cloud-bigquery
---
Successfully installed cachetools-2.1.0 certifi-2018.8.24 chardet-3.0.4 google-api-core-1.3.0 google-auth-1.5.1 google-cloud-bigquery-1.5.0 google-cloud-core-0.28.1 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
$ /tmp/gcp-5637/bin/python -c "import google.cloud.bigquery" && echo NO SEGFAULT
NO SEGFAULT
```

Please feel free to continue investigating / following up here, but I am closing the issue because I can't reproduce it using "stock" Python packaging.

**Closed by tseaver** 2018-08-29 17:50 UTC
Labels: api: bigquery, packaging, type: question
