### ISSUE TITLE
ValueError thrown in django view

### ISSUE THREAD

**Issue by tyggna** [GoogleCloudPlatform/google-cloud-python#5026] opened 2018-03-14 03:04 UTC
This happens on 0.29.0, and 0.30.1
Steps to reproduce:  the following code works within the django shell environment, and in a python prompt and from a command-line script, but gives the traceback below when encapsulated in a view and run through the dev server (python manage.py runserver), or through uwsgi
<pre>
image_file = open(tmpfile, 'rb') 
img = types.Image(content=bytes(image_file.read()))
features = [types.Feature(type=types.Feature.SAFE_SEARCH_DETECTION, max_results=8), 
                  types.Feature(type=types.Feature.LABEL_DETECTION, max_results=8)]
gclient = vision.ImageAnnotatorClient()
resp = gclient.annotate_image({'image' : img, 'features' : features})
</pre>
and the traceback from running inside a view
<pre>
Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/website/beta_uwsgi/git/swym_django/app/views.py", line 276, in vision_process
    resp = gclient.annotate_image({'image' : img, 'features' : features})
  File "/usr/local/lib/python2.7/site-packages/google/cloud/vision_helpers/__init__.py", line 67, in annotate_image
    r = self.batch_annotate_images([request], retry=retry, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/vision_v1/gapic/image_annotator_client.py", line 156, in batch_annotate_images
    requests=requests)
ValueError: Field name must be a string
</pre>

a more full code example inside a functional view:
<pre>
    if request.method == 'POST':
        f = request.FILES['image_data']
        tmpfile = "/tmp/upload-" + str(uuid.uuid4()) + ".jpg"
        opf = open(tmpfile, 'wb+')
        for chunk in f.chunks():
            opf.write(chunk)
        opf.close()
        image_file = open(tmpfile, 'rb')
        image = bytes(image_file.read())
        img = types.Image(content=image)
        features = [types.Feature(type=types.Feature.SAFE_SEARCH_DETECTION, max_results=8),
                    types.Feature(type=types.Feature.LABEL_DETECTION, max_results=8)]
        gclient = vision.ImageAnnotatorClient()
        resp = gclient.annotate_image({'image' : img, 'features' : features})
</pre>

What makes this even stranger is that
<pre>
resp = gclient.label_detection(image=img)
</pre>
will work just fine in views

**Comment by tseaver** [comment] 2018-03-14 19:04
Just a stab in the dark:  can you try not constructing a `Feature` message, and instead pass the features as mappings?  E.g.:

```python
        features = [
            {'type': types.Feature.SAFE_SEARCH_DETECTION, 'max_results': 8},
            {'type': types.Feature.LABEL_DETECTION, 'max_results': 8},
        ]
        gclient = vision.ImageAnnotatorClient()
        resp = gclient.annotate_image({'image' : img, 'features' : features})
```

**Comment by tmillecam** [comment] 2018-03-14 20:12
I tried it both ways, the same error is thrown.  It seems to be isolated to the image area.  It also doesn't matter if I manually extend out that to {'image' : {'content' : image}}  The same error is thrown

**Comment by tseaver** [comment] 2018-03-15 01:26
At the point where the exception is raised, can you get a `pdb.pm` or `pdb.set_trace` and print out the `requests`?  E.g.:

```python
(pdb) pp requests
[
...
]
```

**Comment by tmillecam** [comment] 2018-03-15 04:28
I'll abbreviate it.  The type(requests[0]['image']) is marked as <class google.cloud.vision_v1.types.Image'>
<pre>
[{u'image' : '\n\xa5\x80\x08\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01 . . .'\x1c\xe3\x8fuH\xb1\x91\xf9S\xb7\x14\xce;\x04u\x04\xb5\x7f\xff\xd9'
 , 'features' : [type: SAFE_SEARCH_DETECTION
max_results: 8
, type: LABEL_DETECTION
max_results: 8
]}]
</pre>

**Comment by tseaver** [comment] 2018-03-15 17:30
Trying to reproduce.  Here is my script:

```python
import pprint

from google.cloud.vision_v1 import ImageAnnotatorClient
from google.cloud.vision_v1 import types

client = ImageAnnotatorClient()


FILENAME = '/usr/share/icons/hicolor/128x128/apps/firefox.png'

with open(FILENAME, 'rb') as f:
    img = types.Image(content=f.read())

features = [
    types.Feature(type=types.Feature.SAFE_SEARCH_DETECTION, max_results=8),
    types.Feature(type=types.Feature.LABEL_DETECTION, max_results=8),
]
request = {
    'image': img,
    'features': features,
}
resp = client.annotate_image(request)
pprint.pprint(resp)
```

Running it from a virtualenv with `google.cloud.vision` installed, and the appropriate environment variables for credentials, yields:

```bash
$ /path/to/virtualenv/bin/python3.6 investigate_5236.py 
label_annotations {
  mid: "/m/088fh"
  description: "yellow"
  score: 0.9105799794197083
  topicality: 0.9105799794197083
}
label_annotations {
  mid: "/m/0jc_p"
  description: "orange"
  score: 0.8353860378265381
  topicality: 0.8353860378265381
}
label_annotations {
  mid: "/m/03g09t"
  description: "clip art"
  score: 0.6202390789985657
  topicality: 0.6202390789985657
}
label_annotations {
  mid: "/m/021sdg"
  description: "graphics"
  score: 0.6196287274360657
  topicality: 0.6196287274360657
}
label_annotations {
  mid: "/m/01vkl"
  description: "circle"
  score: 0.5540978908538818
  topicality: 0.5540978908538818
}
label_annotations {
  mid: "/m/06y47"
  description: "sphere"
  score: 0.5511136054992676
  topicality: 0.5511136054992676
}
label_annotations {
  mid: "/m/03gq5hm"
  description: "font"
  score: 0.5489954352378845
  topicality: 0.5489954352378845
}
safe_search_annotation {
  adult: VERY_UNLIKELY
  spoof: VERY_UNLIKELY
  medical: VERY_UNLIKELY
  violence: VERY_UNLIKELY
  racy: VERY_UNLIKELY
}
```

Stepping into the call, the difference for me in the request is that the `mapping` key has a `content` subkey, e.g.:

```python
(Pdb) pp requests
[{'features': [type: SAFE_SEARCH_DETECTION
max_results: 8
,
               type: LABEL_DETECTION
max_results: 8
],
  'image': content: "\211PNG\..."
}]
```

**Comment by tmillecam** [comment] 2018-03-16 21:00
Yeah, as I mentioned, it works fine as a script, and will even work inside of a python manage.py shell for django, the problem only exists inside of a django view running in a wsgi environment.

**Comment by tseaver** [comment] 2018-03-26 16:17
@tmillecam One I can think to suggest is that the Django environment has a different version of `google-cloud-speech` installed.  Can you try running the script explicity with that version (skip and virtualenv activation, and use the full path to its python).

The other choice is that the Django environment is somehow wrapping / monkey-patching the speech library (which seems unlikely).

**Comment by tseaver** [comment] 2018-06-27 19:29
@tyggna Please reopen if you can provide more information to help reproduce the issue.

**Closed by tseaver** 2018-06-27 19:29 UTC
Labels: api: vision, priority: p2, status: awaiting information, type: bug
