### ISSUE TITLE
Pubsub.  Unexpected behaviour. Pubsub client does not pull messages it has previously processed without acking.

### ISSUE THREAD

**Issue by erlendcognite** [GoogleCloudPlatform/google-cloud-python#5044] opened 2018-03-15 15:58 UTC
macOS High Sierra 10.13.3. 
Python 3.6.2. 
google-cloud-core 0.28.1.

```
import logging
import re
import sys
import time

from google.cloud import pubsub_v1

logger = logging.getLogger(__file__)

PROJECT_ID = 'my_id'
SUBSCRIPTION_NAME = 'my_subscription'

def run():
    client = pubsub_v1.SubscriberClient()
    sub_name = 'projects/{}/subscriptions/{}'.format(PROJECT_ID, SUBSCRIPTION_NAME)
    subscription = client.subscribe(
        subscription=sub_name,
        callback=callback
    )
    while True:
        time.sleep(5)

def callback(message):
    success = process_message(message)
    if success:
        message.ack()
    # else:
    #     message.nack()

def process_message(message):
    print(message)
    return False

if __name__ == '__main__':
    run()
```

When I run this code, my client pulls messages on the queue once. It then does not ack the message, and the message returns to the queue after 10 seconds as expected. After a message returns to the queue, the client does however not pull the message again. If I explicitly nack the message, it does pull the message from the queue again.

I would expect the message to appear again in my client when I don’t nack, and the 10 seconds (default limit until it should appear again) has gone by.

**Comment by robhaswell** [comment] 2018-03-16 11:12
Is the client library extending the deadline on non-acked/nacked messages? If so, this sounds like expected behaviour and should just be documented.

**Comment by gcbirzan** [comment] 2018-03-19 10:05
Probably a duplicate of #5005.

**Comment by chemelnucfin** [comment] 2018-03-19 15:28
Yes, are you able to try upgrading the pubsub client?

**Comment by tseaver** [comment] 2018-03-19 17:49
@chemelnucfin That fix is not yet released.

@jonparrott Is it worth releasing a `pubsub-0.32.2` right now, even though we are chasing other pubsub issues?

@erlendcognite Could you try updating to the head?  E.g., in your virtualenv:

```bash
$ pip install -U git+https://github.com/GoogleCloudPython/google-cloud-python
```

**Comment by jonparrott** [comment] 2018-03-19 18:00
No, I want to wait for #5054 before I cut a new release. @lukesneeringer is testing it now.

**Comment by jonparrott** [comment] 2018-03-19 18:00
@tseaver that pip command won't work.

**Comment by tseaver** [comment] 2018-03-19 18:14
@jonparrott Ugh, sorry about that!

@erlendcognite The corrected command line:

```bash
$ pip install https://github.com/GoogleCloudPlatform/google-cloud-python/archive/master.zip
```

**Comment by jonparrott** [comment] 2018-03-19 18:16
Does that even work? That'll just install the umbrella package from source, not necessarily the real packages from source, maybe:

```
git clone https://github.com/GoogleCloudPython/google-cloud-python
pip install google-cloud-python/pubsub
```

**Comment by stianlagstad** [comment] 2018-03-19 19:31
@robhaswell: I'm fairly certain the deadline was not exceeded in @erlendcognite's case. (Answering as his colleague.)

**Comment by jonparrott** [comment] 2018-03-20 18:13
This is related (and somewhat duplicative of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5005).

Basically, not acking a message doesn't automatically nack it. The subscriber will actually keep leasing the message indefinitely (with a caveat, see below). You *must* call ack or nack.

We introduced `flow_control.max_lease_duration` (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5020) to deal with bad actors - by default, if nothing happens to a message in 2 hours the subscriber will nack it.

**Closed by jonparrott** 2018-03-20 18:13 UTC
Labels: api: pubsub, priority: p2, type: bug

**Comment by stianlagstad** [comment] 2018-03-20 18:25
Thanks @jonparrott! That's the kind of flag we need :)
