### ISSUE TITLE
Update the NL Library to v1 API

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/google-cloud-python#2745] opened 2016-11-16 23:44 UTC
The library needs to be updated to the new version of API aka v1.

**Comment by jonparrott** [comment] 2016-11-16 23:46
@puneith do you wanna take that on or do you want me or @ryanmats to do it?

**Comment by puneith** [comment] 2016-11-16 23:47
You mean the creation of the library itself and v1 upgrade?

**Comment by bjwatson** [comment] 2016-11-19 00:55
We're on top of it. :)

This is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2747.

**Closed by bjwatson** 2016-11-19 00:55 UTC
Labels: natural-language
