### ISSUE TITLE
Logging: 503 Deadline Exceeded exceptions when logging from imported module

### ISSUE THREAD

**Issue by d-tw** [GoogleCloudPlatform/google-cloud-python#6060] opened 2018-09-22 20:51 UTC
Hi,

I'm encountering `ServiceUnavailable: 503 Deadline Exceeded` exceptions when I call `logger.log_struct` from a method that's called during a module import.

**Versions**
python version: 2.7.14
google-cloud-logging version: 1.7.0

**Stacktrace**
```
Traceback (most recent call last):
  File "indirect.py", line 1, in <module>
    import direct
  File "/Users/d_tw/Dropbox/Development/projects/log_test/direct.py", line 3, in <module>
    records = setup()
  File "/Users/d_tw/Dropbox/Development/projects/log_test/setup.py", line 7, in setup
    logger.log_struct({'message': 'hello'})
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/cloud/logging/logger.py", line 289, in log_struct
    client.logging_api.write_entries([entry_resource])
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/cloud/logging/_gapic.py", line 124, in write_entries
    partial_success=partial_success)
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/cloud/logging_v2/gapic/logging_service_v2_client.py", line 341, in write_log_entries
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 61, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/d_tw/.pyenv/versions/log_test/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.ServiceUnavailable: 503 Deadline Exceeded
[1]    17650 exit 1     python indirect.py
```

**Code sample**

File 1: `log_test.py`

```python
import google.cloud.logging as logging


def setup():
    client = logging.Client()
    logger = client.logger('test')
    logger.log_struct({'message': 'hello'})
```

File 2: `direct.py`
```python
from log_test import setup

setup()
```

File 3: `indirect.py`
```python
import direct
```

**Steps**

When I run the following, the message is logged to Stackdriver without any issues.

```
python ./direct.py
```

When I run the following, a `ServiceUnavailable: 503 Deadline Exceeded` exception is thrown

```
python ./indirect.py
```

The only difference I can see is that in one case, `logger.log_struct` is called during an `import`, although this may be unrelated. This occurs regardless of the `GOOGLE_APPLICATION_CREDENTIALS` value that I set.

I can probably work around this issue, but does anyone know why it occurs?

Thanks!

**Comment by tseaver** [comment] 2018-09-22 21:32
Interesting:  I was just now able to run each script without errors under Python 3.6, but can reproduce the failure you note under Python 2.7.

**Comment by tseaver** [comment] 2018-09-24 16:04
Hmmm, I was just able to get the `indirect.py` reproduction case to work on Python 2.7 by disabling gRPC, i.e., forcing it to log to the REST API.  E.g.:

```bash
$ GOOGLE_CLOUD_DISABLE_GRPC=1 python2.7 ./indirect.py 
```

That workaround indicates that the bug lies either in `logging/_gapic.py`, `logging_v2/...`, or in `grpcio` itself.

**Comment by d-tw** [comment] 2018-09-25 22:13
Are there significant downsides to disabling GRPC? How long until the REST API is deprecated?

In the meanwhile, I have found a workaround by initialising the Stackdriver client in a background thread and feeding the log messages through a queue, heavily inspired by the [`BackgroundThreadTransport`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py) from the `google-cloud-logging` package.

**Comment by tseaver** [comment] 2018-09-25 23:01
> Are there significant downsides to disabling GRPC?

gRPC ought to be more performant.  If you are logging in high volumes, that will matter more.

> How long until the REST API is deprecated?

Never, AFAIK:  I don't see any mention of its deprecation anywhere in the [docs](https://cloud.google.com/logging).

Doing significant work at import time is always going to be problematic.  In addition to weirness like the bit you encounter here, it can mess with code discovery (e.g., in your editor) or other stuff which expects `import` to be lightweight.

FWIW, I would much prefer to call the `setup()` function you outline above from inside the `if __name__ == '__main__':` block of the application (or another function called transitively from there).  That allows the other bits of code in your app to be more easily tested / composed without the application's policy.

**Comment by tseaver** [comment] 2018-09-26 18:19
@d-tw I'm going to close the issue because I can't see anything we can do to fix it in `google-cloud-logging`, and because there is a workaround / best practice which mitigates it.  Please feel free to follow up if you discover more.

**Closed by tseaver** 2018-09-26 18:19 UTC
Labels: api: logging, priority: p2, status: will not fix, type: bug
