### ISSUE TITLE
No module named proto.datastore.v1

### ISSUE THREAD

**Issue by yogeshesoft** [GoogleCloudPlatform/google-cloud-python#3077] opened 2017-02-27 15:49 UTC
We just installed google cloud SDK and all with the below list of cmds, still we are facing the issue like ImportError: No module named proto.datastore.v1, we try to deploy and running Flask  app-engine flexible environment in localhost

The issue we are facing in Windows OS and python 2.7.9

pip install --upgrade google-cloud-datastore
pip install gapic-google-cloud-datastore-v1
pip install googledatastore

This is the code we are using......

def init_app(app):
    pass

def get_client():
    return datastore.Client(current_app.config['PROJECT_ID'],
                            namespace=current_app.config['DEFAULT_DATASTORE_NAMESPACE'])

def from_datastore(entity):
    """Translates Datastore results into the format expected by the
    application.

    Datastore typically returns:
        [Entity{key: (kind, id), prop: val, ...}]

    This returns:
        {id: id, prop: val, ...}
    """
    if not entity:
        return None
    if isinstance(entity, builtin_list):
        entity = entity.pop()

    entity['id'] = entity.key.id

    return entity

# authorizes user_id (email address) with datastore
def authorize_id(user_id):
    ds = get_client()
    key = ds.key(kind, user_id)
    print(key)
    results = ds.get(key)
    if results is not None:
        print(results)
        return results['role']
    return None

**Comment by daspecster** [comment] 2017-02-27 16:00
@yogeshesoft I'm guessing that there is something contaminated in your environment.

You might try creating a new virtualenv and seeing if the issue clears up.

If that doesn't resolve the issue, could you post the output of `pip freeze` so we can see what versions of the packages are installed?

**Comment by lukesneeringer** [comment] 2017-02-28 20:02
Nope, that is a problem with us actually. If you upgrade `proto-google-cloud-python-datastore-v1` and `gapic-google-cloud-python-datastore-v1`, it should be fixed.

Feel free to reopen if that does not work for you.

**Closed by lukesneeringer** 2017-02-28 20:02 UTC
Labels: API: datastore, GAX

**Comment by ReddingSoftware** [comment] 2020-11-16 17:09
The problem is you need to change your requirements text to google-cloud-ndb==1.7.1

For some reason, the older versions of google cloud NDB no longer work correctly.
