### ISSUE TITLE
Logging seems to not support type.googleapis.com/google.cloud.audit.AuditLog.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3218] opened 2017-03-28 14:49 UTC
@waprin Logging does not seem to support [type.googleapis.com/google.cloud.audit.AuditLog](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog).

```bash
 File "test_logging.py", line 9, in <module>
    for entry in client.list_entries():  # API call(s)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/cloud/iterator.py", line 219, in _items_iter
    for item in page:
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/cloud/iterator.py", line 163, in next
    result = self._item_to_value(self._parent, item)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/cloud/logging/_gax.py", line 488, in _item_to_entry
    resource = MessageToDict(entry_pb)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 133, in MessageToDict
    return printer._MessageToJsonObject(message)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 164, in _MessageToJsonObject
    return self._RegularMessageToJsonObject(message, js)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 196, in _RegularMessageToJsonObject
    js[name] = self._FieldToJsonObject(field, value)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 230, in _FieldToJsonObject
    return self._MessageToJsonObject(value)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 162, in _MessageToJsonObject
    return methodcaller(_WKTJSONMETHODS[full_name][0], message)(self)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 266, in _AnyMessageToJsonObject
    sub_message = _CreateMessageFromTypeUrl(type_url)
  File "/Users/daspecster/.virtualenvs/test-gcp/lib/python2.7/site-packages/google/protobuf/json_format.py", line 341, in _CreateMessageFromTypeUrl
    'Can not find message descriptor by type_url: {0}.'.format(type_url))
TypeError: Can not find message descriptor by type_url: type.googleapis.com/google.cloud.audit.AuditLog.
```

These entries are for things like auth logging/auditing. I think this popped up for me because I just checked all logs and not a specific services log. However I would imagine this would a common log type to support?

**Comment by dhermes** [comment] 2017-03-28 15:57
@daspecster It's not about what `Logging` supports, it's about our parsing of `Any` protobufs. When a type is encountered that isn't in the `google.protobuf` registry, `google.protobuf` barfs.

In other words, this bug is a lot more generic than `AuditLog`

**Comment by daspecster** [comment] 2017-03-28 17:02
@dhermes yeah, I gathered.

Isn't this a problem for GA though?

/cc @lukesneeringer

**Comment by dhermes** [comment] 2017-03-28 17:05
Yes it is a problem for GA

**Comment by waprin** [comment] 2017-03-28 17:54
I don't think working with AuditLogs are the most critical thing in general (the are mostly for compliance and we have Cloud Console tooling for them), but agree with @dhermes the general bug seems like a pretty big issue, especially if crash while just reading all the logs.

**Comment by lukesneeringer** [comment] 2017-03-28 20:52
@dhermes Any thoughts on the correct fix?

**Comment by dhermes** [comment] 2017-03-28 20:55
The culprit is our usage of the `google.protobuf` parsers:

```
$ git grep -n protobuf -- logging/google/ | grep import
logging/google/cloud/logging/_gax.py:32:from google.protobuf.json_format import MessageToDict
logging/google/cloud/logging/_gax.py:33:from google.protobuf.json_format import ParseDict
logging/google/cloud/logging/entries.py:20:from google.protobuf.json_format import Parse
logging/google/cloud/logging/logger.py:19:from google.protobuf.json_format import MessageToJson
```

**Comment by dhermes** [comment] 2017-03-31 20:06
Closing as duplicate of #2674

**Closed by dhermes** 2017-03-31 20:06 UTC
Labels: api: logging, priority: p2+
